name = "CGJteamLab"
version = "0.1.0"
defaultTargets = ["cgjteamlab"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "CGJteamLab"

[[lean_exe]]
name = "cgjteamlab"
root = "Main"
