import CGJteamLab.E4HyperplaneProper

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# Derived E4 hyperplane incidence core

This module completes the basic hyperplane incidence consequences of

    SalasIncidence + E4Dimension.

No new axiom is introduced here.

At this point the five ingredients formerly stored in the primitive
`Hilbert4DHyperplaneIncidenceCore` are available as theorems for the
derived type `E4Hyperplane`:

* hyperplane through four noncoplanar points;
* a point on every hyperplane;
* uniqueness through four noncoplanar points;
* line closure inside a hyperplane;
* existence of five nonhyperplanar points.
-/

/--
Two derived E4 hyperplanes are equal when their carriers are equal.
-/
theorem e4Hyperplane_ext
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    {Sigma Tau : E4Hyperplane Geo}
    (hCarrier : Sigma.carrier = Tau.carrier) :
    Sigma = Tau := by

  cases Sigma with
  | mk carrierSigma generatedSigma properSigma =>
      cases Tau with
      | mk carrierTau generatedTau properTau =>
          dsimp at hCarrier
          subst carrierTau
          rfl


/--
The four named generators are contained in the Smith span generated by
them.
-/
theorem e4_quad_generators_subset_span
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (A B C D : Geo.Point) :
    Set.Subset
      (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D)
      (SmithSpan Geo
        (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D)) := by

  exact
    smithSpan_extensive
      (Geo := Geo)
      (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D)


/--
Any derived E4 hyperplane containing four named points also contains the
Smith span generated by those four points.
-/
theorem e4_quad_span_subset_hyperplane
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (Sigma : E4Hyperplane Geo)
    (A B C D : Geo.Point)
    (hASigma : E4OnHyperplane Geo A Sigma)
    (hBSigma : E4OnHyperplane Geo B Sigma)
    (hCSigma : E4OnHyperplane Geo C Sigma)
    (hDSigma : E4OnHyperplane Geo D Sigma) :
    Set.Subset
      (SmithSpan Geo
        (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D))
      Sigma.carrier := by

  apply
    smithSpan_least
      (Geo := Geo)
      (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D)
      Sigma.carrier
      (e4Hyperplane_flat
        (Geo := Geo)
        Sigma)

  intro X hX
  rcases hX with hXD | hABC

  · subst X
    exact hDSigma

  · rcases hABC with hXA | hXB | hXC

    · subst X
      exact hASigma

    · subst X
      exact hBSigma

    · subst X
      exact hCSigma


/--
A derived E4 hyperplane containing four noncoplanar points is exactly the
canonical Smith span generated by those four points.
-/
theorem salas_e4_hyperplane_carrier_eq_quad_span
    [H : HilbertIncidence Geo]
    [HP : HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [SalasIncidence Geo]
    [D4 : E4Dimension Geo]
    (A B C D : Geo.Point)
    (hNoncoplanar :
      Not (HilbertCoplanar4 Geo A B C D))
    (Sigma : E4Hyperplane Geo)
    (hASigma : E4OnHyperplane Geo A Sigma)
    (hBSigma : E4OnHyperplane Geo B Sigma)
    (hCSigma : E4OnHyperplane Geo C Sigma)
    (hDSigma : E4OnHyperplane Geo D Sigma) :
    Sigma.carrier =
      SmithSpan Geo
        (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D) := by

  let F : Set Geo.Point :=
    SmithSpan Geo
      (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D)

  have hGenerated :
      E4Generated3Flat Geo F := by
    dsimp [F]
    exact
      salas_noncoplanar4_generates_3flat
        (Geo := Geo)
        A B C D
        hNoncoplanar

  have hProper :
      Ne F (Set.univ : Set Geo.Point) :=
    salas_e4_generated3Flat_proper
      (Geo := Geo)
      F
      hGenerated

  let Canon : E4Hyperplane Geo :=
    {
      carrier := F
      generated3Flat := hGenerated
      proper := hProper
    }

  have hFSubsetSigma :
      Set.Subset F Sigma.carrier := by
    dsimp [F]
    exact
      e4_quad_span_subset_hyperplane
        (Geo := Geo)
        Sigma
        A B C D
        hASigma hBSigma hCSigma hDSigma

  have hMax :
      Sigma.carrier = F \/
      Sigma.carrier = (Set.univ : Set Geo.Point) := by

    have h :=
      e4Hyperplane_maximal
        (Geo := Geo)
        Canon
        Sigma.carrier
        (e4Hyperplane_flat
          (Geo := Geo)
          Sigma)
        (by
          dsimp [Canon]
          exact hFSubsetSigma)

    simpa [Canon] using h

  rcases hMax with hEq | hUniv

  · dsimp [F] at hEq
    exact hEq

  · exact False.elim (Sigma.proper hUniv)


/--
Four noncoplanar points determine a derived E4 hyperplane uniquely.
-/
theorem salas_e4_hyperplane_unique_noncoplanar4
    [H : HilbertIncidence Geo]
    [HP : HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [SalasIncidence Geo]
    [E4Dimension Geo]
    (A B C D : Geo.Point)
    (hNoncoplanar :
      Not (HilbertCoplanar4 Geo A B C D))
    (Sigma Tau : E4Hyperplane Geo)
    (hASigma : E4OnHyperplane Geo A Sigma)
    (hBSigma : E4OnHyperplane Geo B Sigma)
    (hCSigma : E4OnHyperplane Geo C Sigma)
    (hDSigma : E4OnHyperplane Geo D Sigma)
    (hATau : E4OnHyperplane Geo A Tau)
    (hBTau : E4OnHyperplane Geo B Tau)
    (hCTau : E4OnHyperplane Geo C Tau)
    (hDTau : E4OnHyperplane Geo D Tau) :
    Sigma = Tau := by

  have hSigma :
      Sigma.carrier =
        SmithSpan Geo
          (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D) :=
    salas_e4_hyperplane_carrier_eq_quad_span
      (Geo := Geo)
      A B C D
      hNoncoplanar
      Sigma
      hASigma hBSigma hCSigma hDSigma

  have hTau :
      Tau.carrier =
        SmithSpan Geo
          (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D) :=
    salas_e4_hyperplane_carrier_eq_quad_span
      (Geo := Geo)
      A B C D
      hNoncoplanar
      Tau
      hATau hBTau hCTau hDTau

  apply
    e4Hyperplane_ext
      (Geo := Geo)

  exact hSigma.trans hTau.symm


/--
Five points are hyperplanar in the derived E4 sense when one derived
hyperplane contains all five.
-/
def E4Hyperplanar5
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (A B C D E : Geo.Point) : Prop :=
  exists Sigma : E4Hyperplane Geo,
    E4OnHyperplane Geo A Sigma /\
    E4OnHyperplane Geo B Sigma /\
    E4OnHyperplane Geo C Sigma /\
    E4OnHyperplane Geo D Sigma /\
    E4OnHyperplane Geo E Sigma


/--
Every five-point E4 frame is nonhyperplanar in the derived sense.
-/
theorem e4Frame_not_hyperplanar5
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [D4 : E4Dimension Geo]
    (A B C D E : Geo.Point)
    (hFrame : E4Frame Geo A B C D E) :
    Not (E4Hyperplanar5 Geo A B C D E) := by

  intro hHyper
  rcases hHyper with
    ⟨Sigma,
     hASigma,
     hBSigma,
     hCSigma,
     hDSigma,
     hESigma⟩

  have hFiveSubset :
      Set.Subset
        (E4PointFive Geo A B C D E)
        Sigma.carrier := by

    intro X hX
    rcases hX with hXE | hRest

    · subst X
      exact hESigma

    · rcases hRest with hXD | hABC

      · subst X
        exact hDSigma

      · rcases hABC with hXA | hXB | hXC

        · subst X
          exact hASigma

        · subst X
          exact hBSigma

        · subst X
          exact hCSigma

  have hSpanSubset :
      Set.Subset
        (SmithSpan Geo (E4PointFive Geo A B C D E))
        Sigma.carrier :=
    smithSpan_least
      (Geo := Geo)
      (E4PointFive Geo A B C D E)
      Sigma.carrier
      (e4Hyperplane_flat
        (Geo := Geo)
        Sigma)
      hFiveSubset

  have hSpanUniv :
      SmithSpan Geo (E4PointFive Geo A B C D E) =
        (Set.univ : Set Geo.Point) :=
    e4Frame_span_eq_univ
      (Geo := Geo)
      A B C D E
      hFrame

  have hUnivSubset :
      Set.Subset
        (Set.univ : Set Geo.Point)
        Sigma.carrier := by
    rw [<- hSpanUniv]
    exact hSpanSubset

  have hCarrierUniv :
      Sigma.carrier =
        (Set.univ : Set Geo.Point) := by

    apply Set.Subset.antisymm

    · intro X hX
      trivial

    · exact hUnivSubset

  exact Sigma.proper hCarrierUniv


/--
Dimension four supplies five points which are not contained in any
derived E4 hyperplane.
-/
theorem e4Dimension_exists_five_nonhyperplanar
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [D4 : E4Dimension Geo] :
    exists A B C D E : Geo.Point,
      Not (E4Hyperplanar5 Geo A B C D E) := by

  rcases D4.frame_exists with
    ⟨A, B, C, D, E, hFrame⟩

  exact
    ⟨A, B, C, D, E,
     e4Frame_not_hyperplanar5
       (Geo := Geo)
       A B C D E
       hFrame⟩

end Geometry
