-- E4HyperplaneXI12 FIX1 - 2026-09-11
import CGJteamLab.E4HyperplaneFrameCriterionDerived
import CGJteamLab.Coxeter.E4NormalSectionNormal
import CGJteamLab.Hilbert4DHyperplaneCarriers

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# Euclid XI.12 lifted to E4 hyperplanes

This file derives the E4 analogue of Euclid XI.12:

  from a point O of an E4 hyperplane Sigma, there exists a line
  perpendicular to Sigma at O.

The construction is dimension-correct.

1. Choose an ambient 2-plane Delta contained in Sigma and passing through O.
2. Choose P outside Sigma.
3. Let Tau be the hyperplane generated by Delta and P.
4. Sigma and Tau meet exactly in Delta.
5. The existing normal-section theorem constructs the normal 2-plane of
   the pair (Sigma,Tau) at O.
6. The existing normal-section-normal theorem constructs in that plane a
   line perpendicular to Sigma at O.
7. The only former extra boundary used by that theorem, the E4 hyperplane
   frame criterion, is supplied here by the derived XI.4 theorem.

No normal-existence axiom is assumed.
-/

local instance derivedHyperplaneFrameCriterion_XI12
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    [Hilbert4DAmbientIncidence Geo]
    [Hilbert4DHyperplaneLocal3DIncidence Geo]
    [Hilbert4DAmbientOrder Geo]
    [Hilbert4DAmbientCongruence Geo] :
    Hilbert4DHyperplanePerpendicularFrameCriterion_corrected Geo :=
  hilbert4D_hyperplanePerpendicularFrameCriterion_of_XI4
    (Geo := Geo)


/--
Every point of an E4 hyperplane lies in an ambient 2-plane contained in
that hyperplane.
-/
theorem hilbert4D_plane_in_hyperplane_through_point_corrected
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    [H4I : Hilbert4DAmbientIncidence Geo]
    [H4L : Hilbert4DHyperplaneLocal3DIncidence Geo]
    (Sigma : Q.Hyperplane)
    (O : Geo.Point)
    (hOSigma : Q.OnHyperplane O Sigma) :
    exists Delta : Q.toHilbertSpacePrimitive.Plane,
      Q.toHilbertSpacePrimitive.OnPlane O Delta /\
      HilbertPlaneInHyperplane4 Geo Delta Sigma := by

  rcases H4L.four_noncoplanar_on_hyperplane Sigma with
    ⟨A, B, C, D,
     hASigma, hBSigma, _hCSigma, _hDSigma,
     hNoncop⟩

  have hABC :
      Not (PrimCollinear Geo A B C) :=
    hilbert4D_noncoplanar4_first_three_noncollinear_corrected
      (Geo := Geo)
      A B C D
      hNoncop

  have hAB : Ne A B :=
    hilbert_noncollinear_ne_first
      (Geo := Geo)
      A B C
      hABC

  by_cases hOA : O = A

  case pos =>
    let OSigma : HyperplanePoint4 Geo Sigma :=
      ⟨O, hOSigma⟩

    let BSigma : HyperplanePoint4 Geo Sigma :=
      ⟨B, hBSigma⟩

    have hOB : Ne O B := by
      intro hOB
      apply hAB
      exact hOA.symm.trans hOB

    have hOBSub : Ne OSigma BSigma := by
      intro hEq
      apply hOB
      exact congrArg Subtype.val hEq

    rcases
        hyperplaneGeo4_plane_through_point_avoiding_point_corrected
          (Geo := Geo)
          Sigma
          OSigma BSigma
          hOBSub with
      ⟨DeltaLocal, hODeltaLocal, _hBoff⟩

    exact
      ⟨DeltaLocal.1,
       hODeltaLocal,
       DeltaLocal.2⟩

  case neg =>
    let OSigma : HyperplanePoint4 Geo Sigma :=
      ⟨O, hOSigma⟩

    let ASigma : HyperplanePoint4 Geo Sigma :=
      ⟨A, hASigma⟩

    have hOASub : Ne OSigma ASigma := by
      intro hEq
      apply hOA
      exact congrArg Subtype.val hEq

    rcases
        hyperplaneGeo4_plane_through_point_avoiding_point_corrected
          (Geo := Geo)
          Sigma
          OSigma ASigma
          hOASub with
      ⟨DeltaLocal, hODeltaLocal, _hAoff⟩

    exact
      ⟨DeltaLocal.1,
       hODeltaLocal,
       DeltaLocal.2⟩


/--
Given Sigma and O in Sigma, construct a second hyperplane Tau such that
Sigma and Tau meet exactly in a 2-plane Delta containing O.
-/
theorem hilbert4D_auxiliary_hyperplane_pair_at_point_corrected
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    [D : HilbertDimensionFreeIncidence Geo]
    [H4I : Hilbert4DAmbientIncidence Geo]
    [C4 : Hilbert4DHyperplaneIncidenceCore Geo]
    [H4L : Hilbert4DHyperplaneLocal3DIncidence Geo]
    (Sigma : Q.Hyperplane)
    (O : Geo.Point)
    (hOSigma : Q.OnHyperplane O Sigma) :
    exists Tau : Q.Hyperplane,
      exists Delta : Q.toHilbertSpacePrimitive.Plane,
        Q.toHilbertSpacePrimitive.OnPlane O Delta /\
        HyperplanesMeetInPlane4_corrected
          Geo Sigma Tau Delta := by

  rcases
      hilbert4D_plane_in_hyperplane_through_point_corrected
        (Geo := Geo)
        Sigma O hOSigma with
    ⟨Delta, hODelta, hDeltaSigma⟩

  rcases
      hilbert4D_point_off_hyperplane_corrected
        (Geo := Geo)
        Sigma with
    ⟨P, hPSigma⟩

  have hPDelta :
      Not
        (Q.toHilbertSpacePrimitive.OnPlane P Delta) := by
    intro hPDelta
    exact hPSigma (hDeltaSigma P hPDelta)

  rcases
      hilbert4D_hyperplane_through_plane_and_external_point_corrected
        (Geo := Geo)
        Delta P hPDelta with
    ⟨Tau, hDeltaTau, hPTau⟩

  have hSigmaTau : Ne Sigma Tau := by
    intro hEq
    apply hPSigma
    rw [hEq]
    exact hPTau

  have hMeet :
      HyperplanesMeetInPlane4_corrected
        Geo Sigma Tau Delta := by

    unfold HyperplanesMeetInPlane4_corrected

    refine And.intro hSigmaTau ?_
    refine And.intro hDeltaSigma ?_
    refine And.intro hDeltaTau ?_

    intro X

    constructor

    case mp =>
      intro hXBoth

      by_contra hXDelta

      have hEq :
          Sigma = Tau :=
        hilbert4D_hyperplane_unique_of_plane_and_external_point_corrected
          (Geo := Geo)
          Delta X hXDelta
          Sigma Tau
          hDeltaSigma hXBoth.1
          hDeltaTau hXBoth.2

      exact hSigmaTau hEq

    case mpr =>
      intro hXDelta

      exact
        And.intro
          (hDeltaSigma X hXDelta)
          (hDeltaTau X hXDelta)

  exact
    Exists.intro Tau
      (Exists.intro Delta
        (And.intro hODelta hMeet))


/--
Dimension-correct E4 analogue of Euclid XI.12.

At every point O of an E4 hyperplane Sigma there exists a line
perpendicular to Sigma at O.
-/
theorem hilbert4D_XI12_normal_at_hyperplane_point_corrected
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    [D : HilbertDimensionFreeIncidence Geo]
    [H4I : Hilbert4DAmbientIncidence Geo]
    [C4 : Hilbert4DHyperplaneIncidenceCore Geo]
    [H4L : Hilbert4DHyperplaneLocal3DIncidence Geo]
    [Hilbert4DAmbientOrder Geo]
    [Hilbert4DAmbientCongruence Geo]
    [Hilbert4DAmbientEuclidean Geo]
    (Sigma : Q.Hyperplane)
    (O : Geo.Point)
    (hOSigma : Q.OnHyperplane O Sigma) :
    exists r : Geo.Line,
      HilbertLinePerpendicularHyperplaneAt4_corrected
        Geo r Sigma O := by

  rcases
      hilbert4D_auxiliary_hyperplane_pair_at_point_corrected
        (Geo := Geo)
        Sigma O hOSigma with
    ⟨Tau, Delta, hODelta, hMeet⟩

  rcases
      hilbert4D_hyperplane_pair_normal_section_exists_corrected
        (Geo := Geo)
        Sigma Tau
        Delta
        hMeet
        O hODelta with
    ⟨s, t,
     hSPerp, hTPerp,
     hst,
     N, hON, hsN, htN⟩

  rcases
      hilbert4D_normal_to_hyperplane_inside_normal_section_corrected
        (Geo := Geo)
        Sigma Tau
        Delta N
        hMeet
        O hODelta
        s t
        hSPerp hTPerp
        hst
        hON hsN htN with
    ⟨r, _hrN, _hOr, _hrPerpS, hNormal⟩

  exact
    Exists.intro r hNormal

end Geometry
