-- E4HyperplaneProper FIX5 - 2026-09-11
import CGJteamLab.E4HyperplaneIncidence

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# Properness of arbitrary generated E4 hyperplanes

This module proves the first genuinely rank-theoretic consequence of

    Sancho de Salas LP1-LP4 + E4Dimension.

The goal is to show that every 3-flat generated by four noncoplanar
points is proper.  The lower-dimensional witness in `E4Dimension`
contains a five-point frame.  The proof uses the Steinitz exchange law
already derived from Salas incidence.

No new axiom is introduced here.
-/

/--
Adjoin all points from a finite list to a base set.
-/
def E4AdjoinList
    (X : Set Geo.Point)
    (L : List Geo.Point) : Set Geo.Point :=
  fun P =>
    X P \/ List.Mem P L


/--
Adjoining a list with a new head is the same set as first adjoining the
tail and then adjoining the head.
-/
theorem e4AdjoinList_cons
    (X : Set Geo.Point)
    (Q : Geo.Point)
    (L : List Geo.Point) :
    E4AdjoinList Geo X (Q :: L) =
      SmithAdjoinPoint Geo (E4AdjoinList Geo X L) Q := by

  apply Set.ext
  intro P
  constructor

  · intro hP
    change X P \/ List.Mem P (Q :: L) at hP
    change P = Q \/ (X P \/ List.Mem P L)

    rcases hP with hPX | hPmem

    · exact Or.inr (Or.inl hPX)

    · rcases List.mem_cons.mp hPmem with hPQ | hPmemL
      · exact Or.inl hPQ
      · exact Or.inr (Or.inr hPmemL)

  · intro hP
    change P = Q \/ (X P \/ List.Mem P L) at hP
    change X P \/ List.Mem P (Q :: L)

    rcases hP with hPQ | hRest

    · exact Or.inr (List.mem_cons.mpr (Or.inl hPQ))

    · rcases hRest with hPX | hPmemL
      · exact Or.inl hPX
      · exact Or.inr (List.mem_cons.mpr (Or.inr hPmemL))


/--
Adjoining one point to the base before adjoining a list is the same set
as adjoining the list first and then the point.
-/
theorem e4AdjoinList_adjoin_comm
    (X : Set Geo.Point)
    (P : Geo.Point)
    (L : List Geo.Point) :
    E4AdjoinList Geo (SmithAdjoinPoint Geo X P) L =
      SmithAdjoinPoint Geo (E4AdjoinList Geo X L) P := by

  apply Set.ext
  intro Q
  constructor

  · intro hQ
    change (Q = P \/ X Q) \/ List.Mem Q L at hQ
    change Q = P \/ (X Q \/ List.Mem Q L)
    tauto

  · intro hQ
    change Q = P \/ (X Q \/ List.Mem Q L) at hQ
    change (Q = P \/ X Q) \/ List.Mem Q L
    tauto


/--
Adjoining the empty list changes nothing.
-/
theorem e4AdjoinList_nil
    (X : Set Geo.Point) :
    E4AdjoinList Geo X [] = X := by

  apply Set.ext
  intro P
  unfold E4AdjoinList
  constructor

  · intro hP
    rcases hP with hPX | hMem

    · exact hPX

    · cases hMem

  · intro hPX
    exact Or.inl hPX


/--
If two generating sets have the same Smith span, adjoining the same
point preserves equality of their spans.
-/
theorem e4_span_adjoin_congr
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (X Y : Set Geo.Point)
    (P : Geo.Point)
    (hXY :
      SmithSpan Geo X =
        SmithSpan Geo Y) :
    SmithSpan Geo (SmithAdjoinPoint Geo X P) =
      SmithSpan Geo (SmithAdjoinPoint Geo Y P) := by

  calc
    SmithSpan Geo (SmithAdjoinPoint Geo X P)
        =
      SmithSpan Geo
        (SmithAdjoinPoint Geo (SmithSpan Geo X) P) := by
          symm
          exact
            e4_span_adjoin_span_eq_adjoin
              (Geo := Geo) X P
    _ =
      SmithSpan Geo
        (SmithAdjoinPoint Geo (SmithSpan Geo Y) P) := by
          rw [hXY]
    _ =
      SmithSpan Geo (SmithAdjoinPoint Geo Y P) := by
          exact
            e4_span_adjoin_span_eq_adjoin
              (Geo := Geo) Y P


/--
One-step Steinitz replacement.

If P first appears after adjoining Q to X, then Q can be replaced by P
without changing the generated Smith span.
-/
theorem e4_exchange_replace_one
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (hExchange : SmithSpanExchange Geo)
    (X : Set Geo.Point)
    (P Q : Geo.Point)
    (hPin :
      SmithSpan Geo (SmithAdjoinPoint Geo X Q) P)
    (hPout :
      Not (SmithSpan Geo X P)) :
    SmithSpan Geo (SmithAdjoinPoint Geo X P) =
      SmithSpan Geo (SmithAdjoinPoint Geo X Q) := by

  have hQin :
      SmithSpan Geo (SmithAdjoinPoint Geo X P) Q :=
    hExchange.exchange
      X
      P Q
      hPin
      hPout

  apply Set.Subset.antisymm

  · apply
      smithSpan_least
        (Geo := Geo)
        (SmithAdjoinPoint Geo X P)
        (SmithSpan Geo (SmithAdjoinPoint Geo X Q))
        (smithSpan_flat
          (Geo := Geo)
          (SmithAdjoinPoint Geo X Q))

    intro R hR
    rcases hR with hRP | hRX

    · subst R
      exact hPin

    · exact
        smithSpan_extensive
          (Geo := Geo)
          (SmithAdjoinPoint Geo X Q)
          (Or.inr hRX)

  · apply
      smithSpan_least
        (Geo := Geo)
        (SmithAdjoinPoint Geo X Q)
        (SmithSpan Geo (SmithAdjoinPoint Geo X P))
        (smithSpan_flat
          (Geo := Geo)
          (SmithAdjoinPoint Geo X P))

    intro R hR
    rcases hR with hRQ | hRX

    · subst R
      exact hQin

    · exact
        smithSpan_extensive
          (Geo := Geo)
          (SmithAdjoinPoint Geo X P)
          (Or.inr hRX)


/--
Finite Steinitz reduction.

If P lies in the span of X together with a finite list L, but P is
outside Span(X), then one generator from L can be removed after adjoining
P to the base, without changing the final span.

The returned list has exactly one fewer element.
-/
theorem e4_exchange_reduce_generator_list
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (hExchange : SmithSpanExchange Geo)
    (X : Set Geo.Point)
    (L : List Geo.Point)
    (P : Geo.Point)
    (hPout :
      Not (SmithSpan Geo X P))
    (hPin :
      SmithSpan Geo (E4AdjoinList Geo X L) P) :
    exists R : List Geo.Point,
      R.length + 1 = L.length /\
      SmithSpan Geo
          (E4AdjoinList Geo
            (SmithAdjoinPoint Geo X P) R) =
        SmithSpan Geo (E4AdjoinList Geo X L) := by

  induction L with

  | nil =>
      exfalso
      apply hPout

      rw [e4AdjoinList_nil (Geo := Geo) X] at hPin
      exact hPin

  | cons Q L ih =>

      have hCons :
          E4AdjoinList Geo X (Q :: L) =
            SmithAdjoinPoint Geo
              (E4AdjoinList Geo X L) Q :=
        e4AdjoinList_cons
          (Geo := Geo)
          X Q L

      by_cases hPprev :
          SmithSpan Geo (E4AdjoinList Geo X L) P

      · rcases
          ih hPprev with
          ⟨R, hLen, hSpan⟩

        refine ⟨Q :: R, ?_, ?_⟩

        · simp only [List.length_cons]
          omega

        · rw [
            e4AdjoinList_cons
              (Geo := Geo)
              (SmithAdjoinPoint Geo X P)
              Q R,
            hCons
          ]

          exact
            e4_span_adjoin_congr
              (Geo := Geo)
              (E4AdjoinList Geo
                (SmithAdjoinPoint Geo X P) R)
              (E4AdjoinList Geo X L)
              Q
              hSpan

      · have hPinLast :
            SmithSpan Geo
              (SmithAdjoinPoint Geo
                (E4AdjoinList Geo X L) Q) P := by
          rw [<- hCons]
          exact hPin

        have hReplace :
            SmithSpan Geo
                (SmithAdjoinPoint Geo
                  (E4AdjoinList Geo X L) P) =
              SmithSpan Geo
                (SmithAdjoinPoint Geo
                  (E4AdjoinList Geo X L) Q) :=
          e4_exchange_replace_one
            (Geo := Geo)
            hExchange
            (E4AdjoinList Geo X L)
            P Q
            hPinLast
            hPprev

        refine ⟨L, ?_, ?_⟩

        · simp

        · rw [
            e4AdjoinList_adjoin_comm
              (Geo := Geo)
              X P L,
            hCons
          ]

          exact hReplace


/--
The empty point carrier is a Smith flat.
-/
def E4EmptyCarrier : Set Geo.Point :=
  fun _ => False


theorem e4EmptyCarrier_flat
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo] :
    SmithFlat Geo (E4EmptyCarrier Geo) := by

  constructor

  · intro A B hA
    exact False.elim hA

  · intro A B C hA
    exact False.elim hA


/--
The Smith span of the empty carrier is empty.
-/
theorem e4Span_empty_eq_empty
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo] :
    SmithSpan Geo (E4EmptyCarrier Geo) =
      E4EmptyCarrier Geo := by

  exact
    smithSpan_eq_self_of_flat
      (Geo := Geo)
      (E4EmptyCarrier Geo)
      (e4EmptyCarrier_flat
        (Geo := Geo))


/--
The four-element list carrier over the empty base is the usual
four-point carrier used for a generated 3-flat.
-/
theorem e4AdjoinList_four_eq_quad
    (A B C D : Geo.Point) :
    E4AdjoinList Geo
        (E4EmptyCarrier Geo)
        [A, B, C, D] =
      SmithAdjoinPoint Geo
        (SmithPointTriple Geo A B C) D := by

  apply Set.ext
  intro P
  constructor

  · intro hP
    change False \/ List.Mem P [A, B, C, D] at hP
    change P = D \/ (P = A \/ P = B \/ P = C)

    rcases hP with hFalse | hMem

    · exact False.elim hFalse

    · rcases List.mem_cons.mp hMem with hPA | hMem
      · exact Or.inr (Or.inl hPA)

      · rcases List.mem_cons.mp hMem with hPB | hMem
        · exact Or.inr (Or.inr (Or.inl hPB))

        · rcases List.mem_cons.mp hMem with hPC | hMem
          · exact Or.inr (Or.inr (Or.inr hPC))

          · have hPD : P = D :=
              List.mem_singleton.mp hMem
            exact Or.inl hPD

  · intro hP
    change P = D \/ (P = A \/ P = B \/ P = C) at hP
    change False \/ List.Mem P [A, B, C, D]
    right

    rcases hP with hPD | hRest

    · exact
        List.mem_cons.mpr
          (Or.inr
            (List.mem_cons.mpr
              (Or.inr
                (List.mem_cons.mpr
                  (Or.inr
                    (List.mem_singleton.mpr hPD))))))

    · rcases hRest with hPA | hRest

      · exact List.mem_cons.mpr (Or.inl hPA)

      · rcases hRest with hPB | hPC
        · exact
            List.mem_cons.mpr
              (Or.inr
                (List.mem_cons.mpr
                  (Or.inl hPB)))
        · exact
            List.mem_cons.mpr
              (Or.inr
                (List.mem_cons.mpr
                  (Or.inr
                    (List.mem_cons.mpr
                      (Or.inl hPC)))))


/--
The accumulated reference base A,B,C,D is the usual four-point carrier.
-/
theorem e4_reference_quad_eq
    (A B C D : Geo.Point) :
    SmithAdjoinPoint Geo
      (SmithAdjoinPoint Geo
        (SmithAdjoinPoint Geo
          (SmithAdjoinPoint Geo
            (E4EmptyCarrier Geo) A) B) C) D =
      SmithAdjoinPoint Geo
        (SmithPointTriple Geo A B C) D := by

  apply Set.ext
  intro P
  change
    (P = D \/ (P = C \/ (P = B \/ (P = A \/ False)))) <->
      (P = D \/ (P = A \/ P = B \/ P = C))
  tauto


/--
The first point of a noncollinear triple is different from the second.
-/
theorem e4_noncollinear_first_ne_second
    [H : HilbertIncidence Geo]
    [HP : HilbertPlaneIncidence Geo]
    (A B C : Geo.Point)
    (hABC : Not (PrimCollinear Geo A B C)) :
    Ne A B := by

  intro hAB
  exact
    hABC
      (primCollinear_of_eq_first_second
        (Geo := Geo)
        A B C hAB)


/--
For a noncollinear triple A,B,C, the point B is outside the span of the
singleton A.
-/
theorem e4_second_outside_first_span
    [H : HilbertIncidence Geo]
    [HP : HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (A B C : Geo.Point)
    (hABC : Not (PrimCollinear Geo A B C)) :
    Not
      (SmithSpan Geo
        (SmithAdjoinPoint Geo (E4EmptyCarrier Geo) A) B) := by

  have hAB : Ne A B :=
    e4_noncollinear_first_ne_second
      (Geo := Geo)
      A B C hABC

  intro hB

  have hBsingle :
      SmithSingletonCarrier Geo A B :=
    hB
      (SmithSingletonCarrier Geo A)
      (smithSingletonCarrier_flat
        (Geo := Geo) A)
      (by
        intro P hP
        rcases hP with hPA | hEmpty

        · exact hPA

        · exact False.elim hEmpty)

  exact hAB hBsingle.symm


/--
For a noncollinear triple A,B,C, the point C is outside the span of A,B.
-/
theorem e4_third_outside_first_two_span
    [H : HilbertIncidence Geo]
    [HP : HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (A B C : Geo.Point)
    (hABC : Not (PrimCollinear Geo A B C)) :
    Not
      (SmithSpan Geo
        (SmithAdjoinPoint Geo
          (SmithAdjoinPoint Geo (E4EmptyCarrier Geo) A) B)
        C) := by

  have hAB : Ne A B :=
    e4_noncollinear_first_ne_second
      (Geo := Geo)
      A B C hABC

  rcases
      HP.line_through
        A B hAB with
    ⟨l, hAl, hBl⟩

  intro hC

  have hCline :
      SmithLineCarrier Geo l C :=
    hC
      (SmithLineCarrier Geo l)
      (smithLineCarrier_flat
        (Geo := Geo) l)
      (by
        intro P hP
        rcases hP with hPB | hRest

        · subst P
          exact hBl

        · rcases hRest with hPA | hEmpty

          · subst P
            exact hAl

          · exact False.elim hEmpty)

  exact
    hABC
      ⟨l, hAl, hBl, hCline⟩


/--
A genuine E4 frame supplies four successive exchange-independent points
A,B,C,D over the empty carrier.
-/
theorem e4_frame_four_step_independence
    [H : HilbertIncidence Geo]
    [HP : HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (A B C D P : Geo.Point)
    (hFrame : E4Frame Geo A B C D P) :
    Not (SmithSpan Geo (E4EmptyCarrier Geo) A) /\
    Not
      (SmithSpan Geo
        (SmithAdjoinPoint Geo (E4EmptyCarrier Geo) A) B) /\
    Not
      (SmithSpan Geo
        (SmithAdjoinPoint Geo
          (SmithAdjoinPoint Geo (E4EmptyCarrier Geo) A) B)
        C) /\
    Not
      (SmithSpan Geo
        (SmithAdjoinPoint Geo
          (SmithAdjoinPoint Geo
            (SmithAdjoinPoint Geo (E4EmptyCarrier Geo) A) B) C)
        D) := by

  rcases hFrame with
    ⟨hABC, hDout, _hPout⟩

  have hAout :
      Not (SmithSpan Geo (E4EmptyCarrier Geo) A) := by
    intro hA
    have hAempty : E4EmptyCarrier Geo A := by
      rw [<- e4Span_empty_eq_empty (Geo := Geo)]
      exact hA
    exact hAempty

  have hBout :=
    e4_second_outside_first_span
      (Geo := Geo)
      A B C hABC

  have hCout :=
    e4_third_outside_first_two_span
      (Geo := Geo)
      A B C hABC

  have hBase3 :
      SmithAdjoinPoint Geo
        (SmithAdjoinPoint Geo
          (SmithAdjoinPoint Geo (E4EmptyCarrier Geo) A) B) C =
        SmithPointTriple Geo A B C := by
    apply Set.ext
    intro Q
    change
      (Q = C \/ (Q = B \/ (Q = A \/ False))) <->
        (Q = A \/ Q = B \/ Q = C)
    tauto

  have hDoutBase :
      Not
        (SmithSpan Geo
          (SmithAdjoinPoint Geo
            (SmithAdjoinPoint Geo
              (SmithAdjoinPoint Geo (E4EmptyCarrier Geo) A) B) C)
          D) := by
    rw [hBase3]
    exact hDout

  exact
    ⟨hAout, hBout, hCout, hDoutBase⟩


/--
Core rank argument.

In a geometry satisfying Salas exchange and the E4 frame-existence lower
bound, the span of any four-point generated 3-flat cannot be the entire
ambient point space.
-/
theorem salas_e4_generated3Flat_proper
    [H : HilbertIncidence Geo]
    [HP : HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [SalasIncidence Geo]
    [D4 : E4Dimension Geo]
    (F : Set Geo.Point)
    (hF : E4Generated3Flat Geo F) :
    Ne F (Set.univ : Set Geo.Point) := by

  rcases hF with
    ⟨A, B, C, D, hABC, hDout, hFdef⟩

  intro hFuniv

  have hExchange :
      SmithSpanExchange Geo :=
    salas_implies_smithSpanExchange
      (Geo := Geo)

  rcases D4.frame_exists with
    ⟨A0, B0, C0, D0, P0, hFrame0⟩

  rcases
      e4_frame_four_step_independence
        (Geo := Geo)
        A0 B0 C0 D0 P0
        hFrame0 with
    ⟨hA0out, hB0out, hC0out, hD0out⟩

  have hP0out :
      Not
        (SmithSpan Geo
          (SmithAdjoinPoint Geo
            (SmithPointTriple Geo A0 B0 C0) D0)
          P0) :=
    hFrame0.2.2

  let L0 : List Geo.Point := [A, B, C, D]

  have hL0set :
      E4AdjoinList Geo (E4EmptyCarrier Geo) L0 =
        SmithAdjoinPoint Geo
          (SmithPointTriple Geo A B C) D := by
    dsimp [L0]
    exact
      e4AdjoinList_four_eq_quad
        (Geo := Geo)
        A B C D

  have hL0univ :
      SmithSpan Geo
          (E4AdjoinList Geo (E4EmptyCarrier Geo) L0) =
        (Set.univ : Set Geo.Point) := by
    rw [hL0set]
    rw [<- hFdef]
    exact hFuniv

  have hA0in :
      SmithSpan Geo
        (E4AdjoinList Geo (E4EmptyCarrier Geo) L0) A0 := by
    rw [hL0univ]
    trivial

  rcases
      e4_exchange_reduce_generator_list
        (Geo := Geo)
        hExchange
        (E4EmptyCarrier Geo)
        L0
        A0
        hA0out
        hA0in with
    ⟨L1, hLen1, hSpan1⟩

  let X1 : Set Geo.Point :=
    SmithAdjoinPoint Geo (E4EmptyCarrier Geo) A0

  have hUniv1 :
      SmithSpan Geo (E4AdjoinList Geo X1 L1) =
        (Set.univ : Set Geo.Point) := by
    dsimp [X1]
    exact hSpan1.trans hL0univ

  have hB0in :
      SmithSpan Geo (E4AdjoinList Geo X1 L1) B0 := by
    rw [hUniv1]
    trivial

  rcases
      e4_exchange_reduce_generator_list
        (Geo := Geo)
        hExchange
        X1
        L1
        B0
        hB0out
        hB0in with
    ⟨L2, hLen2, hSpan2⟩

  let X2 : Set Geo.Point :=
    SmithAdjoinPoint Geo X1 B0

  have hUniv2 :
      SmithSpan Geo (E4AdjoinList Geo X2 L2) =
        (Set.univ : Set Geo.Point) := by
    dsimp [X2]
    exact hSpan2.trans hUniv1

  have hC0in :
      SmithSpan Geo (E4AdjoinList Geo X2 L2) C0 := by
    rw [hUniv2]
    trivial

  rcases
      e4_exchange_reduce_generator_list
        (Geo := Geo)
        hExchange
        X2
        L2
        C0
        hC0out
        hC0in with
    ⟨L3, hLen3, hSpan3⟩

  let X3 : Set Geo.Point :=
    SmithAdjoinPoint Geo X2 C0

  have hUniv3 :
      SmithSpan Geo (E4AdjoinList Geo X3 L3) =
        (Set.univ : Set Geo.Point) := by
    dsimp [X3]
    exact hSpan3.trans hUniv2

  have hD0in :
      SmithSpan Geo (E4AdjoinList Geo X3 L3) D0 := by
    rw [hUniv3]
    trivial

  rcases
      e4_exchange_reduce_generator_list
        (Geo := Geo)
        hExchange
        X3
        L3
        D0
        hD0out
        hD0in with
    ⟨L4, hLen4, hSpan4⟩

  let X4 : Set Geo.Point :=
    SmithAdjoinPoint Geo X3 D0

  have hUniv4 :
      SmithSpan Geo (E4AdjoinList Geo X4 L4) =
        (Set.univ : Set Geo.Point) := by
    dsimp [X4]
    exact hSpan4.trans hUniv3

  have hL4zero : L4.length = 0 := by
    dsimp [L0] at hLen1
    omega

  have hL4nil : L4 = [] := by
    cases L4 with
    | nil => rfl
    | cons Q L =>
        simp only [List.length_cons] at hL4zero
        omega

  have hX4univ :
      SmithSpan Geo X4 =
        (Set.univ : Set Geo.Point) := by
    rw [hL4nil] at hUniv4
    rw [e4AdjoinList_nil (Geo := Geo) X4] at hUniv4
    exact hUniv4

  have hX4quad :
      X4 =
        SmithAdjoinPoint Geo
          (SmithPointTriple Geo A0 B0 C0) D0 := by
    dsimp [X4, X3, X2, X1]
    exact
      e4_reference_quad_eq
        (Geo := Geo)
        A0 B0 C0 D0

  have hP0in :
      SmithSpan Geo
        (SmithAdjoinPoint Geo
          (SmithPointTriple Geo A0 B0 C0) D0)
        P0 := by
    rw [<- hX4quad]
    rw [hX4univ]
    trivial

  exact hP0out hP0in


/--
Every four noncoplanar points determine a proper generated E4 hyperplane.
-/
theorem salas_e4_hyperplane_through_noncoplanar4
    [H : HilbertIncidence Geo]
    [HP : HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [SalasIncidence Geo]
    [E4Dimension Geo]
    (A B C D : Geo.Point)
    (hNoncoplanar :
      Not (HilbertCoplanar4 Geo A B C D)) :
    exists Sigma : E4Hyperplane Geo,
      E4OnHyperplane Geo A Sigma /\
      E4OnHyperplane Geo B Sigma /\
      E4OnHyperplane Geo C Sigma /\
      E4OnHyperplane Geo D Sigma := by

  let F : Set Geo.Point :=
    SmithSpan Geo
      (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D)

  have hGenerated :
      E4Generated3Flat Geo F := by
    dsimp [F]
    exact
      salas_noncoplanar4_generates_3flat
        (Geo := Geo)
        A B C D
        hNoncoplanar

  have hProper :
      Ne F (Set.univ : Set Geo.Point) :=
    salas_e4_generated3Flat_proper
      (Geo := Geo)
      F
      hGenerated

  let Sigma : E4Hyperplane Geo :=
    {
      carrier := F
      generated3Flat := hGenerated
      proper := hProper
    }

  refine ⟨Sigma, ?_, ?_, ?_, ?_⟩

  all_goals
    dsimp [Sigma, E4OnHyperplane, F]
    apply
      smithSpan_extensive
        (Geo := Geo)
        (SmithAdjoinPoint Geo
          (SmithPointTriple Geo A B C) D)

  · exact Or.inr (Or.inl rfl)

  · exact Or.inr (Or.inr (Or.inl rfl))

  · exact Or.inr (Or.inr (Or.inr rfl))

  · exact Or.inl rfl

end Geometry
