import CGJteamLab.E4Dimension

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# Derived E4 hyperplanes

This module replaces the old primitive 4D hyperplane object by a derived
closure-theoretic object.

An E4 hyperplane is a proper generated 3-flat:

* it is generated by four points A,B,C,D with A,B,C noncollinear and
  D outside the span of A,B,C;
* it is not the whole ambient point space.

The dimension-four upper bound then proves that every such hyperplane is
a maximal proper Smith flat.

No new axiom is introduced here.
-/

/--
A derived hyperplane in E4 is a proper generated 3-flat.
-/
structure E4Hyperplane
    (Geo : Geometry.Geo)
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo] where

  carrier :
    Set Geo.Point

  generated3Flat :
    E4Generated3Flat Geo carrier

  proper :
    Ne carrier (Set.univ : Set Geo.Point)


/--
Point membership in a derived E4 hyperplane.
-/
def E4OnHyperplane
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (P : Geo.Point)
    (Sigma : E4Hyperplane Geo) : Prop :=
  Sigma.carrier P


/--
Every derived E4 hyperplane is a Smith flat.
-/
theorem e4Hyperplane_flat
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (Sigma : E4Hyperplane Geo) :
    SmithFlat Geo Sigma.carrier := by

  exact
    e4Generated3Flat_flat
      (Geo := Geo)
      Sigma.carrier
      Sigma.generated3Flat


/--
Every derived E4 hyperplane contains a point.
-/
theorem e4Hyperplane_point_exists
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (Sigma : E4Hyperplane Geo) :
    exists P : Geo.Point,
      E4OnHyperplane Geo P Sigma := by

  rcases Sigma.generated3Flat with
    ⟨A, B, C, D, _hABC, _hDout, hCarrier⟩

  refine ⟨A, ?_⟩

  dsimp [E4OnHyperplane]
  rw [hCarrier]

  apply
    smithSpan_extensive
      (Geo := Geo)
      (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D)

  exact Or.inr (Or.inl rfl)


/--
A line through two distinct points of a derived E4 hyperplane remains
inside the hyperplane.
-/
theorem e4Hyperplane_line_in
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (Sigma : E4Hyperplane Geo)
    (A B : Geo.Point)
    (hASigma : E4OnHyperplane Geo A Sigma)
    (hBSigma : E4OnHyperplane Geo B Sigma)
    (hAB : Ne A B)
    (l : Geo.Line)
    (hAl : H.OnLine A l)
    (hBl : H.OnLine B l) :
    forall X : Geo.Point,
      H.OnLine X l ->
      E4OnHyperplane Geo X Sigma := by

  intro X hXl

  exact
    (e4Hyperplane_flat
      (Geo := Geo)
      Sigma).1
        A B
        hASigma hBSigma
        hAB
        l hAl hBl
        X hXl


/--
A plane through three noncollinear points of a derived E4 hyperplane
remains inside the hyperplane.
-/
theorem e4Hyperplane_plane_in
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (Sigma : E4Hyperplane Geo)
    (A B C : Geo.Point)
    (hASigma : E4OnHyperplane Geo A Sigma)
    (hBSigma : E4OnHyperplane Geo B Sigma)
    (hCSigma : E4OnHyperplane Geo C Sigma)
    (hABC : Not (PrimCollinear Geo A B C))
    (pi : S.Plane)
    (hApi : S.OnPlane A pi)
    (hBpi : S.OnPlane B pi)
    (hCpi : S.OnPlane C pi) :
    forall X : Geo.Point,
      S.OnPlane X pi ->
      E4OnHyperplane Geo X Sigma := by

  intro X hXpi

  exact
    (e4Hyperplane_flat
      (Geo := Geo)
      Sigma).2
        A B C
        hASigma hBSigma hCSigma
        hABC
        pi hApi hBpi hCpi
        X hXpi


/--
A derived E4 hyperplane is maximal among proper Smith flats.

If a Smith flat contains the hyperplane, then it is either the hyperplane
itself or the whole ambient point space.
-/
theorem e4Hyperplane_maximal
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [D4 : E4Dimension Geo]
    (Sigma : E4Hyperplane Geo)
    (F : Set Geo.Point)
    (hFFlat : SmithFlat Geo F)
    (hSigmaF : Set.Subset Sigma.carrier F) :
    F = Sigma.carrier \/
    F = (Set.univ : Set Geo.Point) := by

  by_cases hEq : F = Sigma.carrier

  · exact Or.inl hEq

  · right

    have hOutside :
        exists P : Geo.Point,
          F P /\
          Not (Sigma.carrier P) := by

      by_contra hNoOutside

      have hFSigma :
          Set.Subset F Sigma.carrier := by
        intro P hPF
        by_contra hPoff
        exact
          hNoOutside
            ⟨P, hPF, hPoff⟩

      exact
        hEq
          (Set.Subset.antisymm
            hFSigma
            hSigmaF)

    rcases hOutside with
      ⟨P, hPF, hPoff⟩

    have hAdjoinF :
        Set.Subset
          (SmithAdjoinPoint Geo Sigma.carrier P)
          F := by

      intro X hX
      rcases hX with hXP | hXSigma

      · subst X
        exact hPF

      · exact hSigmaF hXSigma

    have hSpanF :
        Set.Subset
          (SmithSpan Geo
            (SmithAdjoinPoint Geo Sigma.carrier P))
          F :=
      smithSpan_least
        (Geo := Geo)
        (SmithAdjoinPoint Geo Sigma.carrier P)
        F
        hFFlat
        hAdjoinF

    have hAmbient :
        SmithSpan Geo
            (SmithAdjoinPoint Geo Sigma.carrier P) =
          (Set.univ : Set Geo.Point) :=
      D4.generated3Flat_adjoin_external_eq_univ
        Sigma.carrier
        P
        Sigma.generated3Flat
        hPoff

    rw [hAmbient] at hSpanF

    apply Set.Subset.antisymm

    · intro X hXF
      trivial

    · exact hSpanF


/--
Adjoining one external point to a derived E4 hyperplane generates the
whole ambient point space.
-/
theorem e4Hyperplane_adjoin_external_span_eq_univ
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [D4 : E4Dimension Geo]
    (Sigma : E4Hyperplane Geo)
    (P : Geo.Point)
    (hPoff : Not (E4OnHyperplane Geo P Sigma)) :
    SmithSpan Geo
        (SmithAdjoinPoint Geo Sigma.carrier P) =
      (Set.univ : Set Geo.Point) := by

  exact
    D4.generated3Flat_adjoin_external_eq_univ
      Sigma.carrier
      P
      Sigma.generated3Flat
      hPoff


/--
The dimension-four frame axiom guarantees that at least one derived
E4 hyperplane exists.
-/
theorem e4Hyperplane_exists
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [D4 : E4Dimension Geo] :
    Nonempty (E4Hyperplane Geo) := by

  rcases D4.frame_exists with
    ⟨A, B, C, D, P, hABC, hDout, hPout⟩

  let F : Set Geo.Point :=
    SmithSpan Geo
      (SmithAdjoinPoint Geo (SmithPointTriple Geo A B C) D)

  have hGenerated :
      E4Generated3Flat Geo F := by
    exact
      ⟨A, B, C, D,
       hABC,
       hDout,
       rfl⟩

  have hProper :
      Ne F (Set.univ : Set Geo.Point) := by
    intro hFUniv

    have hPF : F P := by
      rw [hFUniv]
      trivial

    exact hPout hPF

  exact
    ⟨{
      carrier := F
      generated3Flat := hGenerated
      proper := hProper
    }⟩

end Geometry
