import CGJteamLab.GeometryCore

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

class HilbertIncidence where
  OnLine :
    Geo.Point → Geo.Line → Prop

def PrimCollinear
    [H : HilbertIncidence Geo]
    (A B C : Geo.Point) : Prop :=
  ∃ l : Geo.Line,
    H.OnLine A l ∧
    H.OnLine B l ∧
    H.OnLine C l

theorem PrimCollinearRotate
    [H : HilbertIncidence Geo]
    (A B C : Geo.Point) :
    PrimCollinear Geo A B C →
    PrimCollinear Geo A C B := by
  intro h
  rcases h with ⟨l, hA, hB, hC⟩
  exact ⟨l, hA, hC, hB⟩

theorem PrimCollinearSwap
    [H : HilbertIncidence Geo]
    (A B C : Geo.Point) :
    PrimCollinear Geo A B C →
    PrimCollinear Geo B A C := by
  intro h
  rcases h with ⟨l, hA, hB, hC⟩
  exact ⟨l, hB, hA, hC⟩

theorem PrimCollinearCycle
    [H : HilbertIncidence Geo]
    (A B C : Geo.Point) :
    PrimCollinear Geo A B C →
    PrimCollinear Geo B C A := by
  intro h
  rcases h with ⟨l, hA, hB, hC⟩
  exact ⟨l, hB, hC, hA⟩


theorem PrimCollinear.mk
    [H : HilbertIncidence Geo]
    {A B C : Geo.Point}
    {l : Geo.Line}
    (hA : H.OnLine A l)
    (hB : H.OnLine B l)
    (hC : H.OnLine C l) :
    PrimCollinear Geo A B C :=
by
  exact ⟨l, hA, hB, hC⟩
theorem PrimCollinear.exists_line
    [H : HilbertIncidence Geo]
    {A B C : Geo.Point}
    (h : PrimCollinear Geo A B C) :
    ∃ l : Geo.Line,
      H.OnLine A l ∧
      H.OnLine B l ∧
      H.OnLine C l :=
by
  simpa [PrimCollinear] using h

theorem PrimCollinearSymm
    [H : HilbertIncidence Geo]
    (A B C : Geo.Point) :
    PrimCollinear Geo A B C →
    PrimCollinear Geo C B A := by
  intro h
  rcases h with ⟨l, hA, hB, hC⟩
  exact ⟨l, hC, hB, hA⟩

/-!
# Hilbert's plane axiom hierarchy

The following classes formalize the plane part of the five axiom groups
from the second English edition of Hilbert's *Foundations of Geometry*.
They preserve the small `HilbertIncidence` interface used by the existing
library and add stronger layers without changing `GeometryCore`.
The field documentation retains Hilbert's original group numbering.

The present `Geometry.Geo` has points and lines but no type of planes.
Consequently, the space incidence axioms I, 4-8 are intentionally not
encoded here. Axiom V, 2 is also deferred: Hilbert's line-completeness
axiom is a maximality statement about extensions of an entire ordered
congruence structure and requires a separate model-theoretic interface.
-/

/-- Two Hilbert lines meet when they have a common point. -/
def HilbertLinesMeet
    [H : HilbertIncidence Geo]
    (l m : Geo.Line) : Prop :=
  ∃ P : Geo.Point, H.OnLine P l ∧ H.OnLine P m

/-- Two Hilbert lines are disjoint when they have no common point. -/
def HilbertLinesDisjoint
    [HilbertIncidence Geo]
    (l m : Geo.Line) : Prop :=
  ¬ HilbertLinesMeet Geo l m

/--
`P` and `Q` lie on the same ray from `O`. Betweenness is the primitive
relation inherited from `GeometryCore`.
-/
def HilbertSameRay
    [HilbertIncidence Geo]
    (O P Q : Geo.Point) : Prop :=
  P ≠ O ∧
  Q ≠ O ∧
  PrimCollinear Geo O P Q ∧
  ¬ Geo.Between P O Q

/-- The open segment `AB` meets the line `l`. -/
def HilbertSegmentMeetsLine
    [H : HilbertIncidence Geo]
    (A B : Geo.Point)
    (l : Geo.Line) : Prop :=
  ∃ X : Geo.Point, Geo.Between A X B ∧ H.OnLine X l

/--
One elementary connection between two points avoiding a line.
-/
def HilbertSameSideStep
    [H : HilbertIncidence Geo]
    (P Q : Geo.Point)
    (l : Geo.Line) : Prop :=
  ¬ H.OnLine P l ∧
  ¬ H.OnLine Q l ∧
  ¬ HilbertSegmentMeetsLine Geo P Q l

/--
Two points are on the same side of a line when they belong to the same
region of its complement. A region is represented by the finite
connectivity generated by segments that avoid the line.
-/
def HilbertSameSide
    [H : HilbertIncidence Geo]
    (P Q : Geo.Point)
    (l : Geo.Line) : Prop :=
  ¬ H.OnLine P l ∧
  ¬ H.OnLine Q l ∧
  Relation.ReflTransGen
    (fun X Y => HilbertSameSideStep Geo X Y l) P Q

/--
Group I, axioms I, 1-3 for plane incidence.

The distinctness assumptions make explicit Hilbert's convention that
letters denoting two or more points or lines denote distinct objects.
-/
class HilbertPlaneIncidence (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop where
  /-- I, 1: two distinct points lie on a line. -/
  line_through :
    ∀ A B : Geo.Point,
      A ≠ B →
      ∃ l : Geo.Line,
        HilbertIncidence.OnLine A l ∧
        HilbertIncidence.OnLine B l

  /-- I, 2: two distinct points determine at most one line. -/
  line_unique :
    ∀ A B : Geo.Point,
      A ≠ B →
      ∀ l m : Geo.Line,
        HilbertIncidence.OnLine A l →
        HilbertIncidence.OnLine B l →
        HilbertIncidence.OnLine A m →
        HilbertIncidence.OnLine B m →
        l = m

  /-- First clause of I, 3: two distinct points exist on a line. -/
  two_points_on_line :
    ∃ l : Geo.Line,
      ∃ A B : Geo.Point,
        A ≠ B ∧
        HilbertIncidence.OnLine A l ∧
        HilbertIncidence.OnLine B l

  /-- Second clause of I, 3: three noncollinear points exist. -/
  three_noncollinear :
    ∃ A B C : Geo.Point,
      ¬ PrimCollinear Geo A B C

/-- Group II, axioms II, 1-4 of order. -/
class HilbertOrder (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop
    extends HilbertPlaneIncidence Geo where
  /--
  II, 1: betweenness implies three distinct collinear points and is
  symmetric in the endpoints.
  -/
  between_incidence :
    ∀ A B C : Geo.Point,
      Geo.Between A B C →
      A ≠ B ∧
      B ≠ C ∧
      A ≠ C ∧
      PrimCollinear Geo A B C ∧
      Geo.Between C B A

  /-- II, 2: a segment can be extended beyond either endpoint. -/
  between_extension :
    ∀ A C : Geo.Point,
      A ≠ C →
      ∃ B : Geo.Point,
        Geo.Between A C B

  /--
  II, 3: among three collinear points, no more than one lies between
  the other two.
  -/
  between_unique :
    ∀ A B C : Geo.Point,
      PrimCollinear Geo A B C →
      Geo.Between A B C →
      ¬ Geo.Between B A C ∧
      ¬ Geo.Between A C B

  /--
  II, 4: Pasch's plane axiom. A line entering a triangle through one
  side leaves it through one of the other two sides.
  -/
  pasch :
    ∀ A B C : Geo.Point,
      ¬ PrimCollinear Geo A B C →
      ∀ l : Geo.Line,
        ¬ HilbertIncidence.OnLine A l →
        ¬ HilbertIncidence.OnLine B l →
        ¬ HilbertIncidence.OnLine C l →
        HilbertSegmentMeetsLine Geo A B l →
        HilbertSegmentMeetsLine Geo A C l ∨
        HilbertSegmentMeetsLine Geo B C l

/-- Group III, axioms III, 1-5 of congruence. -/
class HilbertCongruence (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop
    extends HilbertOrder Geo where
  /-- III, 1: a segment can be laid off on a prescribed ray. -/
  segment_construction :
    ∀ A B O R : Geo.Point,
      O ≠ R →
      ∃ X : Geo.Point,
        HilbertSameRay Geo O R X ∧
        Geo.Congruent O X A B

  /--
  III, 2: two segments congruent to the same segment are congruent to
  each other.
  -/
  segment_congruence_common :
    ∀ A B A' B' A'' B'' : Geo.Point,
      Geo.Congruent A B A' B' →
      Geo.Congruent A B A'' B'' →
      Geo.Congruent A' B' A'' B''

  /-- III, 3: additivity of adjacent congruent segments. -/
  segment_additivity :
    ∀ A B C A' B' C' : Geo.Point,
      Geo.Between A B C →
      Geo.Between A' B' C' →
      Geo.Congruent A B A' B' →
      Geo.Congruent B C B' C' →
      Geo.Congruent A C A' C'

  /--
  III, 4: an angle can be constructed uniquely on a prescribed side
  of a prescribed ray. Uniqueness is uniqueness of the resulting ray.
  -/
  angle_construction :
    ∀ A B C A' B' S : Geo.Point,
      ¬ PrimCollinear Geo A B C →
      A' ≠ B' →
      ∀ l : Geo.Line,
        HilbertIncidence.OnLine A' l →
        HilbertIncidence.OnLine B' l →
        ¬ HilbertIncidence.OnLine S l →
        ∃ C' : Geo.Point,
          HilbertSameSide Geo C' S l ∧
          Geo.AngleCongruent A B C A' B' C' ∧
          ∀ D' : Geo.Point,
            HilbertSameSide Geo D' S l →
            Geo.AngleCongruent A B C A' B' D' →
            HilbertSameRay Geo B' C' D'

  /--
  The reflexivity clause stated with III, 4: every (nondegenerate)
  angle is congruent to itself.
  -/
  angle_congruence_reflexive :
    ∀ A B C : Geo.Point,
      ¬ PrimCollinear Geo A B C →
      Geo.AngleCongruent A B C A B C

  /--
  III, 5: Hilbert's SAS axiom, stated in its original angle-conclusion
  form.
  -/
  sas :
    ∀ A B C A' B' C' : Geo.Point,
      ¬ PrimCollinear Geo A B C →
      ¬ PrimCollinear Geo A' B' C' →
      Geo.Congruent A B A' B' →
      Geo.Congruent A C A' C' →
      Geo.AngleCongruent B A C B' A' C' →
      Geo.AngleCongruent A B C A' B' C'

theorem hilbert_primCollinear_trans
    [HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    (A B C D : Geo.Point)
    (hBC : B ≠ C) :
    PrimCollinear Geo A B C →
    PrimCollinear Geo B C D →
    PrimCollinear Geo A B D := by
  intro hABC hBCD
  rcases hABC with ⟨l, hAl, hBl, hCl⟩
  rcases hBCD with ⟨m, hBm, hCm, hDm⟩
  have hlm : l = m :=
    HilbertPlaneIncidence.line_unique
      B C hBC l m hBl hCl hBm hCm
  subst m
  exact ⟨l, hAl, hBl, hDm⟩

theorem hilbert_point_off_line
    [HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    (l : Geo.Line) :
    ∃ P : Geo.Point, ¬ HilbertIncidence.OnLine P l := by
  rcases HilbertPlaneIncidence.three_noncollinear (Geo := Geo) with
    ⟨A, B, C, hABC⟩
  by_cases hA : HilbertIncidence.OnLine A l
  · by_cases hB : HilbertIncidence.OnLine B l
    · by_cases hC : HilbertIncidence.OnLine C l
      · exact False.elim (hABC ⟨l, hA, hB, hC⟩)
      · exact ⟨C, hC⟩
    · exact ⟨B, hB⟩
  · exact ⟨A, hA⟩

theorem hilbert_line_through_point
    [HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    (P : Geo.Point) :
    ∃ l : Geo.Line, HilbertIncidence.OnLine P l := by
  rcases HilbertPlaneIncidence.two_points_on_line (Geo := Geo) with
    ⟨l, A, B, hAB, hAl, hBl⟩
  by_cases hPA : P = A
  · subst P
    exact ⟨l, hAl⟩
  · rcases HilbertPlaneIncidence.line_through P A hPA with
      ⟨m, hPm, _⟩
    exact ⟨m, hPm⟩

theorem hilbert_noncollinear_ne_first
    [HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    (A B C : Geo.Point)
    (hABC : ¬ PrimCollinear Geo A B C) :
    A ≠ B := by
  intro h
  subst B
  by_cases hAC : A = C
  · subst C
    rcases hilbert_line_through_point Geo A with ⟨l, hAl⟩
    exact hABC ⟨l, hAl, hAl, hAl⟩
  · rcases HilbertPlaneIncidence.line_through A C hAC with
      ⟨l, hAl, hCl⟩
    exact hABC ⟨l, hAl, hAl, hCl⟩

theorem hilbert_not_collinear_of_off_line
    [HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    (A B P : Geo.Point)
    (l : Geo.Line)
    (hAB : A ≠ B)
    (hAl : HilbertIncidence.OnLine A l)
    (hBl : HilbertIncidence.OnLine B l)
    (hPl : ¬ HilbertIncidence.OnLine P l) :
    ¬ PrimCollinear Geo A B P := by
  rintro ⟨m, hAm, hBm, hPm⟩
  have hlm : l = m :=
    HilbertPlaneIncidence.line_unique
      A B hAB l m hAl hBl hAm hBm
  subst m
  exact hPl hPm

theorem hilbert_between_on_line
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B C : Geo.Point)
    (l : Geo.Line)
    (hAl : HilbertIncidence.OnLine A l)
    (hCl : HilbertIncidence.OnLine C l)
    (hABC : Geo.Between A B C) :
    HilbertIncidence.OnLine B l := by
  have hData := HilbertOrder.between_incidence A B C hABC
  rcases hData.2.2.2.1 with ⟨m, hAm, hBm, hCm⟩
  have hlm : l = m :=
    HilbertPlaneIncidence.line_unique
      A C hData.2.2.1 l m hAl hCl hAm hCm
  subst m
  exact hBm

theorem hilbert_collinear_on_line
    [HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    (A B C : Geo.Point)
    (l : Geo.Line)
    (hAB : A ≠ B)
    (hAl : HilbertIncidence.OnLine A l)
    (hBl : HilbertIncidence.OnLine B l)
    (hABC : PrimCollinear Geo A B C) :
    HilbertIncidence.OnLine C l := by
  rcases hABC with ⟨m, hAm, hBm, hCm⟩
  have hlm : l = m :=
    HilbertPlaneIncidence.line_unique
      A B hAB l m hAl hBl hAm hBm
  subst m
  exact hCm

/--
Hilbert's Theorem 3: between two distinct points of a line there is a
point. The proof is the construction from the second edition and uses
Pasch's axiom II.4.
-/
theorem hilbert_between_exists
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A C : Geo.Point)
    (hAC : A ≠ C) :
    ∃ D : Geo.Point, Geo.Between A D C := by
  rcases HilbertPlaneIncidence.line_through A C hAC with
    ⟨l, hAl, hCl⟩
  rcases hilbert_point_off_line Geo l with ⟨E, hEl⟩
  have hAE : A ≠ E := by
    intro h
    subst E
    exact hEl hAl
  rcases HilbertPlaneIncidence.line_through A E hAE with
    ⟨k, hAk, hEk⟩
  rcases HilbertOrder.between_extension A E hAE with
    ⟨F, hAEF⟩
  have hAEFData := HilbertOrder.between_incidence A E F hAEF
  have hFk : HilbertIncidence.OnLine F k :=
    hilbert_collinear_on_line
      Geo A E F k hAE hAk hEk hAEFData.2.2.2.1
  have hFl : ¬ HilbertIncidence.OnLine F l := by
    intro hFl
    have hlk : l = k :=
      HilbertPlaneIncidence.line_unique
        A F hAEFData.2.2.1 l k hAl hFl hAk hFk
    subst k
    exact hEl hEk
  have hFC : F ≠ C := by
    intro h
    subst F
    exact hFl hCl
  rcases HilbertPlaneIncidence.line_through F C hFC with
    ⟨n, hFn, hCn⟩
  rcases HilbertOrder.between_extension F C hFC with
    ⟨G, hFCG⟩
  have hFCGData := HilbertOrder.between_incidence F C G hFCG
  have hGn : HilbertIncidence.OnLine G n :=
    hilbert_collinear_on_line
      Geo F C G n hFC hFn hCn hFCGData.2.2.2.1
  have hEn : ¬ HilbertIncidence.OnLine E n := by
    intro hEn
    have hnk : n = k :=
      HilbertPlaneIncidence.line_unique
        E F hAEFData.2.1 n k hEn hFn hEk hFk
    have hAn : HilbertIncidence.OnLine A n := by
      rw [hnk]
      exact hAk
    have hln : l = n :=
      HilbertPlaneIncidence.line_unique
        A C hAC l n hAl hCl hAn hCn
    rw [← hln] at hEn
    exact hEl hEn
  have hEG : E ≠ G := by
    intro h
    subst G
    exact hEn hGn
  rcases HilbertPlaneIncidence.line_through E G hEG with
    ⟨m, hEm, hGm⟩
  have hACF : ¬ PrimCollinear Geo A C F :=
    hilbert_not_collinear_of_off_line
      Geo A C F l hAC hAl hCl hFl
  have hAFC : ¬ PrimCollinear Geo A F C :=
    fun h => hACF (PrimCollinearRotate Geo A F C h)
  have hAm : ¬ HilbertIncidence.OnLine A m := by
    intro hAm
    have hmk : m = k :=
      HilbertPlaneIncidence.line_unique
        A E hAE m k hAm hEm hAk hEk
    have hGk : HilbertIncidence.OnLine G k := by
      rw [← hmk]
      exact hGm
    have hnk : n = k :=
      HilbertPlaneIncidence.line_unique
        F G hFCGData.2.2.1 n k hFn hGn hFk hGk
    have hCk : HilbertIncidence.OnLine C k := by
      rw [← hnk]
      exact hCn
    have hlk : l = k :=
      HilbertPlaneIncidence.line_unique
        A C hAC l k hAl hCl hAk hCk
    rw [← hlk] at hEk
    exact hEl hEk
  have hFm : ¬ HilbertIncidence.OnLine F m := by
    intro hFm
    have hmk : m = k :=
      HilbertPlaneIncidence.line_unique
        E F hAEFData.2.1 m k hEm hFm hEk hFk
    have hGk : HilbertIncidence.OnLine G k := by
      rw [← hmk]
      exact hGm
    have hnk : n = k :=
      HilbertPlaneIncidence.line_unique
        F G hFCGData.2.2.1 n k hFn hGn hFk hGk
    have hCk : HilbertIncidence.OnLine C k := by
      rw [← hnk]
      exact hCn
    have hlk : l = k :=
      HilbertPlaneIncidence.line_unique
        A C hAC l k hAl hCl hAk hCk
    rw [← hlk] at hEk
    exact hEl hEk
  have hCm : ¬ HilbertIncidence.OnLine C m := by
    intro hCm
    have hmn : m = n :=
      HilbertPlaneIncidence.line_unique
        C G hFCGData.2.1 m n hCm hGm hCn hGn
    have hEn' : HilbertIncidence.OnLine E n := by
      rw [← hmn]
      exact hEm
    exact hEn hEn'
  have hMeetsAF : HilbertSegmentMeetsLine Geo A F m :=
    ⟨E, hAEF, hEm⟩
  rcases HilbertOrder.pasch
      (Geo := Geo) A F C hAFC m hAm hFm hCm hMeetsAF with
    hMeetsAC | hMeetsFC
  · exact hMeetsAC.elim fun D hD => ⟨D, hD.1⟩
  · rcases hMeetsFC with ⟨X, hFXC, hXm⟩
    have hXn : HilbertIncidence.OnLine X n :=
      hilbert_between_on_line Geo F X C n hFn hCn hFXC
    have hXG : X ≠ G := by
      intro h
      subst X
      have hNotFGC :=
        (HilbertOrder.between_unique
          (Geo := Geo) F C G hFCGData.2.2.2.1 hFCG).2
      exact hNotFGC hFXC
    have hmn : m = n :=
      HilbertPlaneIncidence.line_unique
        X G hXG m n hXm hGm hXn hGn
    have hEn' : HilbertIncidence.OnLine E n := by
      rw [← hmn]
      exact hEm
    exact False.elim (hEn hEn')

theorem hilbert_pasch_forced
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B C : Geo.Point)
    (l : Geo.Line)
    (hABC : ¬ PrimCollinear Geo A B C)
    (hAl : ¬ HilbertIncidence.OnLine A l)
    (hBl : ¬ HilbertIncidence.OnLine B l)
    (hCl : ¬ HilbertIncidence.OnLine C l)
    (hMeetsAB : HilbertSegmentMeetsLine Geo A B l)
    (hNotMeetsBC : ¬ HilbertSegmentMeetsLine Geo B C l) :
    HilbertSegmentMeetsLine Geo A C l := by
  rcases HilbertOrder.pasch
      (Geo := Geo) A B C hABC l hAl hBl hCl hMeetsAB with
    hMeetsAC | hMeetsBC
  · exact hMeetsAC
  · exact False.elim (hNotMeetsBC hMeetsBC)

theorem hilbert_common_point_unique
    [HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    (l m : Geo.Line)
    (hLM : l ≠ m)
    (P X : Geo.Point)
    (hPl : HilbertIncidence.OnLine P l)
    (hPm : HilbertIncidence.OnLine P m)
    (hXl : HilbertIncidence.OnLine X l)
    (hXm : HilbertIncidence.OnLine X m) :
    X = P := by
  by_contra hXP
  have hlm : l = m :=
    HilbertPlaneIncidence.line_unique
      P X (fun h => hXP h.symm) l m hPl hXl hPm hXm
  exact hLM hlm

theorem hilbert_segment_not_meets_crossing_line
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B P : Geo.Point)
    (base cross : Geo.Line)
    (hLines : base ≠ cross)
    (hAbase : HilbertIncidence.OnLine A base)
    (hBbase : HilbertIncidence.OnLine B base)
    (hPbase : HilbertIncidence.OnLine P base)
    (hPcross : HilbertIncidence.OnLine P cross)
    (hNotBetween : ¬ Geo.Between A P B) :
    ¬ HilbertSegmentMeetsLine Geo A B cross := by
  rintro ⟨X, hAXB, hXcross⟩
  have hXbase :=
    hilbert_between_on_line Geo A X B base hAbase hBbase hAXB
  have hXP :=
    hilbert_common_point_unique
      Geo base cross hLines P X
      hPbase hPcross hXbase hXcross
  subst X
  exact hNotBetween hAXB

/--
Hilbert's Theorem 4: of three distinct collinear points, one lies
between the other two. Together with II.3 this gives uniqueness.
-/
theorem hilbert_between_trichotomy
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B C : Geo.Point)
    (hAB : A ≠ B)
    (hBC : B ≠ C)
    (hAC : A ≠ C)
    (hABC : PrimCollinear Geo A B C) :
    Geo.Between A B C ∨
    Geo.Between B A C ∨
    Geo.Between A C B := by
  by_cases hB : Geo.Between A B C
  · exact Or.inl hB
  by_cases hA : Geo.Between B A C
  · exact Or.inr (Or.inl hA)
  by_contra hAll
  have hC : ¬ Geo.Between A C B :=
    fun h => hAll (Or.inr (Or.inr h))
  rcases hABC with ⟨q, hAq, hBq, hCq⟩
  rcases hilbert_point_off_line Geo q with ⟨D, hDq⟩
  have hBD : B ≠ D := by
    intro h
    subst D
    exact hDq hBq
  rcases HilbertPlaneIncidence.line_through B D hBD with
    ⟨r, hBr, hDr⟩
  rcases HilbertOrder.between_extension B D hBD with
    ⟨G, hBDG⟩
  have hBDGData := HilbertOrder.between_incidence B D G hBDG
  have hGr : HilbertIncidence.OnLine G r :=
    hilbert_collinear_on_line
      Geo B D G r hBD hBr hDr hBDGData.2.2.2.1
  have hGq : ¬ HilbertIncidence.OnLine G q := by
    intro hGq
    have hqr : q = r :=
      HilbertPlaneIncidence.line_unique
        B G hBDGData.2.2.1 q r hBq hGq hBr hGr
    rw [← hqr] at hDr
    exact hDq hDr
  have hAD : A ≠ D := by
    intro h
    subst D
    exact hDq hAq
  rcases HilbertPlaneIncidence.line_through A D hAD with
    ⟨s, hAs, hDs⟩
  have hQS : q ≠ s := by
    intro h
    subst s
    exact hDq hDs
  have hBCG : ¬ PrimCollinear Geo B C G :=
    hilbert_not_collinear_of_off_line
      Geo B C G q hBC hBq hCq hGq
  have hBs : ¬ HilbertIncidence.OnLine B s := by
    intro hBs
    have hqs : q = s :=
      HilbertPlaneIncidence.line_unique
        A B hAB q s hAq hBq hAs hBs
    exact hQS hqs
  have hCs : ¬ HilbertIncidence.OnLine C s := by
    intro hCs
    have hqs : q = s :=
      HilbertPlaneIncidence.line_unique
        A C hAC q s hAq hCq hAs hCs
    exact hQS hqs
  have hGs : ¬ HilbertIncidence.OnLine G s := by
    intro hGs
    have hsr : s = r :=
      HilbertPlaneIncidence.line_unique
        D G hBDGData.2.1 s r hDs hGs hDr hGr
    have hAr : HilbertIncidence.OnLine A r := by
      rw [← hsr]
      exact hAs
    have hqr : q = r :=
      HilbertPlaneIncidence.line_unique
        A B hAB q r hAq hBq hAr hBr
    rw [← hqr] at hDr
    exact hDq hDr
  have hMeetsBG : HilbertSegmentMeetsLine Geo B G s :=
    ⟨D, hBDG, hDs⟩
  have hNotMeetsBC : ¬ HilbertSegmentMeetsLine Geo B C s :=
    hilbert_segment_not_meets_crossing_line
      Geo B C A q s hQS hBq hCq hAq hAs hA
  have hMeetsCG : HilbertSegmentMeetsLine Geo C G s := by
    rcases HilbertOrder.pasch
        (Geo := Geo) B G C
        (fun h => hBCG (PrimCollinearRotate Geo B G C h))
        s hBs hGs hCs hMeetsBG with
      hMeetsBC | hMeetsGC
    · exact False.elim (hNotMeetsBC hMeetsBC)
    · rcases hMeetsGC with ⟨X, hGXC, hXs⟩
      exact
        ⟨X,
          (HilbertOrder.between_incidence G X C hGXC).2.2.2.2,
          hXs⟩
  rcases hMeetsCG with ⟨E, hCEG, hEs⟩
  have hCD : C ≠ D := by
    intro h
    subst D
    exact hDq hCq
  rcases HilbertPlaneIncidence.line_through C D hCD with
    ⟨t, hCt, hDt⟩
  have hQT : q ≠ t := by
    intro h
    subst t
    exact hDq hDt
  have hBGA : ¬ PrimCollinear Geo B G A := by
    have hABG : ¬ PrimCollinear Geo A B G :=
      hilbert_not_collinear_of_off_line
        Geo A B G q hAB hAq hBq hGq
    intro h
    exact hABG (PrimCollinearCycle Geo G A B (PrimCollinearCycle Geo B G A h))
  have hBt : ¬ HilbertIncidence.OnLine B t := by
    intro hBt
    have hqt : q = t :=
      HilbertPlaneIncidence.line_unique
        B C hBC q t hBq hCq hBt hCt
    exact hQT hqt
  have hGt : ¬ HilbertIncidence.OnLine G t := by
    intro hGt
    have htr : t = r :=
      HilbertPlaneIncidence.line_unique
        D G hBDGData.2.1 t r hDt hGt hDr hGr
    have hCr : HilbertIncidence.OnLine C r := by
      rw [← htr]
      exact hCt
    have hqr : q = r :=
      HilbertPlaneIncidence.line_unique
        B C hBC q r hBq hCq hBr hCr
    rw [← hqr] at hDr
    exact hDq hDr
  have hAt : ¬ HilbertIncidence.OnLine A t := by
    intro hAt
    have hqt : q = t :=
      HilbertPlaneIncidence.line_unique
        A C hAC q t hAq hCq hAt hCt
    exact hQT hqt
  have hNotMeetsBA : ¬ HilbertSegmentMeetsLine Geo B A t :=
    hilbert_segment_not_meets_crossing_line
      Geo B A C q t hQT hBq hAq hCq hCt
        (fun hBCA =>
          hC (HilbertOrder.between_incidence B C A hBCA).2.2.2.2)
  have hMeetsBG' : HilbertSegmentMeetsLine Geo B G t :=
    ⟨D, hBDG, hDt⟩
  have hMeetsGA : HilbertSegmentMeetsLine Geo G A t := by
    rcases HilbertOrder.pasch
        (Geo := Geo) B G A hBGA t hBt hGt hAt hMeetsBG' with
      hMeetsBA | hMeetsGA
    · exact False.elim (hNotMeetsBA hMeetsBA)
    · exact hMeetsGA
  rcases hMeetsGA with ⟨F, hGFA, hFt⟩
  have hAFG : Geo.Between A F G :=
    (HilbertOrder.between_incidence G F A hGFA).2.2.2.2
  have hCEGData := HilbertOrder.between_incidence C E G hCEG
  rcases hCEGData.2.2.2.1 with ⟨v, hCv, hEv, hGv⟩
  have hAENe : A ≠ E := by
    intro h
    subst E
    have hqv : q = v :=
      HilbertPlaneIncidence.line_unique
        A C hAC q v hAq hCq hEv hCv
    rw [← hqv] at hGv
    exact hGq hGv
  have hAEG : ¬ PrimCollinear Geo A E G :=
    hilbert_not_collinear_of_off_line
      Geo A E G s hAENe hAs hEs hGs
  have hST : s ≠ t := by
    intro h
    subst t
    exact hAt hAs
  have hDEn : D ≠ E := by
    intro h
    subst E
    have hDrv : HilbertIncidence.OnLine D v := hEv
    have hrv : r = v :=
      HilbertPlaneIncidence.line_unique
        D G hBDGData.2.1 r v hDr hGr hDrv hGv
    have hCr : HilbertIncidence.OnLine C r := by
      rw [hrv]
      exact hCv
    have hqr : q = r :=
      HilbertPlaneIncidence.line_unique
        B C hBC q r hBq hCq hBr hCr
    rw [← hqr] at hDr
    exact hDq hDr
  have hEt : ¬ HilbertIncidence.OnLine E t := by
    intro hEt
    have hED :=
      hilbert_common_point_unique
        Geo s t hST D E hDs hDt hEs hEt
    exact hDEn hED.symm
  have hVT : v ≠ t := by
    intro h
    subst t
    exact hGt hGv
  have hNotGCE : ¬ Geo.Between G C E := by
    intro hGCE
    have hECG :
        Geo.Between E C G :=
      (HilbertOrder.between_incidence G C E hGCE).2.2.2.2
    exact
      (HilbertOrder.between_unique
        (Geo := Geo) C E G
        ⟨v, hCv, hEv, hGv⟩ hCEG).1 hECG
  have hNotMeetsGE : ¬ HilbertSegmentMeetsLine Geo G E t :=
    hilbert_segment_not_meets_crossing_line
      Geo G E C v t hVT hGv hEv hCv hCt hNotGCE
  have hMeetsAGt : HilbertSegmentMeetsLine Geo A G t :=
    ⟨F, hAFG, hFt⟩
  have hMeetsAE : HilbertSegmentMeetsLine Geo A E t :=
    hilbert_pasch_forced
      Geo A G E t
      (fun h => hAEG (PrimCollinearRotate Geo A G E h))
      hAt hGt hEt hMeetsAGt hNotMeetsGE
  rcases hMeetsAE with ⟨X, hAXE, hXt⟩
  have hXD :=
    hilbert_common_point_unique
      Geo s t hST D X hDs hDt
      (hilbert_between_on_line Geo A X E s hAs hEs hAXE) hXt
  subst X
  have hADE : Geo.Between A D E := hAXE
  have hQR : q ≠ r := by
    intro h
    subst r
    exact hDq hDr
  have hAr : ¬ HilbertIncidence.OnLine A r := by
    intro hAr
    have hqr : q = r :=
      HilbertPlaneIncidence.line_unique
        A B hAB q r hAq hBq hAr hBr
    exact hQR hqr
  have hCr : ¬ HilbertIncidence.OnLine C r := by
    intro hCr
    have hqr : q = r :=
      HilbertPlaneIncidence.line_unique
        B C hBC q r hBq hCq hBr hCr
    exact hQR hqr
  have hEr : ¬ HilbertIncidence.OnLine E r := by
    intro hEr
    have hED :=
      hilbert_common_point_unique
        Geo s r
        (fun hsr => by
          have hAr' : HilbertIncidence.OnLine A r := by
            rw [← hsr]
            exact hAs
          exact hAr hAr')
        D E hDs hDr hEs hEr
    exact hDEn hED.symm
  have hAEC : ¬ PrimCollinear Geo A E C :=
    hilbert_not_collinear_of_off_line
      Geo A E C s hAENe hAs hEs hCs
  have hVR : v ≠ r := by
    intro h
    subst r
    exact hCr hCv
  have hNotGEC : ¬ Geo.Between E G C :=
    fun hEGC =>
      (HilbertOrder.between_unique
        (Geo := Geo) C E G
        ⟨v, hCv, hEv, hGv⟩ hCEG).2
        ((HilbertOrder.between_incidence E G C hEGC).2.2.2.2)
  have hNotMeetsEC : ¬ HilbertSegmentMeetsLine Geo E C r :=
    hilbert_segment_not_meets_crossing_line
      Geo E C G v r hVR hEv hCv hGv hGr hNotGEC
  have hMeetsAEr : HilbertSegmentMeetsLine Geo A E r :=
    ⟨D, hADE, hDr⟩
  have hMeetsAC : HilbertSegmentMeetsLine Geo A C r :=
    hilbert_pasch_forced
      Geo A E C r hAEC hAr hEr hCr hMeetsAEr hNotMeetsEC
  rcases hMeetsAC with ⟨Y, hAYC, hYr⟩
  have hYq :=
    hilbert_between_on_line Geo A Y C q hAq hCq hAYC
  have hYB :=
    hilbert_common_point_unique
      Geo q r hQR B Y hBq hBr hYq hYr
  subst Y
  exact hB hAYC

/--
The strengthened inner form of Pasch used in Hilbert's proof of
Theorem 5.  It is a theorem of I.1--I.2 and II.1--II.4, not an
additional order axiom.

If `C` is between `B` and `D`, and `E` is between `A` and `B`,
then the transversal through `D` and `E` cuts `AC` at a point `F`;
moreover `F` is between `D` and `E`.
-/
theorem hilbert_inner_pasch_strong
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B C D E : Geo.Point)
    (hABC : ¬ PrimCollinear Geo A B C)
    (hBCD : Geo.Between B C D)
    (hAEB : Geo.Between A E B) :
    ∃ F : Geo.Point,
      Geo.Between D F E ∧
      Geo.Between A F C := by
  have hBCDData := HilbertOrder.between_incidence B C D hBCD
  have hAEBData := HilbertOrder.between_incidence A E B hAEB
  have hBC : B ≠ C := hBCDData.1
  have hCD : C ≠ D := hBCDData.2.1
  have hBD : B ≠ D := hBCDData.2.2.1
  have hAE : A ≠ E := hAEBData.1
  have hEB : E ≠ B := hAEBData.2.1
  have hAB : A ≠ B := hAEBData.2.2.1
  have hAC : A ≠ C :=
    hilbert_noncollinear_ne_first
      Geo A C B
      (fun h => hABC (PrimCollinearRotate Geo A C B h))
  rcases HilbertPlaneIncidence.line_through B C hBC with
    ⟨g, hBg, hCg⟩
  have hDg : HilbertIncidence.OnLine D g :=
    hilbert_collinear_on_line
      Geo B C D g hBC hBg hCg hBCDData.2.2.2.1
  rcases HilbertPlaneIncidence.line_through A B hAB with
    ⟨m, hAm, hBm⟩
  have hEm : HilbertIncidence.OnLine E m :=
    hilbert_between_on_line Geo A E B m hAm hBm hAEB
  have hgm : g ≠ m := by
    intro h
    subst m
    exact hABC ⟨g, hAm, hBg, hCg⟩
  have hDE : D ≠ E := by
    intro h
    subst E
    have hEq : g = m :=
      HilbertPlaneIncidence.line_unique
        B D hBD g m hBg hDg hBm hEm
    exact hgm hEq
  rcases HilbertPlaneIncidence.line_through D E hDE with
    ⟨l, hDl, hEl⟩
  have hgl : g ≠ l := by
    intro h
    subst l
    have hEq : m = g :=
      HilbertPlaneIncidence.line_unique
        B E hEB.symm m g hBm hEm hBg hEl
    exact hgm hEq.symm
  have hlm : l ≠ m := by
    intro h
    subst m
    have hEq : g = l :=
      HilbertPlaneIncidence.line_unique
        B D hBD g l hBg hDg hBm hDl
    exact hgl hEq
  have hAl : ¬ HilbertIncidence.OnLine A l := by
    intro hAl
    have hEq : l = m :=
      HilbertPlaneIncidence.line_unique
        A E hAE l m hAl hEl hAm hEm
    exact hlm hEq
  have hBl : ¬ HilbertIncidence.OnLine B l := by
    intro hBl
    have hEq : m = l :=
      HilbertPlaneIncidence.line_unique
        B E hEB.symm m l hBm hEm hBl hEl
    exact hlm hEq.symm
  have hCl : ¬ HilbertIncidence.OnLine C l := by
    intro hCl
    have hEq : g = l :=
      HilbertPlaneIncidence.line_unique
        C D hCD g l hCg hDg hCl hDl
    exact hgl hEq
  have hNotBDC : ¬ Geo.Between B D C :=
    (HilbertOrder.between_unique
      (Geo := Geo) B C D hBCDData.2.2.2.1 hBCD).2
  have hNotMeetsBC : ¬ HilbertSegmentMeetsLine Geo B C l :=
    hilbert_segment_not_meets_crossing_line
      Geo B C D g l hgl hBg hCg hDg hDl hNotBDC
  have hMeetsAB : HilbertSegmentMeetsLine Geo A B l :=
    ⟨E, hAEB, hEl⟩
  rcases
      hilbert_pasch_forced
        Geo A B C l hABC hAl hBl hCl
        hMeetsAB hNotMeetsBC with
    ⟨F, hAFC, hFl⟩
  have hAFCData := HilbertOrder.between_incidence A F C hAFC
  rcases HilbertPlaneIncidence.line_through A C hAC with
    ⟨k, hAk, hCk⟩
  have hFk : HilbertIncidence.OnLine F k :=
    hilbert_between_on_line Geo A F C k hAk hCk hAFC
  have hkg : k ≠ g := by
    intro h
    subst g
    exact hABC ⟨k, hAk, hBg, hCk⟩
  have hkm : k ≠ m := by
    intro h
    subst m
    exact hABC ⟨k, hAk, hBm, hCk⟩
  have hDF : D ≠ F := by
    intro h
    subst F
    have hEq : k = g :=
      HilbertPlaneIncidence.line_unique
        C D hCD k g hCk hFk hCg hDg
    exact hkg hEq
  have hEF : E ≠ F := by
    intro h
    subst F
    have hEq : k = m :=
      HilbertPlaneIncidence.line_unique
        A E hAE k m hAk hFk hAm hEm
    exact hkm hEq
  have hDEFCol : PrimCollinear Geo D E F :=
    ⟨l, hDl, hEl, hFl⟩
  rcases
      hilbert_between_trichotomy
        Geo D E F hDE hEF hDF hDEFCol with
    hDEF | hEDF | hDFE
  · have hDk : ¬ HilbertIncidence.OnLine D k := by
      intro hDk
      have hEq : k = g :=
        HilbertPlaneIncidence.line_unique
          C D hCD k g hCk hDk hCg hDg
      exact hkg hEq
    have hDFC : ¬ PrimCollinear Geo D F C := by
      intro h
      exact
        (hilbert_not_collinear_of_off_line
          Geo F C D k hAFCData.2.1 hFk hCk hDk)
          (PrimCollinearCycle Geo D F C h)
    have hDm : ¬ HilbertIncidence.OnLine D m := by
      intro hDm
      have hEq : g = m :=
        HilbertPlaneIncidence.line_unique
          B D hBD g m hBg hDg hBm hDm
      exact hgm hEq
    have hFm : ¬ HilbertIncidence.OnLine F m := by
      intro hFm
      have hEq : k = m :=
        HilbertPlaneIncidence.line_unique
          A F hAFCData.1 k m hAk hFk hAm hFm
      exact hkm hEq
    have hCm : ¬ HilbertIncidence.OnLine C m := by
      intro hCm
      exact hABC ⟨m, hAm, hBm, hCm⟩
    have hDCB :=
      (HilbertOrder.between_incidence B C D hBCD).2.2.2.2
    have hNotDBC : ¬ Geo.Between D B C :=
      (HilbertOrder.between_unique
        (Geo := Geo) D C B
        (HilbertOrder.between_incidence D C B hDCB).2.2.2.1
        hDCB).2
    have hNotMeetsDC : ¬ HilbertSegmentMeetsLine Geo D C m :=
      hilbert_segment_not_meets_crossing_line
        Geo D C B g m hgm hDg hCg hBg hBm hNotDBC
    have hNotFAC : ¬ Geo.Between F A C :=
      (HilbertOrder.between_unique
        (Geo := Geo) A F C hAFCData.2.2.2.1 hAFC).1
    have hNotMeetsFC : ¬ HilbertSegmentMeetsLine Geo F C m :=
      hilbert_segment_not_meets_crossing_line
        Geo F C A k m hkm hFk hCk hAk hAm hNotFAC
    have hMeetsDF : HilbertSegmentMeetsLine Geo D F m :=
      ⟨E, hDEF, hEm⟩
    rcases HilbertOrder.pasch
        (Geo := Geo) D F C hDFC m hDm hFm hCm hMeetsDF with
      hMeetsDC | hMeetsFC
    · exact False.elim (hNotMeetsDC hMeetsDC)
    · exact False.elim (hNotMeetsFC hMeetsFC)
  · have hEg : ¬ HilbertIncidence.OnLine E g := by
      intro hEg
      have hEq : m = g :=
        HilbertPlaneIncidence.line_unique
          B E hEB.symm m g hBm hEm hBg hEg
      exact hgm hEq.symm
    have hFg : ¬ HilbertIncidence.OnLine F g := by
      intro hFg
      have hEq : k = g :=
        HilbertPlaneIncidence.line_unique
          C F hAFCData.2.1.symm k g hCk hFk hCg hFg
      exact hkg hEq
    have hAg : ¬ HilbertIncidence.OnLine A g := by
      intro hAg
      exact hABC ⟨g, hAg, hBg, hCg⟩
    have hEFA : ¬ PrimCollinear Geo E F A := by
      intro h
      have hAFEm : PrimCollinear Geo A F E :=
        PrimCollinearRotate Geo A E F
          (PrimCollinearCycle Geo
            F A E (PrimCollinearCycle Geo E F A h))
      rcases hAFEm with ⟨q, hAq, hFq, hEq⟩
      have hkq : k = q :=
        HilbertPlaneIncidence.line_unique
          A F hAFCData.1 k q hAk hFk hAq hFq
      rw [← hkq] at hEq
      have hmk : m = k :=
        HilbertPlaneIncidence.line_unique
          A E hAE m k hAm hEm hAk hEq
      exact hkm hmk.symm
    have hBEA :=
      (HilbertOrder.between_incidence A E B hAEB).2.2.2.2
    have hNotEBA : ¬ Geo.Between E B A :=
      (HilbertOrder.between_unique
        (Geo := Geo) B E A
        (HilbertOrder.between_incidence B E A hBEA).2.2.2.1
        hBEA).1
    have hNotMeetsEA : ¬ HilbertSegmentMeetsLine Geo E A g :=
      hilbert_segment_not_meets_crossing_line
        Geo E A B m g hgm.symm hEm hAm hBm hBg hNotEBA
    have hCFA :=
      (HilbertOrder.between_incidence A F C hAFC).2.2.2.2
    have hNotFCA : ¬ Geo.Between F C A :=
      (HilbertOrder.between_unique
        (Geo := Geo) C F A
        (HilbertOrder.between_incidence C F A hCFA).2.2.2.1
        hCFA).1
    have hNotMeetsFA : ¬ HilbertSegmentMeetsLine Geo F A g :=
      hilbert_segment_not_meets_crossing_line
        Geo F A C k g hkg hFk hAk hCk hCg hNotFCA
    have hMeetsEF : HilbertSegmentMeetsLine Geo E F g :=
      ⟨D, hEDF, hDg⟩
    rcases HilbertOrder.pasch
        (Geo := Geo) E F A hEFA g hEg hFg hAg hMeetsEF with
      hMeetsEA | hMeetsFA
    · exact False.elim (hNotMeetsEA hMeetsEA)
    · exact False.elim (hNotMeetsFA hMeetsFA)
  · exact ⟨F, hDFE, hAFC⟩

/--
The strengthened outer form of Pasch used in Hilbert's proof of
Theorem 5.  As with `hilbert_inner_pasch_strong`, the extra
betweenness conclusion is derived from II.3, II.4 and Theorem 4.
-/
theorem hilbert_outer_pasch_strong
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B C D E : Geo.Point)
    (hABC : ¬ PrimCollinear Geo A B C)
    (hBCD : Geo.Between B C D)
    (hAEC : Geo.Between A E C) :
    ∃ F : Geo.Point,
      Geo.Between D E F ∧
      Geo.Between A F B := by
  have hBCDData := HilbertOrder.between_incidence B C D hBCD
  have hAECData := HilbertOrder.between_incidence A E C hAEC
  have hBC : B ≠ C := hBCDData.1
  have hCD : C ≠ D := hBCDData.2.1
  have hBD : B ≠ D := hBCDData.2.2.1
  have hAE : A ≠ E := hAECData.1
  have hEC : E ≠ C := hAECData.2.1
  have hAC : A ≠ C := hAECData.2.2.1
  have hAB : A ≠ B :=
    hilbert_noncollinear_ne_first Geo A B C hABC
  rcases HilbertPlaneIncidence.line_through B C hBC with
    ⟨g, hBg, hCg⟩
  have hDg : HilbertIncidence.OnLine D g :=
    hilbert_collinear_on_line
      Geo B C D g hBC hBg hCg hBCDData.2.2.2.1
  rcases HilbertPlaneIncidence.line_through A C hAC with
    ⟨k, hAk, hCk⟩
  have hEk : HilbertIncidence.OnLine E k :=
    hilbert_between_on_line Geo A E C k hAk hCk hAEC
  rcases HilbertPlaneIncidence.line_through A B hAB with
    ⟨m, hAm, hBm⟩
  have hkg : k ≠ g := by
    intro h
    subst g
    exact hABC ⟨k, hAk, hBg, hCk⟩
  have hkm : k ≠ m := by
    intro h
    subst m
    exact hABC ⟨k, hAk, hBm, hCk⟩
  have hgm : g ≠ m := by
    intro h
    subst m
    exact hABC ⟨g, hAm, hBg, hCg⟩
  have hDE : D ≠ E := by
    intro h
    subst E
    have hEq : k = g :=
      HilbertPlaneIncidence.line_unique
        C D hCD k g hCk hEk hCg hDg
    exact hkg hEq
  rcases HilbertPlaneIncidence.line_through D E hDE with
    ⟨l, hDl, hEl⟩
  have hgl : g ≠ l := by
    intro h
    subst l
    have hEq : k = g :=
      HilbertPlaneIncidence.line_unique
        C E hEC.symm k g hCk hEk hCg hEl
    exact hkg hEq
  have hkl : k ≠ l := by
    intro h
    subst l
    have hEq : g = k :=
      HilbertPlaneIncidence.line_unique
        C D hCD g k hCg hDg hCk hDl
    exact hkg hEq.symm
  have hAl : ¬ HilbertIncidence.OnLine A l := by
    intro hAl
    have hEq : k = l :=
      HilbertPlaneIncidence.line_unique
        A E hAE k l hAk hEk hAl hEl
    exact hkl hEq
  have hCl : ¬ HilbertIncidence.OnLine C l := by
    intro hCl
    have hEq : g = l :=
      HilbertPlaneIncidence.line_unique
        C D hCD g l hCg hDg hCl hDl
    exact hgl hEq
  have hBl : ¬ HilbertIncidence.OnLine B l := by
    intro hBl
    have hEq : g = l :=
      HilbertPlaneIncidence.line_unique
        B D hBD g l hBg hDg hBl hDl
    exact hgl hEq
  have hNotBDC : ¬ Geo.Between B D C :=
    (HilbertOrder.between_unique
      (Geo := Geo) B C D hBCDData.2.2.2.1 hBCD).2
  have hNotCDB : ¬ Geo.Between C D B := by
    intro hCDB
    exact
      hNotBDC
        (HilbertOrder.between_incidence C D B hCDB).2.2.2.2
  have hNotMeetsCB : ¬ HilbertSegmentMeetsLine Geo C B l :=
    hilbert_segment_not_meets_crossing_line
      Geo C B D g l hgl hCg hBg hDg hDl hNotCDB
  have hMeetsAC : HilbertSegmentMeetsLine Geo A C l :=
    ⟨E, hAEC, hEl⟩
  have hACB : ¬ PrimCollinear Geo A C B :=
    fun h => hABC (PrimCollinearRotate Geo A C B h)
  rcases
      hilbert_pasch_forced
        Geo A C B l hACB hAl hCl hBl
        hMeetsAC hNotMeetsCB with
    ⟨F, hAFB, hFl⟩
  have hAFBData := HilbertOrder.between_incidence A F B hAFB
  have hFm : HilbertIncidence.OnLine F m :=
    hilbert_between_on_line Geo A F B m hAm hBm hAFB
  have hDF : D ≠ F := by
    intro h
    subst F
    have hEq : g = m :=
      HilbertPlaneIncidence.line_unique
        B D hBD g m hBg hDg hBm hFm
    exact hgm hEq
  have hEF : E ≠ F := by
    intro h
    subst F
    have hEq : k = m :=
      HilbertPlaneIncidence.line_unique
        A E hAE k m hAk hEk hAm hFm
    exact hkm hEq
  have hDEFCol : PrimCollinear Geo D E F :=
    ⟨l, hDl, hEl, hFl⟩
  rcases
      hilbert_between_trichotomy
        Geo D E F hDE hEF hDF hDEFCol with
    hDEF | hEDF | hDFE
  · exact ⟨F, hDEF, hAFB⟩
  · have hEg : ¬ HilbertIncidence.OnLine E g := by
      intro hEg
      have hEq : k = g :=
        HilbertPlaneIncidence.line_unique
          C E hEC.symm k g hCk hEk hCg hEg
      exact hkg hEq
    have hFg : ¬ HilbertIncidence.OnLine F g := by
      intro hFg
      have hEq : m = g :=
        HilbertPlaneIncidence.line_unique
          B F hAFBData.2.1.symm m g hBm hFm hBg hFg
      exact hgm hEq.symm
    have hAg : ¬ HilbertIncidence.OnLine A g := by
      intro hAg
      exact hABC ⟨g, hAg, hBg, hCg⟩
    have hEFA : ¬ PrimCollinear Geo E F A := by
      intro h
      have hAFE : PrimCollinear Geo A F E :=
        PrimCollinearRotate Geo A E F
          (PrimCollinearCycle Geo
            F A E (PrimCollinearCycle Geo E F A h))
      rcases hAFE with ⟨q, hAq, hFq, hEq⟩
      have hmq : m = q :=
        HilbertPlaneIncidence.line_unique
          A F hAFBData.1 m q hAm hFm hAq hFq
      rw [← hmq] at hEq
      have hkm' : k = m :=
        HilbertPlaneIncidence.line_unique
          A E hAE k m hAk hEk hAm hEq
      exact hkm hkm'
    have hNotACE : ¬ Geo.Between A C E :=
      (HilbertOrder.between_unique
        (Geo := Geo) A E C hAECData.2.2.2.1 hAEC).2
    have hNotECA : ¬ Geo.Between E C A := by
      intro hECA
      exact
        hNotACE
          (HilbertOrder.between_incidence E C A hECA).2.2.2.2
    have hNotMeetsEA : ¬ HilbertSegmentMeetsLine Geo E A g :=
      hilbert_segment_not_meets_crossing_line
        Geo E A C k g hkg hEk hAk hCk hCg hNotECA
    have hNotABF : ¬ Geo.Between A B F :=
      (HilbertOrder.between_unique
        (Geo := Geo) A F B hAFBData.2.2.2.1 hAFB).2
    have hNotFBA : ¬ Geo.Between F B A := by
      intro hFBA
      exact
        hNotABF
          (HilbertOrder.between_incidence F B A hFBA).2.2.2.2
    have hNotMeetsFA : ¬ HilbertSegmentMeetsLine Geo F A g :=
      hilbert_segment_not_meets_crossing_line
        Geo F A B m g hgm.symm hFm hAm hBm hBg hNotFBA
    have hMeetsEF : HilbertSegmentMeetsLine Geo E F g :=
      ⟨D, hEDF, hDg⟩
    rcases HilbertOrder.pasch
        (Geo := Geo) E F A hEFA g hEg hFg hAg hMeetsEF with
      hMeetsEA | hMeetsFA
    · exact False.elim (hNotMeetsEA hMeetsEA)
    · exact False.elim (hNotMeetsFA hMeetsFA)
  · have hDm : ¬ HilbertIncidence.OnLine D m := by
      intro hDm
      have hEq : g = m :=
        HilbertPlaneIncidence.line_unique
          B D hBD g m hBg hDg hBm hDm
      exact hgm hEq
    have hEm : ¬ HilbertIncidence.OnLine E m := by
      intro hEm
      have hEq : k = m :=
        HilbertPlaneIncidence.line_unique
          A E hAE k m hAk hEk hAm hEm
      exact hkm hEq
    have hCm : ¬ HilbertIncidence.OnLine C m := by
      intro hCm
      exact hABC ⟨m, hAm, hBm, hCm⟩
    have hDEC : ¬ PrimCollinear Geo D E C := by
      intro h
      rcases h with ⟨q, hDq, hEq, hCq⟩
      have hgq : g = q :=
        HilbertPlaneIncidence.line_unique
          C D hCD g q hCg hDg hCq hDq
      rw [← hgq] at hEq
      have hkg' : k = g :=
        HilbertPlaneIncidence.line_unique
          C E hEC.symm k g hCk hEk hCg hEq
      exact hkg hkg'
    have hDCB :=
      (HilbertOrder.between_incidence B C D hBCD).2.2.2.2
    have hNotDBC : ¬ Geo.Between D B C :=
      (HilbertOrder.between_unique
        (Geo := Geo) D C B
        (HilbertOrder.between_incidence D C B hDCB).2.2.2.1
        hDCB).2
    have hNotMeetsDC : ¬ HilbertSegmentMeetsLine Geo D C m :=
      hilbert_segment_not_meets_crossing_line
        Geo D C B g m hgm hDg hCg hBg hBm hNotDBC
    have hNotEAC : ¬ Geo.Between E A C :=
      (HilbertOrder.between_unique
        (Geo := Geo) A E C hAECData.2.2.2.1 hAEC).1
    have hNotMeetsEC : ¬ HilbertSegmentMeetsLine Geo E C m :=
      hilbert_segment_not_meets_crossing_line
        Geo E C A k m hkm hEk hCk hAk hAm hNotEAC
    have hMeetsDE : HilbertSegmentMeetsLine Geo D E m :=
      ⟨F, hDFE, hFm⟩
    rcases HilbertOrder.pasch
        (Geo := Geo) D E C hDEC m hDm hEm hCm hMeetsDE with
      hMeetsDC | hMeetsEC
    · exact False.elim (hNotMeetsDC hMeetsDC)
    · exact False.elim (hNotMeetsEC hMeetsEC)

/--
The first assertion in Hilbert's Theorem 5, in the one orientation
needed below: from `A-B-C` and `B-C-D` infer `A-C-D`.

The construction is Hilbert's: two applications of strengthened inner
Pasch followed by one application of strengthened outer Pasch.
-/
theorem hilbert_between_outer_trans_right
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B C D : Geo.Point)
    (hABC : Geo.Between A B C)
    (hBCD : Geo.Between B C D) :
    Geo.Between A C D := by
  have hABCData := HilbertOrder.between_incidence A B C hABC
  have hBCDData := HilbertOrder.between_incidence B C D hBCD
  have hAC : A ≠ C := hABCData.2.2.1
  have hBC : B ≠ C := hABCData.2.1
  rcases HilbertPlaneIncidence.line_through A C hAC with
    ⟨g, hAg, hCg⟩
  have hBg : HilbertIncidence.OnLine B g :=
    hilbert_between_on_line Geo A B C g hAg hCg hABC
  have hDg : HilbertIncidence.OnLine D g :=
    hilbert_collinear_on_line
      Geo B C D g hBC hBg hCg hBCDData.2.2.2.1
  rcases hilbert_point_off_line Geo g with ⟨E, hEg⟩
  have hCE : C ≠ E := by
    intro h
    subst E
    exact hEg hCg
  rcases HilbertOrder.between_extension C E hCE with
    ⟨F, hCEF⟩
  have hCEFData := HilbertOrder.between_incidence C E F hCEF
  rcases HilbertPlaneIncidence.line_through C E hCE with
    ⟨n, hCn, hEn⟩
  have hFn : HilbertIncidence.OnLine F n :=
    hilbert_collinear_on_line
      Geo C E F n hCE hCn hEn hCEFData.2.2.2.1
  have hACE : ¬ PrimCollinear Geo A C E :=
    hilbert_not_collinear_of_off_line
      Geo A C E g hAC hAg hCg hEg
  rcases
      hilbert_inner_pasch_strong
        Geo A C E F B hACE hCEF hABC with
    ⟨G, hFGB, hAGE⟩
  have hBGF : Geo.Between B G F :=
    (HilbertOrder.between_incidence F G B hFGB).2.2.2.2
  have hAGEData := HilbertOrder.between_incidence A G E hAGE
  have hGg : ¬ HilbertIncidence.OnLine G g := by
    intro hGg
    have hEOnG :=
      hilbert_collinear_on_line
        Geo A G E g hAGEData.1 hAg hGg hAGEData.2.2.2.1
    exact hEg hEOnG
  have hBD : B ≠ D := hBCDData.2.2.1
  have hDBG : ¬ PrimCollinear Geo D B G :=
    hilbert_not_collinear_of_off_line
      Geo D B G g hBD.symm hDg hBg hGg
  have hDCB : Geo.Between D C B :=
    hBCDData.2.2.2.2
  rcases
      hilbert_inner_pasch_strong
        Geo D B G F C hDBG hBGF hDCB with
    ⟨H, hFHC, hDHG⟩
  have hCHF : Geo.Between C H F :=
    (HilbertOrder.between_incidence F H C hFHC).2.2.2.2
  have hHn : HilbertIncidence.OnLine H n :=
    hilbert_between_on_line Geo C H F n hCn hFn hCHF
  have hAD : A ≠ D := by
    intro h
    subst D
    have hACB : Geo.Between A C B :=
      (HilbertOrder.between_incidence B C A hBCD).2.2.2.2
    exact
      (HilbertOrder.between_unique
        (Geo := Geo) A B C hABCData.2.2.2.1 hABC).2 hACB
  have hDAG : ¬ PrimCollinear Geo D A G :=
    hilbert_not_collinear_of_off_line
      Geo D A G g hAD.symm hDg hAg hGg
  rcases
      hilbert_outer_pasch_strong
        Geo D A G E H hDAG hAGE hDHG with
    ⟨C', hEHC', hDC'A⟩
  have hAC'D : Geo.Between A C' D :=
    (HilbertOrder.between_incidence D C' A hDC'A).2.2.2.2
  have hC'g : HilbertIncidence.OnLine C' g :=
    hilbert_between_on_line Geo A C' D g hAg hDg hAC'D
  have hEHC'Data := HilbertOrder.between_incidence E H C' hEHC'
  have hC'n : HilbertIncidence.OnLine C' n :=
    hilbert_collinear_on_line
      Geo E H C' n hEHC'Data.1 hEn hHn hEHC'Data.2.2.2.1
  have hgn : g ≠ n := by
    intro h
    subst n
    exact hEg hEn
  have hC'C :=
    hilbert_common_point_unique
      Geo g n hgn C C' hCg hCn hC'g hC'n
  subst C'
  exact hAC'D

/--
Both conclusions of the first assertion in Hilbert's Theorem 5.
-/
theorem hilbert_between_outer_trans
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B C D : Geo.Point)
    (hABC : Geo.Between A B C)
    (hBCD : Geo.Between B C D) :
    Geo.Between A C D ∧
    Geo.Between A B D := by
  have hACD :=
    hilbert_between_outer_trans_right Geo A B C D hABC hBCD
  have hDCB :=
    (HilbertOrder.between_incidence B C D hBCD).2.2.2.2
  have hCBA :=
    (HilbertOrder.between_incidence A B C hABC).2.2.2.2
  have hDBA :=
    hilbert_between_outer_trans_right Geo D C B A hDCB hCBA
  exact
    ⟨hACD,
      (HilbertOrder.between_incidence D B A hDBA).2.2.2.2⟩

/--
The second assertion in Hilbert's Theorem 5: from `A-B-C` and
`A-C-D` infer `B-C-D` and `A-B-D`.

Only the first conclusion needs a new Pasch construction.  The second
then follows from `hilbert_between_outer_trans`.
-/
theorem hilbert_between_inner_trans
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A B C D : Geo.Point)
    (hABC : Geo.Between A B C)
    (hACD : Geo.Between A C D) :
    Geo.Between B C D ∧
    Geo.Between A B D := by
  have hABCData := HilbertOrder.between_incidence A B C hABC
  have hACDData := HilbertOrder.between_incidence A C D hACD
  have hAB : A ≠ B := hABCData.1
  have hBC : B ≠ C := hABCData.2.1
  have hAC : A ≠ C := hACDData.1
  have hCD : C ≠ D := hACDData.2.1
  have hAD : A ≠ D := hACDData.2.2.1
  rcases HilbertPlaneIncidence.line_through A D hAD with
    ⟨g, hAg, hDg⟩
  have hCg : HilbertIncidence.OnLine C g :=
    hilbert_between_on_line Geo A C D g hAg hDg hACD
  have hBg : HilbertIncidence.OnLine B g :=
    hilbert_collinear_on_line
      Geo A C B g hAC hAg hCg
      (PrimCollinearRotate Geo A B C hABCData.2.2.2.1)
  rcases hilbert_point_off_line Geo g with ⟨G, hGg⟩
  have hBG : B ≠ G := by
    intro h
    subst G
    exact hGg hBg
  rcases HilbertOrder.between_extension B G hBG with
    ⟨F, hBGF⟩
  have hBGFData := HilbertOrder.between_incidence B G F hBGF
  rcases HilbertPlaneIncidence.line_through B G hBG with
    ⟨r, hBr, hGr⟩
  have hFr : HilbertIncidence.OnLine F r :=
    hilbert_collinear_on_line
      Geo B G F r hBG hBr hGr hBGFData.2.2.2.1
  have hFg : ¬ HilbertIncidence.OnLine F g := by
    intro hFg
    have hEq : g = r :=
      HilbertPlaneIncidence.line_unique
        B F hBGFData.2.2.1 g r hBg hFg hBr hFr
    rw [← hEq] at hGr
    exact hGg hGr
  have hCF : C ≠ F := by
    intro h
    subst F
    exact hFg hCg
  rcases HilbertPlaneIncidence.line_through C F hCF with
    ⟨n, hCn, hFn⟩
  have hgn : g ≠ n := by
    intro h
    subst n
    exact hFg hFn
  have hrn : r ≠ n := by
    intro h
    subst n
    have hEq : g = r :=
      HilbertPlaneIncidence.line_unique
        B C hBC g r hBg hCg hBr hCn
    rw [← hEq] at hGr
    exact hGg hGr
  have hAn : ¬ HilbertIncidence.OnLine A n := by
    intro hAn
    have hEq : g = n :=
      HilbertPlaneIncidence.line_unique
        A C hAC g n hAg hCg hAn hCn
    exact hgn hEq
  have hBn : ¬ HilbertIncidence.OnLine B n := by
    intro hBn
    have hEq : g = n :=
      HilbertPlaneIncidence.line_unique
        B C hBC g n hBg hCg hBn hCn
    exact hgn hEq
  have hDn : ¬ HilbertIncidence.OnLine D n := by
    intro hDn
    have hEq : g = n :=
      HilbertPlaneIncidence.line_unique
        C D hCD g n hCg hDg hCn hDn
    exact hgn hEq
  have hGn : ¬ HilbertIncidence.OnLine G n := by
    intro hGn
    have hEq : r = n :=
      HilbertPlaneIncidence.line_unique
        G F hBGFData.2.1 r n hGr hFr hGn hFn
    exact hrn hEq
  have hNotACB : ¬ Geo.Between A C B :=
    (HilbertOrder.between_unique
      (Geo := Geo) A B C hABCData.2.2.2.1 hABC).2
  have hNotMeetsAB : ¬ HilbertSegmentMeetsLine Geo A B n :=
    hilbert_segment_not_meets_crossing_line
      Geo A B C g n hgn hAg hBg hCg hCn hNotACB
  have hNotBFG : ¬ Geo.Between B F G :=
    (HilbertOrder.between_unique
      (Geo := Geo) B G F hBGFData.2.2.2.1 hBGF).2
  have hNotMeetsBG : ¬ HilbertSegmentMeetsLine Geo B G n :=
    hilbert_segment_not_meets_crossing_line
      Geo B G F r n hrn hBr hGr hFr hFn hNotBFG
  have hABG : ¬ PrimCollinear Geo A B G :=
    hilbert_not_collinear_of_off_line
      Geo A B G g hAB hAg hBg hGg
  have hAGB : ¬ PrimCollinear Geo A G B :=
    fun h => hABG (PrimCollinearRotate Geo A G B h)
  have hNotMeetsAG : ¬ HilbertSegmentMeetsLine Geo A G n := by
    intro hMeetsAG
    rcases HilbertOrder.pasch
        (Geo := Geo) A G B hAGB n hAn hGn hBn hMeetsAG with
      hMeetsAB | hMeetsGB
    · exact hNotMeetsAB hMeetsAB
    · rcases hMeetsGB with ⟨X, hGXB, hXn⟩
      exact
        hNotMeetsBG
          ⟨X,
            (HilbertOrder.between_incidence G X B hGXB).2.2.2.2,
            hXn⟩
  have hADG : ¬ PrimCollinear Geo A D G :=
    hilbert_not_collinear_of_off_line
      Geo A D G g hAD hAg hDg hGg
  have hMeetsAD : HilbertSegmentMeetsLine Geo A D n :=
    ⟨C, hACD, hCn⟩
  have hMeetsDG : HilbertSegmentMeetsLine Geo D G n := by
    rcases HilbertOrder.pasch
        (Geo := Geo) A D G hADG n hAn hDn hGn hMeetsAD with
      hMeetsAG | hMeetsDG
    · exact False.elim (hNotMeetsAG hMeetsAG)
    · exact hMeetsDG
  rcases hMeetsDG with ⟨H, hDHG, hHn⟩
  have hBD : B ≠ D := by
    intro h
    subst D
    have hACB : Geo.Between A C B := hACD
    exact hNotACB hACB
  have hDBG : ¬ PrimCollinear Geo D B G :=
    hilbert_not_collinear_of_off_line
      Geo D B G g hBD.symm hDg hBg hGg
  have hGDB : ¬ PrimCollinear Geo G D B := by
    intro h
    exact hDBG (PrimCollinearCycle Geo G D B h)
  have hGHD : Geo.Between G H D :=
    (HilbertOrder.between_incidence D H G hDHG).2.2.2.2
  have hMeetsGD : HilbertSegmentMeetsLine Geo G D n :=
    ⟨H, hGHD, hHn⟩
  have hMeetsDB : HilbertSegmentMeetsLine Geo D B n := by
    rcases HilbertOrder.pasch
        (Geo := Geo) G D B hGDB n hGn hDn hBn hMeetsGD with
      hMeetsGB | hMeetsDB
    · rcases hMeetsGB with ⟨X, hGXB, hXn⟩
      exact
        False.elim
          (hNotMeetsBG
            ⟨X,
              (HilbertOrder.between_incidence G X B hGXB).2.2.2.2,
              hXn⟩)
    · exact hMeetsDB
  rcases hMeetsDB with ⟨C', hDC'B, hC'n⟩
  have hBC'D : Geo.Between B C' D :=
    (HilbertOrder.between_incidence D C' B hDC'B).2.2.2.2
  have hC'g : HilbertIncidence.OnLine C' g :=
    hilbert_between_on_line Geo B C' D g hBg hDg hBC'D
  have hC'C :=
    hilbert_common_point_unique
      Geo g n hgn C C' hCg hCn hC'g hC'n
  subst C'
  have hOuter :=
    hilbert_between_outer_trans Geo A B C D hABC hBC'D
  exact ⟨hBC'D, hOuter.2⟩

theorem hilbert_sameRay_collinear
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O R X : Geo.Point) :
    HilbertSameRay Geo O R X →
    PrimCollinear Geo O R X := by
  exact fun h => h.2.2.1

theorem hilbert_oppositeRays_of_between
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A O C : Geo.Point)
    (hAOC : Geo.Between A O C) :
    Geo.OppositeRays O A C := by
  have hData := HilbertOrder.between_incidence A O C hAOC
  exact ⟨hData.1, hData.2.1.symm, hAOC⟩

theorem hilbert_adjacentAngles_of_between
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A O B C : Geo.Point)
    (hAOC : Geo.Between A O C)
    (hBO : B ≠ O) :
    Geo.AdjacentAngles A O B C :=
  ⟨hBO, hilbert_oppositeRays_of_between Geo A O C hAOC⟩

theorem hilbert_sameRay_of_between
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O P Q : Geo.Point)
    (hOPQ : Geo.Between O P Q) :
    HilbertSameRay Geo O P Q := by
  have hData := HilbertOrder.between_incidence O P Q hOPQ
  exact
    ⟨hData.1.symm,
      hData.2.2.1.symm,
      hData.2.2.2.1,
      (HilbertOrder.between_unique
        (Geo := Geo) O P Q hData.2.2.2.1 hOPQ).1⟩

theorem hilbert_not_sameRay_of_between_origin
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A O C : Geo.Point)
    (hAOC : Geo.Between A O C) :
    ¬ HilbertSameRay Geo O A C := by
  intro hRay
  exact hRay.2.2.2 hAOC

theorem hilbert_sameRay_cases
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O P Q : Geo.Point)
    (hRay : HilbertSameRay Geo O P Q) :
    P = Q ∨
    Geo.Between O P Q ∨
    Geo.Between O Q P := by
  by_cases hPQ : P = Q
  · exact Or.inl hPQ
  · rcases hilbert_between_trichotomy
        Geo O P Q hRay.1.symm hPQ hRay.2.1.symm hRay.2.2.1 with
      hOPQ | hPOQ | hOQP
    · exact Or.inr (Or.inl hOPQ)
    · exact False.elim (hRay.2.2.2 hPOQ)
    · exact Or.inr (Or.inr hOQP)

/--
Transport of strict betweenness along the two rays determined by a
point lying between their original representatives.

This is the precise local consequence of Hilbert's Theorem 5 needed
in the proof of Theorem 14: if `O` is between `A` and `C`, replacing
`A` and `C` by arbitrary points on the same respective rays preserves
that betweenness.
-/
theorem hilbert_between_transport_sameRays
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A O C A' C' : Geo.Point)
    (hAOC : Geo.Between A O C)
    (hAA' : HilbertSameRay Geo O A A')
    (hCC' : HilbertSameRay Geo O C C') :
    Geo.Between A' O C' := by
  have hSymm :
      ∀ X Y Z : Geo.Point,
        Geo.Between X Y Z → Geo.Between Z Y X :=
    fun X Y Z h =>
      (HilbertOrder.between_incidence X Y Z h).2.2.2.2
  rcases hilbert_sameRay_cases Geo O A A' hAA' with
    hAeq | hOAA' | hOA'A
  · subst A'
    rcases hilbert_sameRay_cases Geo O C C' hCC' with
      hCeq | hOCC' | hOC'C
    · subst C'
      exact hAOC
    · exact
        (hilbert_between_outer_trans
          Geo A O C C' hAOC hOCC').2
    · have hCC'O : Geo.Between C C' O := hSymm O C' C hOC'C
      have hCOA : Geo.Between C O A := hSymm A O C hAOC
      have hC'OA :=
        (hilbert_between_inner_trans
          Geo C C' O A hCC'O hCOA).1
      exact hSymm C' O A hC'OA
  · have hCOA : Geo.Between C O A := hSymm A O C hAOC
    have hA'OC : Geo.Between A' O C := by
      have hCOA' :=
        (hilbert_between_outer_trans
          Geo C O A A' hCOA hOAA').2
      exact hSymm C O A' hCOA'
    rcases hilbert_sameRay_cases Geo O C C' hCC' with
      hCeq | hOCC' | hOC'C
    · subst C'
      exact hA'OC
    · exact
        (hilbert_between_outer_trans
          Geo A' O C C' hA'OC hOCC').2
    · have hCC'O : Geo.Between C C' O := hSymm O C' C hOC'C
      have hCOA' : Geo.Between C O A' := hSymm A' O C hA'OC
      have hC'OA' :=
        (hilbert_between_inner_trans
          Geo C C' O A' hCC'O hCOA').1
      exact hSymm C' O A' hC'OA'
  · have hAA'O : Geo.Between A A' O := hSymm O A' A hOA'A
    have hA'OC :=
      (hilbert_between_inner_trans
        Geo A A' O C hAA'O hAOC).1
    rcases hilbert_sameRay_cases Geo O C C' hCC' with
      hCeq | hOCC' | hOC'C
    · subst C'
      exact hA'OC
    · exact
        (hilbert_between_outer_trans
          Geo A' O C C' hA'OC hOCC').2
    · have hCC'O : Geo.Between C C' O := hSymm O C' C hOC'C
      have hCOA' : Geo.Between C O A' := hSymm A' O C hA'OC
      have hC'OA' :=
        (hilbert_between_inner_trans
          Geo C C' O A' hCC'O hCOA').1
      exact hSymm C' O A' hC'OA'

theorem hilbert_sameRay_refl
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O P : Geo.Point)
    (hPO : P ≠ O) :
    HilbertSameRay Geo O P P := by
  rcases HilbertPlaneIncidence.line_through O P hPO.symm with
    ⟨l, hOl, hPl⟩
  refine ⟨hPO, hPO, ⟨l, hOl, hPl, hPl⟩, ?_⟩
  intro hPOP
  exact (HilbertOrder.between_incidence P O P hPOP).2.2.1 rfl

theorem hilbert_sameRay_symm
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O P Q : Geo.Point) :
    HilbertSameRay Geo O P Q →
    HilbertSameRay Geo O Q P := by
  intro h
  refine ⟨h.2.1, h.1, ?_, ?_⟩
  · exact PrimCollinearRotate Geo O P Q h.2.2.1
  · intro hQOP
    exact
      h.2.2.2
        (HilbertOrder.between_incidence Q O P hQOP).2.2.2.2

theorem hilbert_sameRay_sameSideStep
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O R X C : Geo.Point)
    (base cross : Geo.Line)
    (hObase : HilbertIncidence.OnLine O base)
    (hRbase : HilbertIncidence.OnLine R base)
    (hOcross : HilbertIncidence.OnLine O cross)
    (hCcross : HilbertIncidence.OnLine C cross)
    (hCbase : ¬ HilbertIncidence.OnLine C base)
    (hRX : HilbertSameRay Geo O R X) :
    HilbertSameSideStep Geo R X cross := by
  have hXbase : HilbertIncidence.OnLine X base :=
    hilbert_collinear_on_line
      Geo O R X base hRX.1.symm
      hObase hRbase hRX.2.2.1
  have hLines : base ≠ cross := by
    intro h
    subst cross
    exact hCbase hCcross
  have hRcross : ¬ HilbertIncidence.OnLine R cross := by
    intro hRcross
    have hEq : base = cross :=
      HilbertPlaneIncidence.line_unique
        O R hRX.1.symm base cross
        hObase hRbase hOcross hRcross
    exact hLines hEq
  have hXcross : ¬ HilbertIncidence.OnLine X cross := by
    intro hXcross
    have hEq : base = cross :=
      HilbertPlaneIncidence.line_unique
        O X hRX.2.1.symm base cross
        hObase hXbase hOcross hXcross
    exact hLines hEq
  have hNotBetween : ¬ Geo.Between R O X := hRX.2.2.2
  exact
    ⟨hRcross, hXcross,
      hilbert_segment_not_meets_crossing_line
        Geo R X O base cross hLines
        hRbase hXbase hObase hOcross hNotBetween⟩

theorem hilbert_sameRay_points_sameSide
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O R X Y C : Geo.Point)
    (base cross : Geo.Line)
    (hObase : HilbertIncidence.OnLine O base)
    (hRbase : HilbertIncidence.OnLine R base)
    (hOcross : HilbertIncidence.OnLine O cross)
    (hCcross : HilbertIncidence.OnLine C cross)
    (hCbase : ¬ HilbertIncidence.OnLine C base)
    (hRX : HilbertSameRay Geo O R X)
    (hRY : HilbertSameRay Geo O R Y) :
    HilbertSameSide Geo X Y cross := by
  have hStepRX :=
    hilbert_sameRay_sameSideStep
      Geo O R X C base cross
      hObase hRbase hOcross hCcross hCbase hRX
  have hStepRY :=
    hilbert_sameRay_sameSideStep
      Geo O R Y C base cross
      hObase hRbase hOcross hCcross hCbase hRY
  have hStepXR : HilbertSameSideStep Geo X R cross :=
    ⟨hStepRX.2.1, hStepRX.1, fun hMeet =>
      hStepRX.2.2
        ⟨hMeet.choose,
          (HilbertOrder.between_incidence
            X hMeet.choose R hMeet.choose_spec.1).2.2.2.2,
          hMeet.choose_spec.2⟩⟩
  exact
    ⟨hStepRX.2.1, hStepRY.2.1,
      (Relation.ReflTransGen.single
        (r := fun U V => HilbertSameSideStep Geo U V cross)
        hStepXR).trans
        (Relation.ReflTransGen.single
          (r := fun U V => HilbertSameSideStep Geo U V cross)
          hStepRY)⟩

theorem hilbert_sameSide_refl
    [HilbertIncidence Geo]
    (P : Geo.Point)
    (l : Geo.Line)
    (hPl : ¬ HilbertIncidence.OnLine P l) :
    HilbertSameSide Geo P P l :=
  ⟨hPl, hPl, Relation.ReflTransGen.refl⟩

theorem hilbert_sameSide_symm
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (P Q : Geo.Point)
    (l : Geo.Line) :
    HilbertSameSide Geo P Q l →
    HilbertSameSide Geo Q P l := by
  rintro ⟨hPl, hQl, hPath⟩
  have hSwap :
      Relation.ReflTransGen
        (Function.swap
          (fun X Y => HilbertSameSideStep Geo X Y l)) Q P :=
    Relation.ReflTransGen.swap Q P hPath
  have hPath' :
      Relation.ReflTransGen
        (fun X Y => HilbertSameSideStep Geo X Y l) Q P :=
    (Relation.ReflTransGen.mono
      (r := Function.swap
        (fun X Y => HilbertSameSideStep Geo X Y l))
      (p := fun X Y => HilbertSameSideStep Geo X Y l)
      (fun X Y hStep =>
        ⟨hStep.2.1, hStep.1, fun hMeet =>
          hStep.2.2
            ⟨hMeet.choose,
              (HilbertOrder.between_incidence
                X hMeet.choose Y hMeet.choose_spec.1).2.2.2.2,
              hMeet.choose_spec.2⟩⟩)) Q P hSwap
  exact ⟨hQl, hPl, hPath'⟩

theorem hilbert_sameRay_ray_eq
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O P Q : Geo.Point) :
    HilbertSameRay Geo O P Q →
    Geo.ray O P = Geo.ray O Q := by
  intro h
  have hStep : Geo.SameDirectionStep O P Q := by
    by_cases hPQ : P = Q
    · exact ⟨h.1, h.2.1, Or.inl hPQ⟩
    · rcases hilbert_between_trichotomy
          Geo O P Q h.1.symm hPQ h.2.1.symm h.2.2.1 with
        hOPQ | hPOQ | hOQP
      · exact ⟨h.1, h.2.1, Or.inr (Or.inl hOPQ)⟩
      · exact False.elim (h.2.2.2 hPOQ)
      · exact ⟨h.1, h.2.1, Or.inr (Or.inr hOQP)⟩
  exact
    Geo.ray_eq_of_sameDirectionStep O P Q hStep

theorem hilbert_angle_eq_of_sameRay_first
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O A A' B : Geo.Point)
    (hAA' : HilbertSameRay Geo O A A') :
    Geo.Angle A O B = Geo.Angle A' O B := by
  unfold Geometry.Geo.Angle
  rw [hilbert_sameRay_ray_eq Geo O A A' hAA']

theorem hilbert_angle_eq_of_sameRay_second
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (O A B B' : Geo.Point)
    (hBB' : HilbertSameRay Geo O B B') :
    Geo.Angle A O B = Geo.Angle A O B' := by
  unfold Geometry.Geo.Angle
  rw [hilbert_sameRay_ray_eq Geo O B B' hBB']

theorem hilbert_congruent_reflexive
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B : Geo.Point) :
    Geo.Congruent A B A B := by
  rcases HilbertPlaneIncidence.two_points_on_line (Geo := Geo) with
    ⟨_, O, R, hOR, _, _⟩
  rcases HilbertCongruence.segment_construction
      (Geo := Geo) A B O R hOR with
    ⟨X, _, hX⟩
  exact
    HilbertCongruence.segment_congruence_common
      (Geo := Geo) O X A B A B hX hX

theorem hilbert_congruent_symmetry
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B C D : Geo.Point) :
    Geo.Congruent A B C D →
    Geo.Congruent C D A B := by
  intro h
  exact
    HilbertCongruence.segment_congruence_common
      (Geo := Geo) A B C D A B h
      (hilbert_congruent_reflexive Geo A B)

theorem hilbert_congruent_transitivity
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B C D E F : Geo.Point) :
    Geo.Congruent A B C D →
    Geo.Congruent C D E F →
    Geo.Congruent A B E F := by
  intro h₁ h₂
  exact
    HilbertCongruence.segment_congruence_common
      (Geo := Geo) C D A B E F
      (hilbert_congruent_symmetry Geo A B C D h₁)
      h₂

/--
Uniqueness of Hilbert's segment construction on a prescribed ray.
This is the auxiliary result used in the proof of Theorem 12.
-/
theorem hilbert_segment_construction_unique
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B O R X Y : Geo.Point)
    (hRX : HilbertSameRay Geo O R X)
    (hRY : HilbertSameRay Geo O R Y)
    (hOX : Geo.Congruent O X A B)
    (hOY : Geo.Congruent O Y A B) :
    X = Y := by
  rcases HilbertPlaneIncidence.line_through O R hRX.1.symm with
    ⟨base, hObase, hRbase⟩
  rcases hilbert_point_off_line Geo base with ⟨C, hCbase⟩
  have hOC : O ≠ C := by
    intro h
    subst C
    exact hCbase hObase
  rcases HilbertPlaneIncidence.line_through O C hOC with
    ⟨cross, hOcross, hCcross⟩
  have hSideXY :=
    hilbert_sameRay_points_sameSide
      Geo O R X Y C base cross
      hObase hRbase hOcross hCcross hCbase hRX hRY
  have hXbase : HilbertIncidence.OnLine X base :=
    hilbert_collinear_on_line
      Geo O R X base hRX.1.symm
      hObase hRbase hRX.2.2.1
  have hYbase : HilbertIncidence.OnLine Y base :=
    hilbert_collinear_on_line
      Geo O R Y base hRY.1.symm
      hObase hRbase hRY.2.2.1
  have hOCX : ¬ PrimCollinear Geo O C X :=
    hilbert_not_collinear_of_off_line
      Geo O C X cross hOC hOcross hCcross hSideXY.1
  have hOCY : ¬ PrimCollinear Geo O C Y :=
    hilbert_not_collinear_of_off_line
      Geo O C Y cross hOC hOcross hCcross hSideXY.2.1
  have hOCOC := hilbert_congruent_reflexive Geo O C
  have hOXOY :
      Geo.Congruent O X O Y :=
    HilbertCongruence.segment_congruence_common
      (Geo := Geo) A B O X O Y
      (hilbert_congruent_symmetry Geo O X A B hOX)
      (hilbert_congruent_symmetry Geo O Y A B hOY)
  have hRayXY : Geo.ray O X = Geo.ray O Y := by
    calc
      Geo.ray O X = Geo.ray O R :=
        (hilbert_sameRay_ray_eq Geo O R X hRX).symm
      _ = Geo.ray O Y :=
        hilbert_sameRay_ray_eq Geo O R Y hRY
  have hAngleObject :
      Geo.Angle C O X = Geo.Angle C O Y := by
    unfold Geometry.Geo.Angle
    rw [hRayXY]
  have hAngleRefl :
      Geo.AngleCongruent C O X C O X :=
    HilbertCongruence.angle_congruence_reflexive
      (Geo := Geo) C O X
      (fun h => hOCX (PrimCollinearSwap Geo C O X h))
  have hAngleO :
      Geo.AngleCongruent C O X C O Y := by
    unfold Geometry.Geo.AngleCongruent at hAngleRefl ⊢
    rw [← hAngleObject]
    exact hAngleRefl
  have hAngleC :
      Geo.AngleCongruent O C X O C Y :=
    HilbertCongruence.sas
      (Geo := Geo) O C X O C Y
      hOCX hOCY hOCOC hOXOY hAngleO
  rcases HilbertCongruence.angle_construction
      (Geo := Geo) O C X O C X hOCX hOC
      cross hOcross hCcross hSideXY.1 with
    ⟨Z, hZX, hAngleZ, hUnique⟩
  have hXX : HilbertSameSide Geo X X cross :=
    hilbert_sameSide_refl Geo X cross hSideXY.1
  have hZXRay : HilbertSameRay Geo C Z X :=
    hUnique X hXX
      (HilbertCongruence.angle_congruence_reflexive
        (Geo := Geo) O C X hOCX)
  have hYX : HilbertSameSide Geo Y X cross :=
    hilbert_sameSide_symm Geo X Y cross hSideXY
  have hZYRay : HilbertSameRay Geo C Z Y :=
    hUnique Y hYX hAngleC
  by_contra hXY
  rcases hZXRay.2.2.1 with ⟨l, hCl, hZl, hXl⟩
  rcases hZYRay.2.2.1 with ⟨m, hCm, hZm, hYm⟩
  have hlm : l = m :=
    HilbertPlaneIncidence.line_unique
      C Z hZXRay.1.symm l m hCl hZl hCm hZm
  subst m
  have hBaseL : base = l :=
    HilbertPlaneIncidence.line_unique
      X Y hXY base l hXbase hYbase hXl hYm
  rw [← hBaseL] at hCl
  exact hCbase hCl

/--
The angle part of Hilbert's Theorem 12.

Under the two-side-and-included-angle hypotheses, Axiom III, 5 gives
the congruence of each of the two remaining angles. The congruence of
the third side requires the separate uniqueness-of-segment-construction
argument used in the full theorem.
-/
theorem hilbert_sas_remaining_angles
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B C A' B' C' : Geo.Point)
    (hABC : ¬ PrimCollinear Geo A B C)
    (hA'B'C' : ¬ PrimCollinear Geo A' B' C')
    (hAB : Geo.Congruent A B A' B')
    (hAC : Geo.Congruent A C A' C')
    (hAngleA : Geo.AngleCongruent B A C B' A' C') :
    Geo.AngleCongruent A B C A' B' C' ∧
    Geo.AngleCongruent A C B A' C' B' := by
  constructor
  · exact
      HilbertCongruence.sas
        (Geo := Geo)
        A B C A' B' C'
        hABC hA'B'C' hAB hAC hAngleA
  · exact
      HilbertCongruence.sas
        (Geo := Geo)
        A C B A' C' B'
        (fun h => hABC (PrimCollinearRotate Geo A C B h))
        (fun h => hA'B'C' (PrimCollinearRotate Geo A' C' B' h))
        hAC hAB
        ((Geo.angle_congruent_reverse_second
          C A B B' A' C').mp
          ((Geo.angle_congruent_reverse_first
            B A C B' A' C').mp hAngleA))

/--
The minimal part of Hilbert's Theorem 12 needed by the midsegment
development and by Theorem 14: the third side and the angle at `C`.
-/
theorem hilbert_sas_third_side_and_angle
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B C A' B' C' : Geo.Point)
    (hABC : ¬ PrimCollinear Geo A B C)
    (hA'B'C' : ¬ PrimCollinear Geo A' B' C')
    (hAB : Geo.Congruent A B A' B')
    (hAC : Geo.Congruent A C A' C')
    (hAngleA : Geo.AngleCongruent B A C B' A' C') :
    Geo.Congruent B C B' C' ∧
    Geo.AngleCongruent A C B A' C' B' := by
  have hAngles :=
    hilbert_sas_remaining_angles
      Geo A B C A' B' C'
      hABC hA'B'C' hAB hAC hAngleA
  have hB'C'A' : ¬ PrimCollinear Geo B' C' A' :=
    fun h =>
      hA'B'C'
        (PrimCollinearCycle Geo C' A' B'
          (PrimCollinearCycle Geo B' C' A' h))
  have hB'C' : B' ≠ C' :=
    hilbert_noncollinear_ne_first Geo B' C' A' hB'C'A'
  rcases HilbertCongruence.segment_construction
      (Geo := Geo) B C B' C' hB'C' with
    ⟨X, hRay, hBCX⟩
  have hB'X : B' ≠ X := hRay.2.1.symm
  rcases HilbertPlaneIncidence.line_through B' C' hB'C' with
    ⟨base, hB'base, hC'base⟩
  have hXbase : HilbertIncidence.OnLine X base :=
    hilbert_collinear_on_line
      Geo B' C' X base hB'C'
      hB'base hC'base hRay.2.2.1
  have hA'base : ¬ HilbertIncidence.OnLine A' base := by
    intro h
    exact hA'B'C' ⟨base, h, hB'base, hC'base⟩
  have hA'B' : A' ≠ B' :=
    hilbert_noncollinear_ne_first Geo A' B' C' hA'B'C'
  rcases HilbertPlaneIncidence.line_through A' B' hA'B' with
    ⟨cross, hA'cross, hB'cross⟩
  have hSideXC' :=
    hilbert_sameRay_points_sameSide
      Geo B' C' X C' A' base cross
      hB'base hC'base hB'cross hA'cross hA'base
      hRay (hilbert_sameRay_refl Geo B' C' hB'C'.symm)
  have hA'B'X : ¬ PrimCollinear Geo A' B' X :=
    fun h =>
      (hilbert_not_collinear_of_off_line
        Geo B' X A' base hB'X hB'base hXbase hA'base)
        (PrimCollinearCycle Geo A' B' X h)
  have hTargetAngle :
      Geo.Angle A' B' C' = Geo.Angle A' B' X := by
    exact hilbert_angle_eq_of_sameRay_second Geo B' A' C' X hRay
  have hAngleB :
      Geo.AngleCongruent A B C A' B' X := by
    unfold Geometry.Geo.AngleCongruent at hAngles ⊢
    rw [← hTargetAngle]
    exact hAngles.1
  have hAngleAX :
      Geo.AngleCongruent B A C B' A' X :=
    HilbertCongruence.sas
      (Geo := Geo) B A C B' A' X
      (fun h => hABC (PrimCollinearSwap Geo B A C h))
      (fun h => hA'B'X (PrimCollinearSwap Geo B' A' X h))
      ((Geo.congruent_reverse_second B A A' B').mp
        ((Geo.congruent_reverse_first A B A' B').mp hAB))
      (hilbert_congruent_symmetry Geo B' X B C hBCX)
      hAngleB
  rcases HilbertCongruence.angle_construction
      (Geo := Geo) B A C B' A' C'
      (fun h => hABC (PrimCollinearSwap Geo B A C h))
      hA'B'.symm cross hB'cross hA'cross hSideXC'.2.1 with
    ⟨Z, hZC', hAngleZ, hUnique⟩
  have hC'C' :=
    hilbert_sameSide_refl Geo C' cross hSideXC'.2.1
  have hZC'Ray : HilbertSameRay Geo A' Z C' :=
    hUnique C' hC'C' hAngleA
  have hXC' : HilbertSameSide Geo X C' cross := hSideXC'
  have hZXRay : HilbertSameRay Geo A' Z X :=
    hUnique X hXC' hAngleAX
  have hZXcol := hZXRay.2.2.1
  have hZC'col := hZC'Ray.2.2.1
  have hXC' : X = C' := by
    by_contra hNe
    rcases hZXcol with ⟨l, hA'l, hZl, hXl⟩
    rcases hZC'col with ⟨m, hA'm, hZm, hC'm⟩
    have hlm : l = m :=
      HilbertPlaneIncidence.line_unique
        A' Z hZXRay.1.symm l m hA'l hZl hA'm hZm
    subst m
    have hBaseL : base = l :=
      HilbertPlaneIncidence.line_unique
        X C' hNe base l hXbase hC'base hXl hC'm
    rw [← hBaseL] at hA'l
    exact hA'base hA'l
  subst X
  exact
    ⟨hilbert_congruent_symmetry Geo B' C' B C hBCX,
      hAngles.2⟩

/--
Noncollinearity is preserved when both sides of an angle are replaced
by representatives of the same Hilbert rays.
-/
theorem hilbert_noncollinear_of_sameRays
    [HilbertIncidence Geo]
    [HilbertOrder Geo]
    (A O B X Y : Geo.Point)
    (hAOB : ¬ PrimCollinear Geo A O B)
    (hAX : HilbertSameRay Geo O A X)
    (hBY : HilbertSameRay Geo O B Y) :
    ¬ PrimCollinear Geo X O Y := by
  intro hXOY
  have hAOX : PrimCollinear Geo A O X :=
    PrimCollinearRotate Geo A X O
      (PrimCollinearCycle Geo O A X hAX.2.2.1)
  have hOXY : PrimCollinear Geo O X Y :=
    PrimCollinearSwap Geo X O Y hXOY
  have hAOY : PrimCollinear Geo A O Y :=
    hilbert_primCollinear_trans
      Geo A O X Y hAX.2.1.symm hAOX hOXY
  have hOYB : PrimCollinear Geo O Y B :=
    PrimCollinearRotate Geo O B Y hBY.2.2.1
  exact
    hAOB
      (hilbert_primCollinear_trans
        Geo A O Y B hBY.2.1.symm hAOY hOYB)

/--
Hilbert's Theorem 14: angles adjacent to congruent angles are
congruent.  The hypotheses explicitly exhibit the two linear pairs.

The proof constructs three points on the rays of the first angle,
uses Theorem 12 twice, additivity III.3 once, and finally SAS III.5.
-/
theorem hilbert_adjacent_angles_congruent
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A O B C A' O' B' C' : Geo.Point)
    (hAOC : Geo.Between A O C)
    (hA'O'C' : Geo.Between A' O' C')
    (hAOB : ¬ PrimCollinear Geo A O B)
    (hA'O'B' : ¬ PrimCollinear Geo A' O' B')
    (hAngle : Geo.AngleCongruent A O B A' O' B') :
    Geo.AngleCongruent B O C B' O' C' := by
  have hAOCData := HilbertOrder.between_incidence A O C hAOC
  have hA'O'C'Data :=
    HilbertOrder.between_incidence A' O' C' hA'O'C'
  have hOA : O ≠ A := hAOCData.1.symm
  have hOC : O ≠ C := hAOCData.2.1
  have hOB : O ≠ B := by
    have hBOA : ¬ PrimCollinear Geo B O A := by
      intro h
      exact
        hAOB
          (PrimCollinearRotate Geo A B O
            (PrimCollinearCycle Geo
              O A B (PrimCollinearCycle Geo B O A h)))
    exact
      (hilbert_noncollinear_ne_first Geo B O A hBOA).symm
  rcases HilbertCongruence.segment_construction
      (Geo := Geo) O' A' O A hOA with
    ⟨X, hAX, hOX⟩
  rcases HilbertCongruence.segment_construction
      (Geo := Geo) O' B' O B hOB with
    ⟨Y, hBY, hOY⟩
  rcases HilbertCongruence.segment_construction
      (Geo := Geo) O' C' O C hOC with
    ⟨Z, hCZ, hOZ⟩
  have hXOY : ¬ PrimCollinear Geo X O Y :=
    hilbert_noncollinear_of_sameRays
      Geo A O B X Y hAOB hAX hBY
  have hAngleLeft :
      Geo.Angle A O B = Geo.Angle X O Y := by
    calc
      Geo.Angle A O B = Geo.Angle X O B :=
        hilbert_angle_eq_of_sameRay_first Geo O A X B hAX
      _ = Geo.Angle X O Y :=
        hilbert_angle_eq_of_sameRay_second Geo O X B Y hBY
  have hAngleXOY :
      Geo.AngleCongruent X O Y A' O' B' := by
    unfold Geometry.Geo.AngleCongruent at hAngle ⊢
    rw [← hAngleLeft]
    exact hAngle
  have hFirstAngles :=
    hilbert_sas_remaining_angles
      Geo O X Y O' A' B'
      (fun h => hXOY (PrimCollinearSwap Geo O X Y h))
      (fun h => hA'O'B' (PrimCollinearSwap Geo O' A' B' h))
      hOX hOY hAngleXOY
  have hFirstSide :=
    (hilbert_sas_third_side_and_angle
      Geo O X Y O' A' B'
      (fun h => hXOY (PrimCollinearSwap Geo O X Y h))
      (fun h => hA'O'B' (PrimCollinearSwap Geo O' A' B' h))
      hOX hOY hAngleXOY).1
  have hXOZ : Geo.Between X O Z :=
    hilbert_between_transport_sameRays
      Geo A O C X Z hAOC hAX hCZ
  have hXO : Geo.Congruent X O A' O' :=
    (Geo.congruent_reverse_second
      X O O' A').mp
      ((Geo.congruent_reverse_first
        O X O' A').mp hOX)
  have hXZ : Geo.Congruent X Z A' C' :=
    HilbertCongruence.segment_additivity
      (Geo := Geo) X O Z A' O' C'
      hXOZ hA'O'C' hXO hOZ
  have hRayXOZ : HilbertSameRay Geo X O Z :=
    hilbert_sameRay_of_between Geo X O Z hXOZ
  have hRayA'O'C' : HilbertSameRay Geo A' O' C' :=
    hilbert_sameRay_of_between Geo A' O' C' hA'O'C'
  have hAtXLeft :
      Geo.Angle O X Y = Geo.Angle Y X Z := by
    calc
      Geo.Angle O X Y = Geo.Angle Y X O :=
        Geo.angle_swap O X Y
      _ = Geo.Angle Y X Z :=
        hilbert_angle_eq_of_sameRay_second
          Geo X Y O Z hRayXOZ
  have hAtXRight :
      Geo.Angle O' A' B' = Geo.Angle B' A' C' := by
    calc
      Geo.Angle O' A' B' = Geo.Angle B' A' O' :=
        Geo.angle_swap O' A' B'
      _ = Geo.Angle B' A' C' :=
        hilbert_angle_eq_of_sameRay_second
          Geo A' B' O' C' hRayA'O'C'
  have hAngleXYZ :
      Geo.AngleCongruent Y X Z B' A' C' := by
    unfold Geometry.Geo.AngleCongruent at hFirstAngles ⊢
    rw [← hAtXLeft, ← hAtXRight]
    exact hFirstAngles.1
  have hXYZ : ¬ PrimCollinear Geo X Y Z := by
    intro h
    have hOXZ :=
      (HilbertOrder.between_incidence X O Z hXOZ).2.2.2.1
    have hXZY := PrimCollinearRotate Geo X Y Z h
    have hOXY :=
      hilbert_primCollinear_trans
        Geo O X Z Y
        (HilbertOrder.between_incidence X O Z hXOZ).2.2.1
        (PrimCollinearSwap Geo X O Z hOXZ)
        hXZY
    exact hXOY (PrimCollinearSwap Geo O X Y hOXY)
  have hA'B'C' : ¬ PrimCollinear Geo A' B' C' := by
    intro h
    have hO'A'C' :=
      PrimCollinearSwap Geo A' O' C'
        hA'O'C'Data.2.2.2.1
    have hA'C'B' := PrimCollinearRotate Geo A' B' C' h
    have hO'A'B' :=
      hilbert_primCollinear_trans
        Geo O' A' C' B'
        hA'O'C'Data.2.2.1
        hO'A'C' hA'C'B'
    exact hA'O'B' (PrimCollinearSwap Geo O' A' B' hO'A'B')
  have hSecond :=
    hilbert_sas_third_side_and_angle
      Geo X Y Z A' B' C'
      hXYZ hA'B'C' hFirstSide hXZ hAngleXYZ
  have hZOX : Geo.Between Z O X :=
    (HilbertOrder.between_incidence X O Z hXOZ).2.2.2.2
  have hRayZOX : HilbertSameRay Geo Z O X :=
    hilbert_sameRay_of_between Geo Z O X hZOX
  have hC'O'A' : Geo.Between C' O' A' :=
    hA'O'C'Data.2.2.2.2
  have hRayC'O'A' : HilbertSameRay Geo C' O' A' :=
    hilbert_sameRay_of_between Geo C' O' A' hC'O'A'
  have hAngleZOY :
      Geo.AngleCongruent O Z Y O' C' B' := by
    have hLeft :=
      hilbert_angle_eq_of_sameRay_first
        Geo Z O X Y hRayZOX
    have hRight :=
      hilbert_angle_eq_of_sameRay_first
        Geo C' O' A' B' hRayC'O'A'
    unfold Geometry.Geo.AngleCongruent at hSecond ⊢
    rw [hLeft, hRight]
    exact hSecond.2
  have hZO : Geo.Congruent Z O C' O' :=
    (Geo.congruent_reverse_second
      Z O O' C').mp
      ((Geo.congruent_reverse_first
        O Z O' C').mp hOZ)
  have hZY : Geo.Congruent Z Y C' B' :=
    (Geo.congruent_reverse_second
      Z Y B' C').mp
      ((Geo.congruent_reverse_first
        Y Z B' C').mp hSecond.1)
  have hZOY : ¬ PrimCollinear Geo Z O Y := by
    intro h
    have hXOZCol :=
      (HilbertOrder.between_incidence X O Z hXOZ).2.2.2.1
    exact
      hXOY
        (hilbert_primCollinear_trans
          Geo X O Z Y
          (HilbertOrder.between_incidence X O Z hXOZ).2.1
          hXOZCol
          (PrimCollinearSwap Geo Z O Y h))
  have hC'O'B' : ¬ PrimCollinear Geo C' O' B' := by
    intro h
    have hO'C'B' := PrimCollinearSwap Geo C' O' B' h
    exact
      hA'O'B'
        (hilbert_primCollinear_trans
          Geo A' O' C' B'
          hA'O'C'Data.2.1
          hA'O'C'Data.2.2.2.1 hO'C'B')
  have hFinal :
      Geo.AngleCongruent Z O Y C' O' B' :=
    HilbertCongruence.sas
      (Geo := Geo) Z O Y C' O' B'
      hZOY hC'O'B' hZO hZY hAngleZOY
  have hTargetLeft :
      Geo.Angle B O C = Geo.Angle Z O Y := by
    calc
      Geo.Angle B O C = Geo.Angle C O B :=
        Geo.angle_swap B O C
      _ = Geo.Angle Z O B :=
        hilbert_angle_eq_of_sameRay_first Geo O C Z B hCZ
      _ = Geo.Angle Z O Y :=
        hilbert_angle_eq_of_sameRay_second Geo O Z B Y hBY
  have hTargetRight :
      Geo.Angle B' O' C' = Geo.Angle C' O' B' :=
    Geo.angle_swap B' O' C'
  unfold Geometry.Geo.AngleCongruent at hFinal ⊢
  rw [hTargetLeft, hTargetRight]
  exact hFinal

/--
Vertical angles formed by two intersecting lines are congruent.
-/
theorem hilbert_vertical_angles
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (C E D B F : Geo.Point)
    (hCEB : Geo.Between C E B)
    (hDEF : Geo.Between D E F)
    (hCED : ¬ PrimCollinear Geo C E D) :
    Geo.AngleCongruent C E D B E F := by
  have hBEC : Geo.Between B E C :=
    (HilbertOrder.between_incidence C E B hCEB).2.2.2.2
  have hEB : E ≠ B :=
    (HilbertOrder.between_incidence C E B hCEB).2.1
  have hBED : ¬ PrimCollinear Geo B E D := by
    intro h
    have hEBD := PrimCollinearSwap Geo B E D h
    exact
      hCED
        (hilbert_primCollinear_trans
          Geo C E B D hEB
          (HilbertOrder.between_incidence
            C E B hCEB).2.2.2.1
          hEBD)
  have hDEB : ¬ PrimCollinear Geo D E B := by
    intro h
    exact
      hBED
        (PrimCollinearRotate Geo B D E
          (PrimCollinearCycle Geo
            E B D (PrimCollinearCycle Geo D E B h)))
  have hRefl :
      Geo.AngleCongruent B E D B E D :=
    HilbertCongruence.angle_congruence_reflexive
      (Geo := Geo) B E D hBED
  have hStart :
      Geo.AngleCongruent B E D D E B :=
    (Geo.angle_congruent_reverse_second
      B E D B E D).mp hRefl
  have hSupp :=
    hilbert_adjacent_angles_congruent
      Geo B E D C D E B F
      hBEC hDEF hBED hDEB hStart
  exact
    (Geo.angle_congruent_reverse_first
      D E C B E F).mp hSupp

/--
Extension beyond `B`, with the order information retained.
-/
theorem hilbert_extend_segment_beyond
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B : Geo.Point)
    (hAB : A ≠ B) :
    ∃ T : Geo.Point,
      Geo.Between A B T ∧
      Geo.Congruent A B B T := by
  rcases HilbertOrder.between_extension A B hAB with
    ⟨R, hABR⟩
  have hBR :=
    (HilbertOrder.between_incidence A B R hABR).2.1
  rcases HilbertCongruence.segment_construction
      (Geo := Geo) A B B R hBR with
    ⟨T, hRay, hCong⟩
  have hAA : HilbertSameRay Geo B A A :=
    hilbert_sameRay_refl Geo B A hAB
  have hABT :=
    hilbert_between_transport_sameRays
      Geo A B R A T hABR hAA hRay
  exact
    ⟨T, hABT,
      hilbert_congruent_symmetry Geo B T A B hCong⟩

theorem hilbert_extend_segment
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B : Geo.Point) :
    ∃ T : Geo.Point,
      PrimCollinear Geo A B T ∧
      Geo.Congruent A B B T := by
  by_cases hAB : A = B
  · subst A
    rcases HilbertPlaneIncidence.two_points_on_line (Geo := Geo) with
      ⟨_, O, R, hOR, _, _⟩
    by_cases hBO : B = O
    · subst O
      rcases HilbertCongruence.segment_construction
          (Geo := Geo) B B B R hOR with
        ⟨T, hRay, hCong⟩
      have hBT : B ≠ T := hRay.2.1.symm
      rcases HilbertPlaneIncidence.line_through B T hBT with
        ⟨l, hBl, hTl⟩
      refine ⟨T, ⟨l, hBl, hBl, hTl⟩, ?_⟩
      exact hilbert_congruent_symmetry Geo B T B B hCong
    · rcases HilbertCongruence.segment_construction
          (Geo := Geo) B B B O hBO with
        ⟨T, hRay, hCong⟩
      have hBT : B ≠ T := hRay.2.1.symm
      rcases HilbertPlaneIncidence.line_through B T hBT with
        ⟨l, hBl, hTl⟩
      refine ⟨T, ⟨l, hBl, hBl, hTl⟩, ?_⟩
      exact hilbert_congruent_symmetry Geo B T B B hCong
  · rcases HilbertOrder.between_extension A B hAB with
      ⟨R, hABR⟩
    have hBetweenData :=
      HilbertOrder.between_incidence A B R hABR
    have hBR : B ≠ R := hBetweenData.2.1
    have hABRCol : PrimCollinear Geo A B R :=
      hBetweenData.2.2.2.1
    rcases HilbertCongruence.segment_construction
        (Geo := Geo) A B B R hBR with
      ⟨T, hRay, hCong⟩
    have hBRT : PrimCollinear Geo B R T :=
      hilbert_sameRay_collinear Geo B R T hRay
    have hABT : PrimCollinear Geo A B T :=
      hilbert_primCollinear_trans Geo A B R T hBR hABRCol hBRT
    exact
      ⟨T, hABT,
        hilbert_congruent_symmetry Geo B T A B hCong⟩

theorem hilbert_extend_segment_distinct
    [HilbertIncidence Geo]
    [HilbertCongruence Geo]
    (A B : Geo.Point)
    (hAB : A ≠ B) :
    ∃ T : Geo.Point,
      PrimCollinear Geo A B T ∧
      Geo.Congruent A B B T ∧
      B ≠ T := by
  rcases HilbertOrder.between_extension A B hAB with
    ⟨R, hABR⟩
  have hBetweenData :=
    HilbertOrder.between_incidence A B R hABR
  have hBR : B ≠ R := hBetweenData.2.1
  have hABRCol : PrimCollinear Geo A B R :=
    hBetweenData.2.2.2.1
  rcases HilbertCongruence.segment_construction
      (Geo := Geo) A B B R hBR with
    ⟨T, hRay, hCong⟩
  have hBRT : PrimCollinear Geo B R T :=
    hilbert_sameRay_collinear Geo B R T hRay
  have hABT : PrimCollinear Geo A B T :=
    hilbert_primCollinear_trans Geo A B R T hBR hABRCol hBRT
  exact
    ⟨T, hABT,
      hilbert_congruent_symmetry Geo B T A B hCong,
      hRay.2.1.symm⟩

/-- Group IV, Hilbert's Euclidean axiom of parallels. -/
class HilbertEuclideanPlane (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop
    extends HilbertCongruence Geo where
  /--
  IV: through a point outside a line there is at most one line disjoint
  from the given line.
  -/
  parallel_unique :
    ∀ l : Geo.Line,
      ∀ A : Geo.Point,
        ¬ HilbertIncidence.OnLine A l →
        ∀ b c : Geo.Line,
          HilbertIncidence.OnLine A b →
          HilbertLinesDisjoint Geo b l →
          HilbertIncidence.OnLine A c →
          HilbertLinesDisjoint Geo c l →
          b = c

/--
A finite chain of copies of segment `CD`, beginning at `A`, along the
ray from `A` through `B`.
-/
def HilbertSegmentChain
    (Geo : Geometry.Geo)
    [HilbertIncidence Geo]
    (A B C D : Geo.Point)
    (n : Nat)
    (P : Fin (n + 2) → Geo.Point) : Prop :=
  P 0 = A ∧
  (∀ i : Fin (n + 1),
    Geo.Congruent (P i.castSucc) (P i.succ) C D) ∧
  (∀ i : Fin (n + 1),
    HilbertSameRay Geo A B (P i.succ))

/--
Group V, axiom V, 1: Hilbert's Archimedean axiom.

V, 2 (line completeness) is deliberately not folded into this class;
it requires a separate notion of extensions of ordered congruence
structures.
-/
class HilbertArchimedeanPlane (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop
    extends HilbertEuclideanPlane Geo where
  archimedes :
    ∀ A B C D : Geo.Point,
      A ≠ B →
      C ≠ D →
      ∃ n : Nat,
      ∃ P : Fin (n + 2) → Geo.Point,
        HilbertSegmentChain Geo A B C D n P ∧
        Geo.Between A B (P (Fin.last (n + 1)))
