import CGJteamLab.HilbertCore

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# Extracted Hilbert plane axioms

Working extraction from `HilbertPlaneTheory.lean`.
Only primitive/auxiliary definitions needed to state the axiom classes are kept here.
-/


/-!
# Primitive incidence language

This section introduces the primitive point-line incidence relation,
the derived notion of collinearity, and its elementary permutations.
-/

class HilbertIncidence where
  OnLine :
    Geo.Point → Geo.Line → Prop

def PrimCollinear
    [H : HilbertIncidence Geo]
    (A B C : Geo.Point) : Prop :=
  ∃ l : Geo.Line,
    H.OnLine A l ∧
    H.OnLine B l ∧
    H.OnLine C l


/-!
# Hilbert's plane axiom hierarchy

The following classes formalize the plane part of the five axiom groups
from the second English edition of Hilbert's *Foundations of Geometry*.
They preserve the small `HilbertIncidence` interface used by the existing
library and add stronger layers without changing `GeometryCore`.
The field documentation retains Hilbert's original group numbering.

The present `Geometry.Geo` has points and lines but no type of planes.
Consequently, the space incidence axioms I, 4-8 are intentionally not
encoded here. Axiom V, 2 is also deferred: Hilbert's line-completeness
axiom is a maximality statement about extensions of an entire ordered
congruence structure and requires a separate model-theoretic interface.
-/

/-!
## Derived line, ray, and separation notions

These definitions are built from incidence and betweenness. They are not
additional axioms.
-/

/-- Two Hilbert lines meet when they have a common point. -/
def HilbertLinesMeet
    [H : HilbertIncidence Geo]
    (l m : Geo.Line) : Prop :=
  ∃ P : Geo.Point, H.OnLine P l ∧ H.OnLine P m

/-- Two Hilbert lines are disjoint when they have no common point. -/
def HilbertLinesDisjoint
    [HilbertIncidence Geo]
    (l m : Geo.Line) : Prop :=
  ¬ HilbertLinesMeet Geo l m

/--
`P` and `Q` lie on the same ray from `O`. Betweenness is the primitive
relation inherited from `GeometryCore`.
-/
def HilbertSameRay
    [HilbertIncidence Geo]
    (O P Q : Geo.Point) : Prop :=
  P ≠ O ∧
  Q ≠ O ∧
  PrimCollinear Geo O P Q ∧
  ¬ Geo.Between P O Q

/-- The open segment `AB` meets the line `l`. -/
def HilbertSegmentMeetsLine
    [H : HilbertIncidence Geo]
    (A B : Geo.Point)
    (l : Geo.Line) : Prop :=
  ∃ X : Geo.Point, Geo.Between A X B ∧ H.OnLine X l

/--
One elementary connection between two points avoiding a line.
-/
def HilbertSameSideStep
    [H : HilbertIncidence Geo]
    (P Q : Geo.Point)
    (l : Geo.Line) : Prop :=
  ¬ H.OnLine P l ∧
  ¬ H.OnLine Q l ∧
  ¬ HilbertSegmentMeetsLine Geo P Q l

/--
Two points are on the same side of a line when they belong to the same
region of its complement. A region is represented by the finite
connectivity generated by segments that avoid the line.
-/
def HilbertSameSide
    [H : HilbertIncidence Geo]
    (P Q : Geo.Point)
    (l : Geo.Line) : Prop :=
  ¬ H.OnLine P l ∧
  ¬ H.OnLine Q l ∧
  Relation.ReflTransGen
    (fun X Y => HilbertSameSideStep Geo X Y l) P Q


/-!
## Hilbert axiom classes

The following classes encode the plane incidence, order, congruence,
parallel, and continuity layers of the Hilbert system.
-/

/--
Group I, axioms I, 1-3 for plane incidence.

The distinctness assumptions make explicit Hilbert's convention that
letters denoting two or more points or lines denote distinct objects.
-/
class HilbertPlaneIncidence (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop where
  /-- I, 1: two distinct points lie on a line. -/
  line_through :
    ∀ A B : Geo.Point,
      A ≠ B →
      ∃ l : Geo.Line,
        HilbertIncidence.OnLine A l ∧
        HilbertIncidence.OnLine B l

  /-- I, 2: two distinct points determine at most one line. -/
  line_unique :
    ∀ A B : Geo.Point,
      A ≠ B →
      ∀ l m : Geo.Line,
        HilbertIncidence.OnLine A l →
        HilbertIncidence.OnLine B l →
        HilbertIncidence.OnLine A m →
        HilbertIncidence.OnLine B m →
        l = m

  /-- First clause of I, 3: two distinct points exist on a line. -/
  two_points_on_line :
    ∃ l : Geo.Line,
      ∃ A B : Geo.Point,
        A ≠ B ∧
        HilbertIncidence.OnLine A l ∧
        HilbertIncidence.OnLine B l

  /-- Second clause of I, 3: three noncollinear points exist. -/
  three_noncollinear :
    ∃ A B C : Geo.Point,
      ¬ PrimCollinear Geo A B C

/-- Group II, axioms II, 1-4 of order. -/
class HilbertOrder (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop
    extends HilbertPlaneIncidence Geo where
  /--
  II, 1: betweenness implies three distinct collinear points and is
  symmetric in the endpoints.
  -/
  between_incidence :
    ∀ A B C : Geo.Point,
      Geo.Between A B C →
      A ≠ B ∧
      B ≠ C ∧
      A ≠ C ∧
      PrimCollinear Geo A B C ∧
      Geo.Between C B A

  /-- II, 2: a segment can be extended beyond either endpoint. -/
  between_extension :
    ∀ A C : Geo.Point,
      A ≠ C →
      ∃ B : Geo.Point,
        Geo.Between A C B

  /--
  II, 3: among three collinear points, no more than one lies between
  the other two.
  -/
  between_unique :
    ∀ A B C : Geo.Point,
      PrimCollinear Geo A B C →
      Geo.Between A B C →
      ¬ Geo.Between B A C ∧
      ¬ Geo.Between A C B

  /--
  II, 4: Pasch's plane axiom. A line entering a triangle through one
  side leaves it through one of the other two sides.
  -/
  pasch :
    ∀ A B C : Geo.Point,
      ¬ PrimCollinear Geo A B C →
      ∀ l : Geo.Line,
        ¬ HilbertIncidence.OnLine A l →
        ¬ HilbertIncidence.OnLine B l →
        ¬ HilbertIncidence.OnLine C l →
        HilbertSegmentMeetsLine Geo A B l →
        HilbertSegmentMeetsLine Geo A C l ∨
        HilbertSegmentMeetsLine Geo B C l

/-- Group III, axioms III, 1-5 of congruence. -/
class HilbertCongruence (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop
    extends HilbertOrder Geo where
  /-- III, 1: a segment can be laid off on a prescribed ray. -/
  segment_construction :
    ∀ A B O R : Geo.Point,
      O ≠ R →
      ∃ X : Geo.Point,
        HilbertSameRay Geo O R X ∧
        Geo.Congruent O X A B

  /--
  III, 2: two segments congruent to the same segment are congruent to
  each other.
  -/
  segment_congruence_common :
    ∀ A B A' B' A'' B'' : Geo.Point,
      Geo.Congruent A B A' B' →
      Geo.Congruent A B A'' B'' →
      Geo.Congruent A' B' A'' B''

  /-- III, 3: additivity of adjacent congruent segments. -/
  segment_additivity :
    ∀ A B C A' B' C' : Geo.Point,
      Geo.Between A B C →
      Geo.Between A' B' C' →
      Geo.Congruent A B A' B' →
      Geo.Congruent B C B' C' →
      Geo.Congruent A C A' C'

  /--
  III, 4: an angle can be constructed uniquely on a prescribed side
  of a prescribed ray. Uniqueness is uniqueness of the resulting ray.
  -/
  angle_construction :
    ∀ A B C A' B' S : Geo.Point,
      ¬ PrimCollinear Geo A B C →
      A' ≠ B' →
      ∀ l : Geo.Line,
        HilbertIncidence.OnLine A' l →
        HilbertIncidence.OnLine B' l →
        ¬ HilbertIncidence.OnLine S l →
        ∃ C' : Geo.Point,
          HilbertSameSide Geo C' S l ∧
          Geo.AngleCongruent A B C A' B' C' ∧
          ∀ D' : Geo.Point,
            HilbertSameSide Geo D' S l →
            Geo.AngleCongruent A B C A' B' D' →
            HilbertSameRay Geo B' C' D'

  /--
  The reflexivity clause stated with III, 4: every (nondegenerate)
  angle is congruent to itself.
  -/
  angle_congruence_reflexive :
    ∀ A B C : Geo.Point,
      ¬ PrimCollinear Geo A B C →
      Geo.AngleCongruent A B C A B C

  /--
  III, 5: Hilbert's SAS axiom, stated in its original angle-conclusion
  form.
  -/
  sas :
    ∀ A B C A' B' C' : Geo.Point,
      ¬ PrimCollinear Geo A B C →
      ¬ PrimCollinear Geo A' B' C' →
      Geo.Congruent A B A' B' →
      Geo.Congruent A C A' C' →
      Geo.AngleCongruent B A C B' A' C' →
      Geo.AngleCongruent A B C A' B' C'


/-!
## Euclidean parallel axiom and converse theorems
-/

/-- Group IV, Hilbert's Euclidean axiom of parallels. -/
class HilbertEuclideanPlane (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop
    extends HilbertCongruence Geo where
  /--
  IV: through a point outside a line there is at most one line disjoint
  from the given line.
  -/
  parallel_unique :
    ∀ l : Geo.Line,
      ∀ A : Geo.Point,
        ¬ HilbertIncidence.OnLine A l →
        ∀ b c : Geo.Line,
          HilbertIncidence.OnLine A b →
          HilbertLinesDisjoint Geo b l →
          HilbertIncidence.OnLine A c →
          HilbertLinesDisjoint Geo c l →
          b = c

/-!
## Archimedean continuity layer
-/

/--
A finite chain of copies of segment `CD`, beginning at `A`, along the
ray from `A` through `B`.
-/
def HilbertSegmentChain
    (Geo : Geometry.Geo)
    [HilbertIncidence Geo]
    (A B C D : Geo.Point)
    (n : Nat)
    (P : Fin (n + 2) → Geo.Point) : Prop :=
  P 0 = A ∧
  (∀ i : Fin (n + 1),
    Geo.Congruent (P i.castSucc) (P i.succ) C D) ∧
  (∀ i : Fin (n + 1),
    HilbertSameRay Geo A B (P i.succ))

/--
Group V, axiom V, 1: Hilbert's Archimedean axiom.

V, 2 (line completeness) is deliberately not folded into this class;
it requires a separate notion of extensions of ordered congruence
structures.
-/
class HilbertArchimedeanPlane (Geo : Geometry.Geo)
    [HilbertIncidence Geo] : Prop
    extends HilbertEuclideanPlane Geo where
  archimedes :
    ∀ A B C D : Geo.Point,
      A ≠ B →
      C ≠ D →
      ∃ n : Nat,
      ∃ P : Fin (n + 2) → Geo.Point,
        HilbertSegmentChain Geo A B C D n P ∧
        Geo.Between A B (P (Fin.last (n + 1)))
