import CGJteamLab.HilbertInterface
import Mathlib.Data.Multiset.AddSub

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/--
A triangle as an unordered multiset of its three vertices.

This is intentionally only a formal triangle term.
No geometric region or interior is represented here.
-/
abbrev HilbertTriangleTerm :=
  Multiset Geo.Point

/--
A formal finite sum of triangle terms.
-/
abbrev HilbertScissorsTerm :=
  Multiset (HilbertTriangleTerm Geo)

/--
The formal triangle determined by A, B, C.
-/
def hilbertTriangleTerm
    (A B C : Geo.Point) :
    HilbertTriangleTerm Geo :=
  A ::ₘ B ::ₘ C ::ₘ 0

/--
A single triangle regarded as a scissors term.
-/
def hilbertScissorsTriangle
    (A B C : Geo.Point) :
    HilbertScissorsTerm Geo :=
  hilbertTriangleTerm Geo A B C ::ₘ 0


theorem triangle_swap12
    (A B C : Geo.Point) :
    hilbertTriangleTerm Geo A B C =
      hilbertTriangleTerm Geo B A C := by
  unfold hilbertTriangleTerm
  exact Multiset.cons_swap A B (C ::ₘ 0)


theorem triangle_cycle
    (A B C : Geo.Point) :
    hilbertTriangleTerm Geo A B C =
      hilbertTriangleTerm Geo B C A := by
  unfold hilbertTriangleTerm
  rw [Multiset.cons_swap A B]
  rw [Multiset.cons_swap A C]

/--
Equidecomposition calculus on formal finite sums of triangles.

The relation is generated by:
- reflexivity, symmetry, transitivity,
- compatibility with formal addition,
- splitting a triangle along a point lying between two vertices,
- replacement of a triangle by a congruent triangle.
-/
inductive HilbertScissorsEq
    (Geo : Geometry.Geo) :
    HilbertScissorsTerm Geo ->
    HilbertScissorsTerm Geo ->
    Prop

  | refl
      (P : HilbertScissorsTerm Geo) :
      HilbertScissorsEq Geo P P

  | symm
      {P Q : HilbertScissorsTerm Geo}
      (h : HilbertScissorsEq Geo P Q) :
      HilbertScissorsEq Geo Q P

  | trans
      {P Q R : HilbertScissorsTerm Geo}
      (hPQ : HilbertScissorsEq Geo P Q)
      (hQR : HilbertScissorsEq Geo Q R) :
      HilbertScissorsEq Geo P R

  | add
      {P Q R S : HilbertScissorsTerm Geo}
      (hPQ : HilbertScissorsEq Geo P Q)
      (hRS : HilbertScissorsEq Geo R S) :
      HilbertScissorsEq Geo
        (P + R)
        (Q + S)

  | split
      (A B C X : Geo.Point)
      (hBXC : Geo.Between B X C) :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B C)
        (hilbertScissorsTriangle Geo A B X +
         hilbertScissorsTriangle Geo A X C)

  | congruent
      (A B C D E F : Geo.Point)
      (hCong :
        TriangleCongruenceResult
          Geo A B C D E F) :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B C)
        (hilbertScissorsTriangle Geo D E F)

theorem scissors_congruent
    (A B C D E F : Geo.Point)
    (hCong :
      TriangleCongruenceResult
        Geo A B C D E F) :
    HilbertScissorsEq Geo
      (hilbertScissorsTriangle Geo A B C)
      (hilbertScissorsTriangle Geo D E F) := by
  exact
    HilbertScissorsEq.congruent
      (Geo := Geo)
      A B C D E F hCong

/--
The standard formal triangulation of the quadrilateral ABCD
along the diagonal AC.
-/
def hilbertParallelogramTerm
    (A B C D : Geo.Point) :
    HilbertScissorsTerm Geo :=
  hilbertScissorsTriangle Geo A B C +
  hilbertScissorsTriangle Geo A C D


/--
Formal equicomplementability.

The two terms become equidecomposable after adjoining
equidecomposable complements.

This is the term-level analogue of Hilbert's
equicomplementability relation.
-/
def HilbertScissorsEquicomplementable
    (P Q : HilbertScissorsTerm Geo) : Prop :=
  ∃ R S : HilbertScissorsTerm Geo,
    HilbertScissorsEq Geo R S ∧
    HilbertScissorsEq Geo (P + R) (Q + S)

theorem equicomplementable_refl
    (P : HilbertScissorsTerm Geo) :
    HilbertScissorsEquicomplementable Geo P P := by
  refine ⟨0, 0, ?_, ?_⟩

  · exact
      HilbertScissorsEq.refl
        (Geo := Geo) 0

  · exact
      HilbertScissorsEq.refl
        (Geo := Geo) (P + 0)


theorem equicomplementable_symm
    {P Q : HilbertScissorsTerm Geo}
    (h :
      HilbertScissorsEquicomplementable Geo P Q) :
    HilbertScissorsEquicomplementable Geo Q P := by

  rcases h with
    ⟨R, S, hRS, hPQ⟩

  exact
    ⟨S, R,
      HilbertScissorsEq.symm
        (Geo := Geo) hRS,
      HilbertScissorsEq.symm
        (Geo := Geo) hPQ⟩

theorem equicomplementable_trans
    {P Q T : HilbertScissorsTerm Geo}
    (hPQ :
      HilbertScissorsEquicomplementable Geo P Q)
    (hQT :
      HilbertScissorsEquicomplementable Geo Q T) :
    HilbertScissorsEquicomplementable Geo P T := by

  rcases hPQ with
    ⟨R1, S1, hR1S1, hPQS⟩

  rcases hQT with
    ⟨R2, S2, hR2S2, hQTS⟩

  refine
    ⟨R1 + R2, S1 + S2, ?_, ?_⟩

  · exact
      HilbertScissorsEq.add
        (Geo := Geo)
        hR1S1
        hR2S2

  · have hStep1 :
        HilbertScissorsEq Geo
          ((P + R1) + R2)
          ((Q + S1) + R2) :=
      HilbertScissorsEq.add
        (Geo := Geo)
        hPQS
        (HilbertScissorsEq.refl
          (Geo := Geo) R2)

    have hStep2 :
        HilbertScissorsEq Geo
          ((Q + R2) + S1)
          ((T + S2) + S1) :=
      HilbertScissorsEq.add
        (Geo := Geo)
        hQTS
        (HilbertScissorsEq.refl
          (Geo := Geo) S1)

    have hStep1' :
        HilbertScissorsEq Geo
          (P + (R1 + R2))
          (Q + (S1 + R2)) := by
      simpa only [Multiset.add_assoc] using hStep1

    have hStep2' :
        HilbertScissorsEq Geo
          (Q + (S1 + R2))
          (T + (S1 + S2)) := by
      simpa only
        [Multiset.add_assoc,
         Multiset.add_comm R2 S1,
         Multiset.add_comm S2 S1]
        using hStep2

    exact
      HilbertScissorsEq.trans
        (Geo := Geo)
        hStep1'
        hStep2'

theorem equicomplementable_of_scissorsEq
    {P Q : HilbertScissorsTerm Geo}
    (hPQ : HilbertScissorsEq Geo P Q) :
    HilbertScissorsEquicomplementable Geo P Q := by

  refine ⟨0, 0, ?_, ?_⟩

  · exact
      HilbertScissorsEq.refl
        (Geo := Geo) 0

  · exact
      HilbertScissorsEq.add
        (Geo := Geo)
        hPQ
        (HilbertScissorsEq.refl
          (Geo := Geo) 0)

theorem triangle_swap23
    (A B C : Geo.Point) :
    hilbertTriangleTerm Geo A B C =
      hilbertTriangleTerm Geo A C B := by
  unfold hilbertTriangleTerm
  rw [Multiset.cons_swap B C]


theorem scissors_triangle_swap12
    (A B C : Geo.Point) :
    hilbertScissorsTriangle Geo A B C =
      hilbertScissorsTriangle Geo B A C := by
  unfold hilbertScissorsTriangle
  rw [triangle_swap12 Geo A B C]


theorem scissors_triangle_swap23
    (A B C : Geo.Point) :
    hilbertScissorsTriangle Geo A B C =
      hilbertScissorsTriangle Geo A C B := by
  unfold hilbertScissorsTriangle
  rw [triangle_swap23 Geo A B C]


theorem scissors_triangle_cycle
    (A B C : Geo.Point) :
    hilbertScissorsTriangle Geo A B C =
      hilbertScissorsTriangle Geo B C A := by
  unfold hilbertScissorsTriangle
  rw [triangle_cycle Geo A B C]


theorem parallelogram_two_triangulations
    [HilbertIncidence Geo]
    [HilbertEuclideanPlane Geo]
    (A B C D : Geo.Point)
    (hParallelogram : IsParallelogram Geo A B C D) :
    HilbertScissorsEq Geo
      (hilbertScissorsTriangle Geo A B C +
       hilbertScissorsTriangle Geo A C D)
      (hilbertScissorsTriangle Geo A B D +
       hilbertScissorsTriangle Geo B C D) := by

  rcases
      ParallelogramDiagonalIntersectionExists
        Geo A B C D hParallelogram
    with
    ⟨M, hAMC, hBMD⟩

  --------------------------------------------------------------------
  -- Diagonal AC.
  --
  -- ABC is split by BM at M on AC:
  --
  --   ABC = ABM + BCM
  --------------------------------------------------------------------

  have hABC0 :=
    HilbertScissorsEq.split
      (Geo := Geo) B A C M hAMC

  have hABC :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B C)
        (hilbertScissorsTriangle Geo A B M +
         hilbertScissorsTriangle Geo B C M) := by
    rw [scissors_triangle_swap12 Geo B A C] at hABC0
    rw [scissors_triangle_swap12 Geo B A M] at hABC0
    rw [scissors_triangle_swap23 Geo B M C] at hABC0
    exact hABC0

  --------------------------------------------------------------------
  -- ACD is split by DM at M on AC:
  --
  --   ACD = AMD + CDM
  --------------------------------------------------------------------

  have hACD0 :=
    HilbertScissorsEq.split
      (Geo := Geo) D A C M hAMC

  have hACD :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A C D)
        (hilbertScissorsTriangle Geo A M D +
         hilbertScissorsTriangle Geo C D M) := by
    rw [scissors_triangle_cycle Geo D A C] at hACD0
    rw [scissors_triangle_cycle Geo D A M] at hACD0
    rw [scissors_triangle_cycle Geo D M C] at hACD0
    rw [scissors_triangle_cycle Geo M C D] at hACD0
    exact hACD0

  have hDiagonalAC :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B C +
         hilbertScissorsTriangle Geo A C D)
        ((hilbertScissorsTriangle Geo A B M +
          hilbertScissorsTriangle Geo B C M) +
         (hilbertScissorsTriangle Geo A M D +
          hilbertScissorsTriangle Geo C D M)) :=
    HilbertScissorsEq.add
      (Geo := Geo) hABC hACD

  --------------------------------------------------------------------
  -- Diagonal BD.
  --
  -- ABD is split by AM at M on BD:
  --
  --   ABD = ABM + AMD
  --------------------------------------------------------------------

  have hABD :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B D)
        (hilbertScissorsTriangle Geo A B M +
         hilbertScissorsTriangle Geo A M D) :=
    HilbertScissorsEq.split
      (Geo := Geo) A B D M hBMD

  --------------------------------------------------------------------
  -- BCD is split by CM at M on BD:
  --
  --   BCD = BCM + CDM
  --------------------------------------------------------------------

  have hBCD0 :=
    HilbertScissorsEq.split
      (Geo := Geo) C B D M hBMD

  have hBCD :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo B C D)
        (hilbertScissorsTriangle Geo B C M +
         hilbertScissorsTriangle Geo C D M) := by
    rw [scissors_triangle_swap12 Geo C B D] at hBCD0
    rw [scissors_triangle_swap12 Geo C B M] at hBCD0
    rw [scissors_triangle_swap23 Geo C M D] at hBCD0
    exact hBCD0

  have hDiagonalBD :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B D +
         hilbertScissorsTriangle Geo B C D)
        ((hilbertScissorsTriangle Geo A B M +
          hilbertScissorsTriangle Geo A M D) +
         (hilbertScissorsTriangle Geo B C M +
          hilbertScissorsTriangle Geo C D M)) :=
    HilbertScissorsEq.add
      (Geo := Geo) hABD hBCD

  --------------------------------------------------------------------
  -- Both refinements consist of exactly the same four triangles.
  --------------------------------------------------------------------

  have hCommon :
      ((hilbertScissorsTriangle Geo A B M +
        hilbertScissorsTriangle Geo B C M) +
       (hilbertScissorsTriangle Geo A M D +
        hilbertScissorsTriangle Geo C D M))
        =
      ((hilbertScissorsTriangle Geo A B M +
        hilbertScissorsTriangle Geo A M D) +
       (hilbertScissorsTriangle Geo B C M +
        hilbertScissorsTriangle Geo C D M)) := by
    calc
      ((hilbertScissorsTriangle Geo A B M +
        hilbertScissorsTriangle Geo B C M) +
       (hilbertScissorsTriangle Geo A M D +
        hilbertScissorsTriangle Geo C D M))
          =
        hilbertScissorsTriangle Geo A B M +
          (hilbertScissorsTriangle Geo B C M +
           (hilbertScissorsTriangle Geo A M D +
            hilbertScissorsTriangle Geo C D M)) :=
        Multiset.add_assoc _ _ _

      _ =
        hilbertScissorsTriangle Geo A B M +
          (hilbertScissorsTriangle Geo A M D +
           (hilbertScissorsTriangle Geo B C M +
            hilbertScissorsTriangle Geo C D M)) := by
        apply congrArg
          (fun T =>
            hilbertScissorsTriangle Geo A B M + T)
        calc
          hilbertScissorsTriangle Geo B C M +
              (hilbertScissorsTriangle Geo A M D +
               hilbertScissorsTriangle Geo C D M)
              =
            (hilbertScissorsTriangle Geo B C M +
             hilbertScissorsTriangle Geo A M D) +
              hilbertScissorsTriangle Geo C D M :=
            (Multiset.add_assoc _ _ _).symm

          _ =
            (hilbertScissorsTriangle Geo A M D +
             hilbertScissorsTriangle Geo B C M) +
              hilbertScissorsTriangle Geo C D M := by
            rw [Multiset.add_comm
              (hilbertScissorsTriangle Geo B C M)
              (hilbertScissorsTriangle Geo A M D)]

          _ =
            hilbertScissorsTriangle Geo A M D +
              (hilbertScissorsTriangle Geo B C M +
               hilbertScissorsTriangle Geo C D M) :=
            Multiset.add_assoc _ _ _

      _ =
        ((hilbertScissorsTriangle Geo A B M +
          hilbertScissorsTriangle Geo A M D) +
         (hilbertScissorsTriangle Geo B C M +
          hilbertScissorsTriangle Geo C D M)) :=
        (Multiset.add_assoc _ _ _).symm

  rw [← hCommon] at hDiagonalBD

  exact
    HilbertScissorsEq.trans
      (Geo := Geo)
      hDiagonalAC
      (HilbertScissorsEq.symm
        (Geo := Geo) hDiagonalBD)

theorem parallelogram_term_reverse
    [HilbertIncidence Geo]
    [HilbertEuclideanPlane Geo]
    (A B C D : Geo.Point)
    (hParallelogram : IsParallelogram Geo A B C D) :
    HilbertScissorsEq Geo
      (hilbertParallelogramTerm Geo A B C D)
      (hilbertParallelogramTerm Geo B A D C) := by

  unfold hilbertParallelogramTerm

  have h :=
    parallelogram_two_triangulations
      Geo A B C D hParallelogram

  rw [scissors_triangle_swap12 Geo A B D] at h
  rw [scissors_triangle_swap23 Geo B C D] at h

  exact h

theorem crossing_quadrilateral_two_triangulations
    (A B C D M : Geo.Point)
    (hAMC : Geo.Between A M C)
    (hBMD : Geo.Between B M D) :
    HilbertScissorsEq Geo
      (hilbertScissorsTriangle Geo A B C +
       hilbertScissorsTriangle Geo A C D)
      (hilbertScissorsTriangle Geo A B D +
       hilbertScissorsTriangle Geo B C D) := by

  --------------------------------------------------------------------
  -- Split ABC along BM, since A-M-C.
  --------------------------------------------------------------------

  have hABC0 :=
    HilbertScissorsEq.split
      (Geo := Geo)
      B A C M hAMC

  have hABC :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B C)
        (hilbertScissorsTriangle Geo A B M +
         hilbertScissorsTriangle Geo B M C) := by

    rw [scissors_triangle_swap12 Geo B A C] at hABC0
    rw [scissors_triangle_swap12 Geo B A M] at hABC0

    exact hABC0

  --------------------------------------------------------------------
  -- Split ACD along DM, since A-M-C.
  --------------------------------------------------------------------

  have hACD0 :=
    HilbertScissorsEq.split
      (Geo := Geo)
      D A C M hAMC

  have hACD :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A C D)
        (hilbertScissorsTriangle Geo A M D +
         hilbertScissorsTriangle Geo C M D) := by

    -- DAC -> ACD
    rw [scissors_triangle_cycle Geo D A C] at hACD0

    -- DAM -> AMD
    rw [scissors_triangle_cycle Geo D A M] at hACD0

    -- DMC -> CMD
    rw [scissors_triangle_swap12 Geo D M C] at hACD0
    rw [scissors_triangle_cycle Geo M D C] at hACD0
    rw [scissors_triangle_cycle Geo D C M] at hACD0

    exact hACD0

  --------------------------------------------------------------------
  -- Therefore the AC triangulation refines to four triangles.
  --------------------------------------------------------------------

  have hLeft :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B C +
         hilbertScissorsTriangle Geo A C D)
        ((hilbertScissorsTriangle Geo A B M +
          hilbertScissorsTriangle Geo B M C) +
         (hilbertScissorsTriangle Geo A M D +
          hilbertScissorsTriangle Geo C M D)) :=

    HilbertScissorsEq.add
      (Geo := Geo)
      hABC
      hACD

  --------------------------------------------------------------------
  -- Split ABD along AM, since B-M-D.
  --------------------------------------------------------------------

  have hABD :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B D)
        (hilbertScissorsTriangle Geo A B M +
         hilbertScissorsTriangle Geo A M D) :=
    HilbertScissorsEq.split
      (Geo := Geo)
      A B D M hBMD

  --------------------------------------------------------------------
  -- Split BCD along CM, since B-M-D.
  --------------------------------------------------------------------

  have hBCD0 :=
    HilbertScissorsEq.split
      (Geo := Geo)
      C B D M hBMD

  have hBCD :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo B C D)
        (hilbertScissorsTriangle Geo B M C +
         hilbertScissorsTriangle Geo C M D) := by

    -- CBD -> BCD
    rw [scissors_triangle_swap12 Geo C B D] at hBCD0

    -- CBM -> BCM -> BMC
    rw [scissors_triangle_swap12 Geo C B M] at hBCD0
    rw [scissors_triangle_swap23 Geo B C M] at hBCD0

    exact hBCD0

  --------------------------------------------------------------------
  -- Therefore the BD triangulation refines to the same four triangles.
  --------------------------------------------------------------------

  have hRight :
      HilbertScissorsEq Geo
        (hilbertScissorsTriangle Geo A B D +
         hilbertScissorsTriangle Geo B C D)
        ((hilbertScissorsTriangle Geo A B M +
          hilbertScissorsTriangle Geo A M D) +
         (hilbertScissorsTriangle Geo B M C +
          hilbertScissorsTriangle Geo C M D)) :=

    HilbertScissorsEq.add
      (Geo := Geo)
      hABD
      hBCD

  --------------------------------------------------------------------
  -- The four pieces differ only by formal order.
  --------------------------------------------------------------------

  have hArrange :
      ((hilbertScissorsTriangle Geo A B M +
        hilbertScissorsTriangle Geo B M C) +
       (hilbertScissorsTriangle Geo A M D +
        hilbertScissorsTriangle Geo C M D))
        =
      ((hilbertScissorsTriangle Geo A B M +
        hilbertScissorsTriangle Geo A M D) +
       (hilbertScissorsTriangle Geo B M C +
        hilbertScissorsTriangle Geo C M D)) := by

    calc
      ((hilbertScissorsTriangle Geo A B M +
        hilbertScissorsTriangle Geo B M C) +
       (hilbertScissorsTriangle Geo A M D +
        hilbertScissorsTriangle Geo C M D))
          =
        hilbertScissorsTriangle Geo A B M +
          (hilbertScissorsTriangle Geo B M C +
           (hilbertScissorsTriangle Geo A M D +
            hilbertScissorsTriangle Geo C M D)) :=
        Multiset.add_assoc _ _ _

      _ =
        hilbertScissorsTriangle Geo A B M +
          ((hilbertScissorsTriangle Geo B M C +
            hilbertScissorsTriangle Geo A M D) +
           hilbertScissorsTriangle Geo C M D) := by
        apply congrArg
          (fun T =>
            hilbertScissorsTriangle Geo A B M + T)
        exact
          (Multiset.add_assoc
            (hilbertScissorsTriangle Geo B M C)
            (hilbertScissorsTriangle Geo A M D)
            (hilbertScissorsTriangle Geo C M D)).symm

      _ =
        hilbertScissorsTriangle Geo A B M +
          ((hilbertScissorsTriangle Geo A M D +
            hilbertScissorsTriangle Geo B M C) +
           hilbertScissorsTriangle Geo C M D) := by
        apply congrArg
          (fun T =>
            hilbertScissorsTriangle Geo A B M + T)
        apply congrArg
          (fun T =>
            T + hilbertScissorsTriangle Geo C M D)
        exact
          Multiset.add_comm
            (hilbertScissorsTriangle Geo B M C)
            (hilbertScissorsTriangle Geo A M D)

      _ =
        hilbertScissorsTriangle Geo A B M +
          (hilbertScissorsTriangle Geo A M D +
           (hilbertScissorsTriangle Geo B M C +
            hilbertScissorsTriangle Geo C M D)) := by
        apply congrArg
          (fun T =>
            hilbertScissorsTriangle Geo A B M + T)
        exact
          Multiset.add_assoc
            (hilbertScissorsTriangle Geo A M D)
            (hilbertScissorsTriangle Geo B M C)
            (hilbertScissorsTriangle Geo C M D)

      _ =
        ((hilbertScissorsTriangle Geo A B M +
          hilbertScissorsTriangle Geo A M D) +
         (hilbertScissorsTriangle Geo B M C +
          hilbertScissorsTriangle Geo C M D)) := by
        exact
          (Multiset.add_assoc
            (hilbertScissorsTriangle Geo A B M)
            (hilbertScissorsTriangle Geo A M D)
            (hilbertScissorsTriangle Geo B M C +
             hilbertScissorsTriangle Geo C M D)).symm

  rw [hArrange] at hLeft

  exact
    HilbertScissorsEq.trans
      (Geo := Geo)
      hLeft
      (HilbertScissorsEq.symm
        (Geo := Geo) hRight)

theorem parallelogram_term_rotateTwo
    (A B C D : Geo.Point) :
    HilbertScissorsEq Geo
      (hilbertParallelogramTerm Geo A B C D)
      (hilbertParallelogramTerm Geo C D A B) := by

  unfold hilbertParallelogramTerm

  rw [scissors_triangle_cycle Geo C D A]
  rw [scissors_triangle_cycle Geo D A C]
  rw [scissors_triangle_cycle Geo C A B]

  rw [Multiset.add_comm
    (hilbertScissorsTriangle Geo A C D)
    (hilbertScissorsTriangle Geo A B C)]

  exact
    HilbertScissorsEq.refl
      (Geo := Geo) _

end Geometry
