import CGJteamLab.HilbertDimensionFreeFlats

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# Dimension-free Smith exchange calculus

This module contains the abstract closure/exchange layer for `SmithSpan`.

It does NOT assume that exchange holds.  Instead it:

* defines one-point adjunction;
* records standard closure lemmas;
* defines the Steinitz exchange property;
* defines Wyler's generated-flat exchange formulation;
* proves that the two exchange formulations are equivalent.

The geometric theorem that Smith I5 implies exchange belongs to the next
production layer.  Thus no diagnostic exchange axiom is installed here.
-/

/--
Adjoin one point P to a set X.
-/
def SmithAdjoinPoint
    (X : Set Geo.Point)
    (P : Geo.Point) : Set Geo.Point :=
  fun Q => Q = P \/ X Q


/--
Smith span is monotone.
-/
theorem smithSpan_mono
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    {X Y : Set Geo.Point}
    (hXY : Set.Subset X Y) :
    Set.Subset
      (SmithSpan Geo X)
      (SmithSpan Geo Y) := by

  intro P hPX F hFlat hYF

  apply hPX F hFlat

  intro Q hQX
  exact hYF (hXY hQX)


/--
Idempotence of Smith closure.
-/
theorem smithSpan_idempotent
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (X : Set Geo.Point) :
    SmithSpan Geo (SmithSpan Geo X) =
      SmithSpan Geo X := by

  apply Set.Subset.antisymm

  · exact
      smithSpan_least
        (Geo := Geo)
        (SmithSpan Geo X)
        (SmithSpan Geo X)
        (smithSpan_flat (Geo := Geo) X)
        Set.Subset.rfl

  · exact
      smithSpan_extensive
        (Geo := Geo)
        (SmithSpan Geo X)


/--
A Smith flat is already closed under Smith span.
-/
theorem smithSpan_eq_self_of_flat
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (F : Set Geo.Point)
    (hFlat : SmithFlat Geo F) :
    SmithSpan Geo F = F := by

  apply Set.Subset.antisymm

  · exact
      smithSpan_least
        (Geo := Geo)
        F F
        hFlat
        Set.Subset.rfl

  · exact
      smithSpan_extensive
        (Geo := Geo)
        F


/--
Steinitz exchange for the Smith closure operator.

This is a property type, not an additional geometric axiom.  Later
production theorems derive a value of this type from
`HilbertDimensionFreeIncidence`.
-/
class SmithSpanExchange
    (Geo : Geometry.Geo)
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo] : Prop where

  exchange :
    forall X : Set Geo.Point,
      forall P Q : Geo.Point,
        SmithSpan Geo (SmithAdjoinPoint Geo X Q) P ->
        Not (SmithSpan Geo X P) ->
        SmithSpan Geo (SmithAdjoinPoint Geo X P) Q


/--
Wyler's generated-flat exchange statement in closure notation.

If B lies in the flat generated by F and A, with A and B both outside F,
then replacing A by B does not change the generated flat.
-/
def WylerGeneratedFlatExchange
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo] : Prop :=
  forall F : Set Geo.Point,
    SmithFlat Geo F ->
    forall A B : Geo.Point,
      Not (F A) ->
      Not (F B) ->
      SmithSpan Geo (SmithAdjoinPoint Geo F A) B ->
      SmithSpan Geo (SmithAdjoinPoint Geo F B) =
        SmithSpan Geo (SmithAdjoinPoint Geo F A)


/--
Steinitz exchange implies Wyler's generated-flat exchange formulation.
-/
theorem smithSpanExchange_implies_wylerGeneratedFlatExchange
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (hExchange : SmithSpanExchange Geo) :
    WylerGeneratedFlatExchange Geo := by

  intro F hFlat A B hAOut hBOut hBinFA

  have hSpanF :
      SmithSpan Geo F = F :=
    smithSpan_eq_self_of_flat
      (Geo := Geo)
      F hFlat

  have hBNotSpanF :
      Not (SmithSpan Geo F B) := by
    intro hB
    rw [hSpanF] at hB
    exact hBOut hB

  have hAinFB :
      SmithSpan Geo (SmithAdjoinPoint Geo F B) A :=
    hExchange.exchange
      F
      B A
      hBinFA
      hBNotSpanF

  apply Set.Subset.antisymm

  · apply
      smithSpan_least
        (Geo := Geo)
        (SmithAdjoinPoint Geo F B)
        (SmithSpan Geo (SmithAdjoinPoint Geo F A))
        (smithSpan_flat
          (Geo := Geo)
          (SmithAdjoinPoint Geo F A))

    intro P hP
    rcases hP with hPB | hPF

    · subst P
      exact hBinFA

    · apply
        smithSpan_extensive
          (Geo := Geo)
          (SmithAdjoinPoint Geo F A)
      exact Or.inr hPF

  · apply
      smithSpan_least
        (Geo := Geo)
        (SmithAdjoinPoint Geo F A)
        (SmithSpan Geo (SmithAdjoinPoint Geo F B))
        (smithSpan_flat
          (Geo := Geo)
          (SmithAdjoinPoint Geo F B))

    intro P hP
    rcases hP with hPA | hPF

    · subst P
      exact hAinFB

    · apply
        smithSpan_extensive
          (Geo := Geo)
          (SmithAdjoinPoint Geo F B)
      exact Or.inr hPF


/--
Wyler's generated-flat exchange implies ordinary Steinitz exchange for
arbitrary generator sets.
-/
theorem wylerGeneratedFlatExchange_implies_smithSpanExchange
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    (hWyler : WylerGeneratedFlatExchange Geo) :
    SmithSpanExchange Geo := by

  constructor
  intro X P Q hPInXQ hPNotX

  let F : Set Geo.Point :=
    SmithSpan Geo X

  have hFlatF :
      SmithFlat Geo F := by
    exact
      smithSpan_flat
        (Geo := Geo)
        X

  have hPOutF :
      Not (F P) := by
    exact hPNotX

  have hQOutF :
      Not (F Q) := by
    intro hQF

    have hAdjoinXQSubF :
        Set.Subset
          (SmithAdjoinPoint Geo X Q)
          F := by
      intro R hR
      rcases hR with hRQ | hRX

      · subst R
        exact hQF

      · exact
          smithSpan_extensive
            (Geo := Geo)
            X hRX

    have hPInF :
        F P :=
      smithSpan_least
        (Geo := Geo)
        (SmithAdjoinPoint Geo X Q)
        F
        hFlatF
        hAdjoinXQSubF
        hPInXQ

    exact hPNotX hPInF

  have hAdjoinXQSubFQ :
      Set.Subset
        (SmithAdjoinPoint Geo X Q)
        (SmithAdjoinPoint Geo F Q) := by

    intro R hR
    rcases hR with hRQ | hRX

    · exact Or.inl hRQ

    · exact
        Or.inr
          (smithSpan_extensive
            (Geo := Geo)
            X hRX)

  have hPInFQ :
      SmithSpan Geo
        (SmithAdjoinPoint Geo F Q) P :=
    smithSpan_mono
      (Geo := Geo)
      hAdjoinXQSubFQ
      hPInXQ

  have hEq :
      SmithSpan Geo (SmithAdjoinPoint Geo F P) =
        SmithSpan Geo (SmithAdjoinPoint Geo F Q) :=
    hWyler
      F hFlatF
      Q P
      hQOutF hPOutF
      hPInFQ

  have hQInFQ :
      SmithSpan Geo
        (SmithAdjoinPoint Geo F Q) Q := by

    apply
      smithSpan_extensive
        (Geo := Geo)
        (SmithAdjoinPoint Geo F Q)

    exact Or.inl rfl

  have hQInFP :
      SmithSpan Geo
        (SmithAdjoinPoint Geo F P) Q := by
    rw [hEq]
    exact hQInFQ

  have hXSubXP :
      Set.Subset
        X
        (SmithAdjoinPoint Geo X P) := by
    intro R hRX
    exact Or.inr hRX

  have hFSubXPSpan :
      Set.Subset
        F
        (SmithSpan Geo
          (SmithAdjoinPoint Geo X P)) := by

    exact
      smithSpan_mono
        (Geo := Geo)
        hXSubXP

  have hAdjoinFPSubXPSpan :
      Set.Subset
        (SmithAdjoinPoint Geo F P)
        (SmithSpan Geo
          (SmithAdjoinPoint Geo X P)) := by

    intro R hR
    rcases hR with hRP | hRF

    · subst R
      apply
        smithSpan_extensive
          (Geo := Geo)
          (SmithAdjoinPoint Geo X P)
      exact Or.inl rfl

    · exact hFSubXPSpan hRF

  exact
    smithSpan_least
      (Geo := Geo)
      (SmithAdjoinPoint Geo F P)
      (SmithSpan Geo
        (SmithAdjoinPoint Geo X P))
      (smithSpan_flat
        (Geo := Geo)
        (SmithAdjoinPoint Geo X P))
      hAdjoinFPSubXPSpan
      hQInFP


/--
The Steinitz and Wyler generated-flat exchange formulations are exactly
equivalent.
-/
theorem wylerGeneratedFlatExchange_iff_smithSpanExchange
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo] :
    WylerGeneratedFlatExchange Geo <->
      SmithSpanExchange Geo := by

  constructor

  · exact
      wylerGeneratedFlatExchange_implies_smithSpanExchange
        (Geo := Geo)

  · intro hExchange

    exact
      smithSpanExchange_implies_wylerGeneratedFlatExchange
        (Geo := Geo)
        hExchange

end Geometry
