import CGJteamLab.HilbertSpaceIncidence

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# Sancho de Salas incidence axioms

This module records the point-line-plane incidence axioms LP1-LP4 from
Juan B. Sancho de Salas, "The Fundamental Theorem for locally projective
geometries", Definition 3.6.

The purpose of this file is deliberately narrow:

* it gives a source-based, dimension-independent incidence interface;
* it introduces no dimension axiom;
* it introduces no order, congruence, parallelism, metric, orthogonality,
  reflection, or continuity axiom;
* it does not assume Mac Lane-Steinitz exchange;
* it does not identify the axioms below with Wyler's 1953 IG1-IG5
  declaration by declaration.

The existing `HilbertSpacePrimitive` type is reused only as the current
project signature for planes and point-plane incidence. No
`HilbertSpaceIncidence` assumption is used here.

The later bridge to the existing Smith/Wyler machinery is intentionally
kept out of this file.
-/

/--
Sancho de Salas LP1-LP4 in the current point-line-plane language.

LP1:
  two distinct points determine a unique line, and every line contains
  at least two distinct points.

LP2:
  three noncollinear points determine a unique plane, and every plane
  contains at least three noncollinear points.

LP3:
  the line joining two distinct points of a plane is contained in that
  plane.

LP4:
  if `l1` and `l2` are distinct lines in a plane `pi`, and `x` is
  outside `pi`, then the two planes generated by `l1,x` and `l2,x`
  intersect in a line.

In LP4 we avoid introducing a separate join operation. Instead we
quantify over planes `alpha` and `beta` containing the required line
and the external point. LP2 and LP3 provide the uniqueness needed to
interpret these planes as `l1 v x` and `l2 v x`.
-/
class SalasIncidence
    (Geo : Geometry.Geo)
    [H : HilbertIncidence Geo]
    [S : HilbertSpacePrimitive Geo] : Prop where

  /-- LP1, existence and uniqueness of the joining line. -/
  line_through_unique :
    forall A B : Geo.Point,
      Ne A B ->
      exists l : Geo.Line,
        H.OnLine A l /\
        H.OnLine B l /\
        forall m : Geo.Line,
          H.OnLine A m ->
          H.OnLine B m ->
          m = l

  /-- LP1, every line has at least two distinct points. -/
  two_points_on_each_line :
    forall l : Geo.Line,
      exists A B : Geo.Point,
        Ne A B /\
        H.OnLine A l /\
        H.OnLine B l

  /-- LP2, existence and uniqueness of the joining plane. -/
  plane_through_unique :
    forall A B C : Geo.Point,
      Not (PrimCollinear Geo A B C) ->
      exists pi : S.Plane,
        S.OnPlane A pi /\
        S.OnPlane B pi /\
        S.OnPlane C pi /\
        forall rho : S.Plane,
          S.OnPlane A rho ->
          S.OnPlane B rho ->
          S.OnPlane C rho ->
          rho = pi

  /-- LP2, every plane has at least three noncollinear points. -/
  three_noncollinear_on_each_plane :
    forall pi : S.Plane,
      exists A B C : Geo.Point,
        S.OnPlane A pi /\
        S.OnPlane B pi /\
        S.OnPlane C pi /\
        Not (PrimCollinear Geo A B C)

  /--
  LP3, line closure inside a plane.

  Since LP1 gives uniqueness of the line through `A,B`, any line `l`
  containing the two distinct points is their joining line.
  -/
  line_in_plane :
    forall A B : Geo.Point,
      Ne A B ->
      forall l : Geo.Line,
        H.OnLine A l ->
        H.OnLine B l ->
        forall pi : S.Plane,
          S.OnPlane A pi ->
          S.OnPlane B pi ->
          HilbertLineInPlane Geo l pi

  /--
  LP4, the local projective incidence axiom.

  The conclusion says that the set-theoretic intersection of `alpha`
  and `beta`, expressed through point-plane incidence, is exactly the
  point set of a line `m`.
  -/
  lp4 :
    forall pi : S.Plane,
      forall l1 l2 : Geo.Line,
        Ne l1 l2 ->
        HilbertLineInPlane Geo l1 pi ->
        HilbertLineInPlane Geo l2 pi ->
        forall x : Geo.Point,
          Not (S.OnPlane x pi) ->
          forall alpha beta : S.Plane,
            HilbertLineInPlane Geo l1 alpha ->
            S.OnPlane x alpha ->
            HilbertLineInPlane Geo l2 beta ->
            S.OnPlane x beta ->
            exists m : Geo.Line,
              forall y : Geo.Point,
                H.OnLine y m <->
                  S.OnPlane y alpha /\ S.OnPlane y beta

end Geometry
