import CGJteamLab.Coxeter.E4HyperplaneReflectionEquiv

/-!
# Corrected E4 hyperplane intersection

Production promotion of the exact common-plane theorem for two
distinct E4 hyperplanes. The historical reflection-word checkpoint
imports are removed because this module does not use that API.
-/

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# E4: exact intersection plane of two distinct hyperplanes

For a finite Coxeter relation between two reflecting hyperplanes, the
interesting case is the intersecting one.

In genuine E4, two distinct 3-hyperplanes which share three
noncollinear points meet in a 2-plane. This file proves the exact
intersection statement synthetically.

No metric, angle, normal, coordinate, or dimension formula is used.
The proof is pure incidence:

* three noncollinear common points determine a unique 2-plane Delta;
* Delta lies in both hyperplanes;
* a fourth common point outside Delta would make the four points
  noncoplanar;
* four noncoplanar common points determine a unique hyperplane, forcing
  the two hyperplanes to be equal.
-/

/--
`HyperplanesMeetInPlane4_corrected Geo Sigma Tau Delta` means that
Sigma and Tau are distinct and their pointwise intersection is exactly
the ambient 2-plane Delta.
-/
def HyperplanesMeetInPlane4_corrected
    [HilbertIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    (Sigma Tau : Q.Hyperplane)
    (Delta : Q.toHilbertSpacePrimitive.Plane) : Prop :=
  Ne Sigma Tau /\
  HilbertPlaneInHyperplane4 Geo Delta Sigma /\
  HilbertPlaneInHyperplane4 Geo Delta Tau /\
  forall X : Geo.Point,
    (Q.OnHyperplane X Sigma /\ Q.OnHyperplane X Tau) <->
      Q.toHilbertSpacePrimitive.OnPlane X Delta

/--
A fourth point outside the plane through three noncollinear points is
noncoplanar with those three points.
-/
theorem hilbert4D_noncoplanar_of_off_plane_through_three_corrected
    [H : HilbertIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    [H4I : Hilbert4DAmbientIncidence Geo]
    (A B C X : Geo.Point)
    (Delta : Q.toHilbertSpacePrimitive.Plane)
    (hABC : Not (PrimCollinear Geo A B C))
    (hADelta :
      Q.toHilbertSpacePrimitive.OnPlane A Delta)
    (hBDelta :
      Q.toHilbertSpacePrimitive.OnPlane B Delta)
    (hCDelta :
      Q.toHilbertSpacePrimitive.OnPlane C Delta)
    (hXoff :
      Not (Q.toHilbertSpacePrimitive.OnPlane X Delta)) :
    Not (HilbertCoplanar4 Geo A B C X) := by

  intro hCop

  let pi : Q.toHilbertSpacePrimitive.Plane :=
    Classical.choose hCop

  have hData :=
    Classical.choose_spec hCop

  have hApi := hData.1
  have hBpi := hData.2.1
  have hCpi := hData.2.2.1
  have hXpi := hData.2.2.2

  have hPiDelta :
      pi = Delta :=
    H4I.plane_unique
      A B C
      hABC
      pi Delta
      hApi hBpi hCpi
      hADelta hBDelta hCDelta

  have hXpiPi :
      Q.toHilbertSpacePrimitive.OnPlane X pi := by
    simpa [pi] using hXpi

  rw [hPiDelta] at hXpiPi

  exact hXoff hXpiPi

/--
If two distinct E4 hyperplanes contain the same three noncollinear
points, then the plane generated by those three points is their exact
intersection.
-/
theorem hilbert4D_distinct_hyperplanes_exact_common_plane_corrected
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    [H4I : Hilbert4DAmbientIncidence Geo]
    [H4L : Hilbert4DHyperplaneLocal3DIncidence Geo]
    (Sigma Tau : Q.Hyperplane)
    (hSigmaTau : Ne Sigma Tau)
    (A B C : Geo.Point)
    (hABC : Not (PrimCollinear Geo A B C))
    (hASigma : Q.OnHyperplane A Sigma)
    (hBSigma : Q.OnHyperplane B Sigma)
    (hCSigma : Q.OnHyperplane C Sigma)
    (hATau : Q.OnHyperplane A Tau)
    (hBTau : Q.OnHyperplane B Tau)
    (hCTau : Q.OnHyperplane C Tau) :
    exists Delta : Q.toHilbertSpacePrimitive.Plane,
      Q.toHilbertSpacePrimitive.OnPlane A Delta /\
      Q.toHilbertSpacePrimitive.OnPlane B Delta /\
      Q.toHilbertSpacePrimitive.OnPlane C Delta /\
      HyperplanesMeetInPlane4_corrected
        Geo Sigma Tau Delta := by

  have hPlaneExists :=
    H4I.plane_through
      A B C hABC

  let Delta : Q.toHilbertSpacePrimitive.Plane :=
    Classical.choose hPlaneExists

  have hData :=
    Classical.choose_spec hPlaneExists

  have hADelta := hData.1
  have hBDelta := hData.2.1
  have hCDelta := hData.2.2

  have hDeltaSigma :
      HilbertPlaneInHyperplane4
        Geo Delta Sigma :=
    H4L.plane_in_hyperplane
      A B C hABC
      Delta
      hADelta hBDelta hCDelta
      Sigma
      hASigma hBSigma hCSigma

  have hDeltaTau :
      HilbertPlaneInHyperplane4
        Geo Delta Tau :=
    H4L.plane_in_hyperplane
      A B C hABC
      Delta
      hADelta hBDelta hCDelta
      Tau
      hATau hBTau hCTau

  refine Exists.intro Delta ?_

  refine And.intro hADelta ?_
  refine And.intro hBDelta ?_
  refine And.intro hCDelta ?_

  unfold HyperplanesMeetInPlane4_corrected

  refine And.intro hSigmaTau ?_
  refine And.intro hDeltaSigma ?_
  refine And.intro hDeltaTau ?_

  intro X

  constructor

  case mp =>
    intro hXBoth

    by_contra hXoff

    have hNoncop :
        Not (HilbertCoplanar4 Geo A B C X) :=
      hilbert4D_noncoplanar_of_off_plane_through_three_corrected
        (Geo := Geo)
        A B C X
        Delta
        hABC
        hADelta hBDelta hCDelta
        hXoff

    have hEq :
        Sigma = Tau :=
      H4I.hyperplane_unique
        A B C X
        hNoncop
        Sigma Tau
        hASigma hBSigma hCSigma hXBoth.1
        hATau hBTau hCTau hXBoth.2

    exact hSigmaTau hEq

  case mpr =>
    intro hXDelta

    exact
      And.intro
        (hDeltaSigma X hXDelta)
        (hDeltaTau X hXDelta)

/--
Membership in the exact common plane is equivalent to membership in
both reflecting hyperplanes.
-/
theorem hyperplanesMeetInPlane4_corrected_iff
    [HilbertIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    (Sigma Tau : Q.Hyperplane)
    (Delta : Q.toHilbertSpacePrimitive.Plane)
    (hMeet :
      HyperplanesMeetInPlane4_corrected
        Geo Sigma Tau Delta)
    (X : Geo.Point) :
    Q.toHilbertSpacePrimitive.OnPlane X Delta <->
      Q.OnHyperplane X Sigma /\ Q.OnHyperplane X Tau := by

  exact (hMeet.2.2.2 X).symm

/--
Every point of the exact common plane is fixed by both corrected
hyperplane reflections.
-/
theorem hyperplanesMeetInPlane4_corrected_common_point_fixed
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [Q : Hilbert4DPrimitive Geo]
    [Hilbert4DAmbientIncidence Geo]
    [Hilbert4DAmbientOrder Geo]
    [Hilbert4DAmbientCongruence Geo]
    [Hilbert4DNormalFromExternalPointExistence_corrected Geo]
    (Sigma Tau : Q.Hyperplane)
    (Delta : Q.toHilbertSpacePrimitive.Plane)
    (hMeet :
      HyperplanesMeetInPlane4_corrected
        Geo Sigma Tau Delta)
    (X : Geo.Point)
    (hXDelta :
      Q.toHilbertSpacePrimitive.OnPlane X Delta) :
    hyperplaneReflect4_corrected Geo Sigma X = X /\
    hyperplaneReflect4_corrected Geo Tau X = X := by

  have hXBoth :
      Q.OnHyperplane X Sigma /\
      Q.OnHyperplane X Tau :=
    (hyperplanesMeetInPlane4_corrected_iff
      (Geo := Geo)
      Sigma Tau Delta
      hMeet X).mp hXDelta

  constructor

  next =>
    exact
      (hyperplaneReflect4_corrected_fixed_iff
        (Geo := Geo)
        Sigma X).2
        hXBoth.1

  next =>
    exact
      (hyperplaneReflect4_corrected_fixed_iff
        (Geo := Geo)
        Tau X).2
        hXBoth.2

end Geometry
