import CGJteamLab.Wyler.HilbertWylerInterface

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/-!
# Wyler affine proportion

This file introduces the incidence/affine notion needed by Euclid XI.17.

The primitive relation is the affine intercept step

  X-E-Y,
  X-F-Z,
  EF || YZ.

It says that E and F occupy the same affine division position on the
two transversals XY and XZ.

The full relation on ordered triples is generated by:

* one affine intercept step;
* reflexivity;
* symmetry;
* transitivity;
* simultaneous reversal of both ordered triples.

No segment classes, angle ratios, metric lengths, coordinates, real
numbers, or HilbertVI2Raw occur in this definition.
-/

/--
One elementary affine intercept step.

The triples

  (X,E,Y) and (X,F,Z)

have a common first endpoint X.  The joining line EF is parallel to the
joining line YZ.  This is the incidence form of the elementary Thales
configuration.
-/
def HilbertWylerDivisionStep
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [_HSI : HilbertSpaceIncidence Geo]
    (X E Y F Z : Geo.Point) : Prop :=
  Geo.Between X E Y /\
  Geo.Between X F Z /\
  exists lEF lYZ : Geo.Line,
    H.OnLine E lEF /\
    H.OnLine F lEF /\
    H.OnLine Y lYZ /\
    H.OnLine Z lYZ /\
    HilbertSpaceLinesParallel Geo lEF lYZ


/--
Wyler affine equality of division positions.

`HilbertWylerSameDivision Geo A E B C F D` means that E divides AB in
the same affine position in which F divides CD.

This is deliberately an affine/incidence relation.  It is not defined
through metric segment ratios.
-/
inductive HilbertWylerSameDivision
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [HSI : HilbertSpaceIncidence Geo] :
    Geo.Point -> Geo.Point -> Geo.Point ->
    Geo.Point -> Geo.Point -> Geo.Point -> Prop

  | refl
      (A E B : Geo.Point) :
      HilbertWylerSameDivision A E B A E B

  | step
      (X E Y F Z : Geo.Point)
      (hStep :
        HilbertWylerDivisionStep
          (Geo := Geo)
          X E Y F Z) :
      HilbertWylerSameDivision
        X E Y
        X F Z

  | symm
      {A E B C F D : Geo.Point}
      (h :
        HilbertWylerSameDivision
          A E B C F D) :
      HilbertWylerSameDivision
        C F D A E B

  | trans
      {A E B C F D P Q R : Geo.Point}
      (h1 :
        HilbertWylerSameDivision
          A E B C F D)
      (h2 :
        HilbertWylerSameDivision
          C F D P Q R) :
      HilbertWylerSameDivision
        A E B P Q R

  | reverse
      {A E B C F D : Geo.Point}
      (h :
        HilbertWylerSameDivision
          A E B C F D) :
      HilbertWylerSameDivision
        B E A D F C


/--
Package a concrete parallel-section configuration as one Wyler
division step.
-/
theorem hilbertWylerSameDivision_of_parallel_sections
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [HSI : HilbertSpaceIncidence Geo]
    (X E Y F Z : Geo.Point)
    (hXEY : Geo.Between X E Y)
    (hXFZ : Geo.Between X F Z)
    (lEF lYZ : Geo.Line)
    (hElEF : H.OnLine E lEF)
    (hFlEF : H.OnLine F lEF)
    (hYlYZ : H.OnLine Y lYZ)
    (hZlYZ : H.OnLine Z lYZ)
    (hParallel :
      HilbertSpaceLinesParallel Geo lEF lYZ) :
    HilbertWylerSameDivision
      (Geo := Geo)
      X E Y
      X F Z := by

  apply HilbertWylerSameDivision.step

  exact
    And.intro hXEY
      (And.intro hXFZ
        (Exists.intro lEF
          (Exists.intro lYZ
            (And.intro hElEF
              (And.intro hFlEF
                (And.intro hYlYZ
                  (And.intro hZlYZ hParallel)))))))


/--
Simultaneous reversal preserves the affine division relation.
-/
theorem hilbertWylerSameDivision_reverse
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [HSI : HilbertSpaceIncidence Geo]
    (A E B C F D : Geo.Point)
    (h :
      HilbertWylerSameDivision
        (Geo := Geo)
        A E B
        C F D) :
    HilbertWylerSameDivision
      (Geo := Geo)
      B E A
      D F C := by

  exact
    HilbertWylerSameDivision.reverse h


/--
Transitivity is the affine V.11 analogue.
-/
theorem hilbertWylerSameDivision_trans
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [HSI : HilbertSpaceIncidence Geo]
    (A E B C F D P Q R : Geo.Point)
    (h1 :
      HilbertWylerSameDivision
        (Geo := Geo)
        A E B
        C F D)
    (h2 :
      HilbertWylerSameDivision
        (Geo := Geo)
        C F D
        P Q R) :
    HilbertWylerSameDivision
      (Geo := Geo)
      A E B
      P Q R := by

  exact
    HilbertWylerSameDivision.trans h1 h2

end Geometry
