import CGJteamLab.Wyler.HilbertWylerInterface

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/--
Euclid XI.9.

If two straight lines are each parallel to the same straight line, and
the three lines are not all contained in one plane, then the first two
lines are parallel to one another.

Wyler form of the spatial argument:

  sigma contains l,n,
  tau   contains m,n,

with sigma and tau distinct.  Choose B on m outside l and let

  omega = Join(l,{B}).

Then r = omega meet tau is a line through B.  A generator argument shows
that r is disjoint from n.  Group IV inside tau identifies r with m.
Thus l and m are coplanar in omega.  A second generator argument shows
that l and m are disjoint.

No proposition-local plane-uniqueness helper is used: equalities of
planes are detected through equal joins generated by a line and an
external point.
-/
theorem euclid_proposition_11_9
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [HSI : HilbertSpaceIncidence Geo]
    [_HSO : HilbertSpaceOrder
      (Geo := Geo) (H := H) (S := S)]
    [HSC : HilbertSpaceCongruence
      (Geo := Geo) (H := H) (S := S)]
    [HSE : HilbertSpaceEuclidean Geo]
    (l m n : Geo.Line)
    (hParallelLN : HilbertSpaceLinesParallel Geo l n)
    (hParallelMN : HilbertSpaceLinesParallel Geo m n)
    (hNoCommonPlane :
      Not (exists omega : S.Plane,
        HilbertLineInPlane Geo l omega /\
        HilbertLineInPlane Geo m omega /\
        HilbertLineInPlane Geo n omega)) :
    HilbertSpaceLinesParallel Geo l m := by

  /-
  The two given parallelisms supply two carrier planes.
  -/
  cases hParallelLN with
  | intro sigma hSigmaData =>
      have hlsigma :
          HilbertLineInPlane Geo l sigma :=
        hSigmaData.1

      have hnsigma :
          HilbertLineInPlane Geo n sigma :=
        hSigmaData.2.1

      have hDisjointLN :
          HilbertLinesDisjoint Geo l n :=
        hSigmaData.2.2

      cases hParallelMN with
      | intro tau hTauData =>
          have hmtau :
              HilbertLineInPlane Geo m tau :=
            hTauData.1

          have hntau :
              HilbertLineInPlane Geo n tau :=
            hTauData.2.1

          have hDisjointMN :
              HilbertLinesDisjoint Geo m n :=
            hTauData.2.2

          /-
          The two carrier planes cannot have the same carrier.
          -/
          have hSigmaTauCarrier :
              Ne
                (HilbertPlaneCarrier3D Geo sigma)
                (HilbertPlaneCarrier3D Geo tau) := by
            intro hCarrierEq

            have hmsigma :
                HilbertLineInPlane Geo m sigma := by
              intro X hXm
              change HilbertPlaneCarrier3D Geo sigma X
              rw [hCarrierEq]
              exact hmtau X hXm

            exact
              hNoCommonPlane
                (Exists.intro sigma
                  (And.intro hlsigma
                    (And.intro hmsigma hnsigma)))

          /-
          In particular l and m are distinct.
          -/
          have hlm : Ne l m := by
            intro hEq

            have hmsigma :
                HilbertLineInPlane Geo m sigma := by
              rw [<- hEq]
              exact hlsigma

            exact
              hNoCommonPlane
                (Exists.intro sigma
                  (And.intro hlsigma
                    (And.intro hmsigma hnsigma)))

          /-
          Choose B on m but outside l.
          -/
          cases
              hilbert_point_on_second_line_off_first
                (Geo := Geo)
                l m hlm with
          | intro B hBData =>
              have hBm : H.OnLine B m :=
                hBData.1

              have hBl : Not (H.OnLine B l) :=
                hBData.2

              have hBtau : S.OnPlane B tau :=
                hmtau B hBm

              have hBn : Not (H.OnLine B n) := by
                intro hBn
                exact
                  hDisjointMN
                    (Exists.intro B
                      (And.intro hBm hBn))

              /-
              omega is generated by l and the external point B.
              -/
              cases
                  hilbert_plane_through_line_and_external_point
                    (Geo := Geo)
                    l B hBl with
              | intro omega hOmegaData =>
                  have hlomega :
                      HilbertLineInPlane Geo l omega :=
                    hOmegaData.1

                  have hBomega :
                      S.OnPlane B omega :=
                    hOmegaData.2.1

                  have hJoinOmegaLB :
                      HilbertJoin3D Geo
                          (HilbertLineCarrier3D Geo l)
                          ({B} : Set Geo.Point) =
                        HilbertPlaneCarrier3D Geo omega :=
                    hilbertJoin3D_line_external_point_eq_planeCarrier
                      (Geo := Geo)
                      omega l B
                      hlomega hBomega hBl

                  /-
                  sigma and omega have different carriers.

                  Otherwise B would lie in sigma.  Then sigma and tau
                  would both be generated by n and the same external
                  point B, forcing their carriers to coincide.
                  -/
                  have hSigmaOmegaCarrier :
                      Ne
                        (HilbertPlaneCarrier3D Geo sigma)
                        (HilbertPlaneCarrier3D Geo omega) := by
                    intro hCarrierEq

                    have hBsigma : S.OnPlane B sigma := by
                      change HilbertPlaneCarrier3D Geo sigma B
                      rw [hCarrierEq]
                      exact hBomega

                    have hJoinSigmaNB :
                        HilbertJoin3D Geo
                            (HilbertLineCarrier3D Geo n)
                            ({B} : Set Geo.Point) =
                          HilbertPlaneCarrier3D Geo sigma :=
                      hilbertJoin3D_line_external_point_eq_planeCarrier
                        (Geo := Geo)
                        sigma n B
                        hnsigma hBsigma hBn

                    have hJoinTauNB :
                        HilbertJoin3D Geo
                            (HilbertLineCarrier3D Geo n)
                            ({B} : Set Geo.Point) =
                          HilbertPlaneCarrier3D Geo tau :=
                      hilbertJoin3D_line_external_point_eq_planeCarrier
                        (Geo := Geo)
                        tau n B
                        hntau hBtau hBn

                    apply hSigmaTauCarrier
                    exact
                      hJoinSigmaNB.symm.trans hJoinTauNB

                  /-
                  omega and tau are distinct, otherwise tau itself would
                  contain l,m,n.
                  -/
                  have hOmegaTau : Ne omega tau := by
                    intro hEq

                    have hltau :
                        HilbertLineInPlane Geo l tau := by
                      rw [<- hEq]
                      exact hlomega

                    exact
                      hNoCommonPlane
                        (Exists.intro tau
                          (And.intro hltau
                            (And.intro hmtau hntau)))

                  /-
                  r is the meet line omega inter tau through B.
                  -/
                  cases
                      hilbertPlaneCarrier3D_inter_eq_lineCarrier
                        (Geo := Geo)
                        omega tau
                        hOmegaTau
                        B hBomega hBtau with
                  | intro r hRData =>
                      have hBr : H.OnLine B r :=
                        hRData.1

                      have hromega :
                          HilbertLineInPlane Geo r omega :=
                        hRData.2.1

                      have hrtau :
                          HilbertLineInPlane Geo r tau :=
                        hRData.2.2.1

                      have _hMeet :
                          Set.inter
                              (HilbertPlaneCarrier3D Geo omega)
                              (HilbertPlaneCarrier3D Geo tau) =
                            HilbertLineCarrier3D Geo r :=
                        hRData.2.2.2

                      /-
                      r is disjoint from n.

                      A common point P would make sigma and omega both
                      generated by l and the same external point P.
                      -/
                      have hDisjointRN :
                          HilbertLinesDisjoint Geo r n := by
                        intro hMeet

                        cases hMeet with
                        | intro P hPData =>
                            have hPr : H.OnLine P r :=
                              hPData.1

                            have hPn : H.OnLine P n :=
                              hPData.2

                            have hPomega : S.OnPlane P omega :=
                              hromega P hPr

                            have hPsigma : S.OnPlane P sigma :=
                              hnsigma P hPn

                            have hPl : Not (H.OnLine P l) := by
                              intro hPl
                              exact
                                hDisjointLN
                                  (Exists.intro P
                                    (And.intro hPl hPn))

                            have hJoinSigmaLP :
                                HilbertJoin3D Geo
                                    (HilbertLineCarrier3D Geo l)
                                    ({P} : Set Geo.Point) =
                                  HilbertPlaneCarrier3D Geo sigma :=
                              hilbertJoin3D_line_external_point_eq_planeCarrier
                                (Geo := Geo)
                                sigma l P
                                hlsigma hPsigma hPl

                            have hJoinOmegaLP :
                                HilbertJoin3D Geo
                                    (HilbertLineCarrier3D Geo l)
                                    ({P} : Set Geo.Point) =
                                  HilbertPlaneCarrier3D Geo omega :=
                              hilbertJoin3D_line_external_point_eq_planeCarrier
                                (Geo := Geo)
                                omega l P
                                hlomega hPomega hPl

                            apply hSigmaOmegaCarrier
                            exact
                              hJoinSigmaLP.symm.trans hJoinOmegaLP

                      /-
                      Group IV inside tau: through B there is a unique
                      line disjoint from n.  Both r and m satisfy this,
                      hence r = m.
                      -/
                      have hrm : r = m :=
                        HilbertSpaceEuclidean.parallel_unique_in_plane
                          (Geo := Geo)
                          tau
                          n hntau
                          B hBtau hBn
                          r m
                          hrtau hmtau
                          hBr hDisjointRN
                          hBm hDisjointMN

                      have hmomega :
                          HilbertLineInPlane Geo m omega := by
                        rw [<- hrm]
                        exact hromega

                      /-
                      Finally l and m are disjoint.

                      If P lay on both, sigma and tau would both be
                      generated by n and the same external point P.
                      -/
                      have hDisjointLM :
                          HilbertLinesDisjoint Geo l m := by
                        intro hMeet

                        cases hMeet with
                        | intro P hPData =>
                            have hPl : H.OnLine P l :=
                              hPData.1

                            have hPm : H.OnLine P m :=
                              hPData.2

                            have hPn : Not (H.OnLine P n) := by
                              intro hPn
                              exact
                                hDisjointLN
                                  (Exists.intro P
                                    (And.intro hPl hPn))

                            have hPsigma : S.OnPlane P sigma :=
                              hlsigma P hPl

                            have hPtau : S.OnPlane P tau :=
                              hmtau P hPm

                            have hJoinSigmaNP :
                                HilbertJoin3D Geo
                                    (HilbertLineCarrier3D Geo n)
                                    ({P} : Set Geo.Point) =
                                  HilbertPlaneCarrier3D Geo sigma :=
                              hilbertJoin3D_line_external_point_eq_planeCarrier
                                (Geo := Geo)
                                sigma n P
                                hnsigma hPsigma hPn

                            have hJoinTauNP :
                                HilbertJoin3D Geo
                                    (HilbertLineCarrier3D Geo n)
                                    ({P} : Set Geo.Point) =
                                  HilbertPlaneCarrier3D Geo tau :=
                              hilbertJoin3D_line_external_point_eq_planeCarrier
                                (Geo := Geo)
                                tau n P
                                hntau hPtau hPn

                            apply hSigmaTauCarrier
                            exact
                              hJoinSigmaNP.symm.trans hJoinTauNP

                      /-
                      The target spatial parallelism is now the explicit
                      pair: common carrier plane omega + disjointness.
                      -/
                      exact
                        Exists.intro omega
                          (And.intro hlomega
                            (And.intro hmomega hDisjointLM))

end Geometry
