import CGJteamLab.Wyler.HilbertWylerInterface
import CGJteamLab.Wyler.Proposition11_11
import CGJteamLab.Wyler.Proposition11_9
import CGJteamLab.Wyler.Proposition11_4
import CGJteamLab.Wyler.Proposition11_14

namespace Geometry

universe u

variable (Geo : Geometry.Geo)

/--
Euclid XI.15 in Wyler form.

The proof body is intentionally not factored into proposition-local
aggregate helpers.  The source hypothesis that the four displayed lines
are not all coplanar first gives pi != rho; the corresponding plane join
is then recorded as the full ambient 3-space.

Visible construction:

1. prove B is outside rho by comparing joins generated by m1,m2 and B;
2. use XI.11 to construct the normal n from B to rho, with foot G;
3. for the first reference direction m1:
   - if G lies on m1, take q1 = m1;
   - otherwise construct q1 through G parallel to m1 in the generated
     slice sigma1, and retain the exact join certificates

       Join(m1,{G}) = carrier(sigma1),
       Join(m1,q1)  = carrier(sigma1).

   The same generator Join(m1,{G}) identifies the constructed line q1
   as a line of rho.

This is the production Wyler proof of Euclid XI.15.
-/
theorem euclid_proposition_11_15
    [H : HilbertIncidence Geo]
    [HilbertPlaneIncidence Geo]
    [S : HilbertSpacePrimitive Geo]
    [HSI : HilbertSpaceIncidence Geo]
    [_HSO : HilbertSpaceOrder
      (Geo := Geo) (H := H) (S := S)]
    [HSC : HilbertSpaceCongruence
      (Geo := Geo) (H := H) (S := S)]
    [HSE : HilbertSpaceEuclidean Geo]
    (pi rho : S.Plane)
    (l1 l2 : PlaneLine Geo pi)
    (m1 m2 : PlaneLine Geo rho)
    (B : PlanePoint Geo pi)
    (hBl1 : H.OnLine B.1 l1.1)
    (hBl2 : H.OnLine B.1 l2.1)
    (hl12 : Ne l1 l2)
    (hParallel1 :
      HilbertSpaceLinesParallel Geo l1.1 m1.1)
    (hParallel2 :
      HilbertSpaceLinesParallel Geo l2.1 m2.1)
    (hNoCommonPlane :
      Not (exists omega : S.Plane,
        HilbertLineInPlane Geo l1.1 omega /\
        HilbertLineInPlane Geo l2.1 omega /\
        HilbertLineInPlane Geo m1.1 omega /\
        HilbertLineInPlane Geo m2.1 omega)) :
    HilbertSpacePlanesParallel Geo pi rho := by

  ----------------------------------------------------------------------
  -- Step 0. The two displayed carrier planes are distinct.
  --
  -- If pi = rho, then all four given lines lie in that same plane,
  -- contrary to the XI.15 source hypothesis.
  ----------------------------------------------------------------------

  have hPlanesNe : Ne pi rho := by
    intro hPiRho

    have hm1pi :
        HilbertLineInPlane Geo m1.1 pi := by
      rw [hPiRho]
      exact m1.2

    have hm2pi :
        HilbertLineInPlane Geo m2.1 pi := by
      rw [hPiRho]
      exact m2.2

    exact
      hNoCommonPlane
        (Exists.intro pi
          (And.intro l1.2
            (And.intro l2.2
              (And.intro hm1pi hm2pi))))

  ----------------------------------------------------------------------
  -- Wyler rank certificate:
  -- two distinct planes generate the whole ambient 3-space.
  --
  -- This records the global flat geometry of XI.15.  It does not
  -- replace the later metric argument.
  ----------------------------------------------------------------------

  have _hJoinRank3 :
      HilbertJoin3D Geo
          (HilbertPlaneCarrier3D Geo pi)
          (HilbertPlaneCarrier3D Geo rho) =
        (Set.univ : Set Geo.Point) :=
    hilbertJoin3D_two_distinct_planes_eq_univ
      (Geo := Geo)
      pi rho hPlanesNe

  ----------------------------------------------------------------------
  -- Step 1. B is outside rho.
  --
  -- Assume B lies in rho. For l1 || m1, let sigma1 be their carrier
  -- plane. Since B lies on l1, B lies in sigma1 and is outside m1.
  -- Therefore the same generator Join(m1,{B}) is both carrier(sigma1)
  -- and carrier(rho).
  ----------------------------------------------------------------------

  have hBoffRho : Not (S.OnPlane B.1 rho) := by
    intro hBrho

    cases hParallel1 with
    | intro tau1 hTau1 =>
        have hl1tau1 :
            HilbertLineInPlane Geo l1.1 tau1 :=
          hTau1.1

        have hm1tau1 :
            HilbertLineInPlane Geo m1.1 tau1 :=
          hTau1.2.1

        have hDisjoint1 :
            HilbertLinesDisjoint Geo l1.1 m1.1 :=
          hTau1.2.2

        have hBtau1 : S.OnPlane B.1 tau1 :=
          hl1tau1 B.1 hBl1

        have hBm1 : Not (H.OnLine B.1 m1.1) := by
          intro hBm1
          exact
            hDisjoint1
              (Exists.intro B.1
                (And.intro hBl1 hBm1))

        have hJoinTau1 :
            HilbertJoin3D Geo
                (HilbertLineCarrier3D Geo m1.1)
                ({B.1} : Set Geo.Point) =
              HilbertPlaneCarrier3D Geo tau1 :=
          hilbertJoin3D_line_external_point_eq_planeCarrier
            (Geo := Geo)
            tau1 m1.1 B.1
            hm1tau1 hBtau1 hBm1

        have hJoinRho1 :
            HilbertJoin3D Geo
                (HilbertLineCarrier3D Geo m1.1)
                ({B.1} : Set Geo.Point) =
              HilbertPlaneCarrier3D Geo rho :=
          hilbertJoin3D_line_external_point_eq_planeCarrier
            (Geo := Geo)
            rho m1.1 B.1
            m1.2 hBrho hBm1

        have hCarrierTau1Rho :
            HilbertPlaneCarrier3D Geo tau1 =
              HilbertPlaneCarrier3D Geo rho :=
          hJoinTau1.symm.trans hJoinRho1

        have hl1rho :
            HilbertLineInPlane Geo l1.1 rho := by
          intro X hXl1
          change HilbertPlaneCarrier3D Geo rho X
          rw [<- hCarrierTau1Rho]
          exact hl1tau1 X hXl1

        ----------------------------------------------------------------
        -- Repeat the same generator argument for l2 || m2.
        ----------------------------------------------------------------

        cases hParallel2 with
        | intro tau2 hTau2 =>
            have hl2tau2 :
                HilbertLineInPlane Geo l2.1 tau2 :=
              hTau2.1

            have hm2tau2 :
                HilbertLineInPlane Geo m2.1 tau2 :=
              hTau2.2.1

            have hDisjoint2 :
                HilbertLinesDisjoint Geo l2.1 m2.1 :=
              hTau2.2.2

            have hBtau2 : S.OnPlane B.1 tau2 :=
              hl2tau2 B.1 hBl2

            have hBm2 : Not (H.OnLine B.1 m2.1) := by
              intro hBm2
              exact
                hDisjoint2
                  (Exists.intro B.1
                    (And.intro hBl2 hBm2))

            have hJoinTau2 :
                HilbertJoin3D Geo
                    (HilbertLineCarrier3D Geo m2.1)
                    ({B.1} : Set Geo.Point) =
                  HilbertPlaneCarrier3D Geo tau2 :=
              hilbertJoin3D_line_external_point_eq_planeCarrier
                (Geo := Geo)
                tau2 m2.1 B.1
                hm2tau2 hBtau2 hBm2

            have hJoinRho2 :
                HilbertJoin3D Geo
                    (HilbertLineCarrier3D Geo m2.1)
                    ({B.1} : Set Geo.Point) =
                  HilbertPlaneCarrier3D Geo rho :=
              hilbertJoin3D_line_external_point_eq_planeCarrier
                (Geo := Geo)
                rho m2.1 B.1
                m2.2 hBrho hBm2

            have hCarrierTau2Rho :
                HilbertPlaneCarrier3D Geo tau2 =
                  HilbertPlaneCarrier3D Geo rho :=
              hJoinTau2.symm.trans hJoinRho2

            have hl2rho :
                HilbertLineInPlane Geo l2.1 rho := by
              intro X hXl2
              change HilbertPlaneCarrier3D Geo rho X
              rw [<- hCarrierTau2Rho]
              exact hl2tau2 X hXl2

            ----------------------------------------------------------------
            -- l1,l2 are distinct and meet at B. Hence they determine one
            -- plane. Both pi and rho contain them.
            ----------------------------------------------------------------

            have hl12Ambient : Ne l1.1 l2.1 := by
              intro hEq
              apply hl12
              exact Subtype.ext hEq

            cases
                hilbert_plane_through_two_intersecting_lines
                  (Geo := Geo)
                  l1.1 l2.1
                  hl12Ambient
                  B.1
                  hBl1 hBl2 with
            | intro omega hOmega =>
                have hPiOmega : pi = omega :=
                  hOmega.2.2 pi l1.2 l2.2

                have hRhoOmega : rho = omega :=
                  hOmega.2.2 rho hl1rho hl2rho

                exact
                  hPlanesNe
                    (hPiOmega.trans hRhoOmega.symm)

  ----------------------------------------------------------------------
  -- Step 2. XI.11: construct n through B perpendicular to rho.
  ----------------------------------------------------------------------

  cases
      euclid_proposition_11_11
        (Geo := Geo)
        rho B.1 hBoffRho with
  | intro n hN =>
      cases hN with
      | intro G hG =>
          have hBn : H.OnLine B.1 n :=
            hG.1

          have hNormalRho :
              HilbertLinePerpendicularPlaneAt Geo n rho G :=
            hG.2

          have hNormalInc :=
            HilbertLinePerpendicularPlaneAt.incidence
              (Geo := Geo)
              hNormalRho

          have hGrho : S.OnPlane G rho :=
            hNormalInc.2


          ----------------------------------------------------------------
          -- Step 3. First reference direction through G.
          --
          -- This stays local to XI.15: no proposition-level wrapper.
          -- We retain the exact Wyler join certificates in the generic
          -- branch.
          ----------------------------------------------------------------

          have hQ1Data :
              exists q1 : Geo.Line,
                H.OnLine G q1 /\
                HilbertLineInPlane Geo q1 rho /\
                (q1 = m1.1 \/
                  exists sigma1 : S.Plane,
                    HilbertJoin3D Geo
                        (HilbertLineCarrier3D Geo m1.1)
                        ({G} : Set Geo.Point) =
                      HilbertPlaneCarrier3D Geo sigma1 /\
                    HilbertSpaceLinesParallel Geo m1.1 q1 /\
                    HilbertJoin3D Geo
                        (HilbertLineCarrier3D Geo m1.1)
                        (HilbertLineCarrier3D Geo q1) =
                      HilbertPlaneCarrier3D Geo sigma1) := by

            by_cases hGm1 : H.OnLine G m1.1

            next =>
              exact
                Exists.intro m1.1
                  (And.intro hGm1
                    (And.intro m1.2
                      (Or.inl rfl)))

            next =>
              cases
                  hilbert_XI12_generated_slice_parallel_native
                    (Geo := Geo)
                    m1.1 G hGm1 with
              | intro sigma1 hSlice1 =>
                  cases hSlice1 with
                  | intro q1 hQ1 =>
                      have hJoinM1G :
                          HilbertJoin3D Geo
                              (HilbertLineCarrier3D Geo m1.1)
                              ({G} : Set Geo.Point) =
                            HilbertPlaneCarrier3D Geo sigma1 :=
                        hQ1.1

                      have hGq1 : H.OnLine G q1 :=
                        hQ1.2.1

                      have hParallelM1Q1 :
                          HilbertSpaceLinesParallel Geo m1.1 q1 :=
                        hQ1.2.2.1

                      have hJoinM1Q1 :
                          HilbertJoin3D Geo
                              (HilbertLineCarrier3D Geo m1.1)
                              (HilbertLineCarrier3D Geo q1) =
                            HilbertPlaneCarrier3D Geo sigma1 :=
                        hQ1.2.2.2

                      have hJoinRho1 :
                          HilbertJoin3D Geo
                              (HilbertLineCarrier3D Geo m1.1)
                              ({G} : Set Geo.Point) =
                            HilbertPlaneCarrier3D Geo rho :=
                        hilbertJoin3D_line_external_point_eq_planeCarrier
                          (Geo := Geo)
                          rho m1.1 G
                          m1.2 hGrho hGm1

                      cases hParallelM1Q1 with
                      | intro tau1 hTau1 =>
                          have hm1tau1 :
                              HilbertLineInPlane Geo m1.1 tau1 :=
                            hTau1.1

                          have hq1tau1 :
                              HilbertLineInPlane Geo q1 tau1 :=
                            hTau1.2.1

                          have hDisjointM1Q1 :
                              HilbertLinesDisjoint Geo m1.1 q1 :=
                            hTau1.2.2

                          have hGtau1 : S.OnPlane G tau1 :=
                            hq1tau1 G hGq1

                          have hJoinTau1 :
                              HilbertJoin3D Geo
                                  (HilbertLineCarrier3D Geo m1.1)
                                  ({G} : Set Geo.Point) =
                                HilbertPlaneCarrier3D Geo tau1 :=
                            hilbertJoin3D_line_external_point_eq_planeCarrier
                              (Geo := Geo)
                              tau1 m1.1 G
                              hm1tau1 hGtau1 hGm1

                          have hCarrierTau1Rho :
                              HilbertPlaneCarrier3D Geo tau1 =
                                HilbertPlaneCarrier3D Geo rho :=
                            hJoinTau1.symm.trans hJoinRho1

                          have hq1rho :
                              HilbertLineInPlane Geo q1 rho := by
                            intro X hXq1
                            change HilbertPlaneCarrier3D Geo rho X
                            rw [<- hCarrierTau1Rho]
                            exact hq1tau1 X hXq1

                          have hParallelM1Q1' :
                              HilbertSpaceLinesParallel Geo m1.1 q1 :=
                            Exists.intro tau1
                              (And.intro hm1tau1
                                (And.intro hq1tau1 hDisjointM1Q1))

                          exact
                            Exists.intro q1
                              (And.intro hGq1
                                (And.intro hq1rho
                                  (Or.inr
                                    (Exists.intro sigma1
                                      (And.intro hJoinM1G
                                        (And.intro
                                          hParallelM1Q1'
                                          hJoinM1Q1))))))

          cases hQ1Data with
          | intro q1 hQ1Data' =>
              have hGq1 : H.OnLine G q1 :=
                hQ1Data'.1

              have hq1rho :
                  HilbertLineInPlane Geo q1 rho :=
                hQ1Data'.2.1

              have hQ1Structure :=
                hQ1Data'.2.2

              ----------------------------------------------------------------
              -- Step 4. Second reference direction through G.
              --
              -- Repeat the same Wyler construction for m2. Again the
              -- generated slice is visible through exact join identities.
              ----------------------------------------------------------------

              have hQ2Data :
                  exists q2 : Geo.Line,
                    H.OnLine G q2 /\
                    HilbertLineInPlane Geo q2 rho /\
                    (q2 = m2.1 \/
                      exists sigma2 : S.Plane,
                        HilbertJoin3D Geo
                            (HilbertLineCarrier3D Geo m2.1)
                            ({G} : Set Geo.Point) =
                          HilbertPlaneCarrier3D Geo sigma2 /\
                        HilbertSpaceLinesParallel Geo m2.1 q2 /\
                        HilbertJoin3D Geo
                            (HilbertLineCarrier3D Geo m2.1)
                            (HilbertLineCarrier3D Geo q2) =
                          HilbertPlaneCarrier3D Geo sigma2) := by

                by_cases hGm2 : H.OnLine G m2.1

                next =>
                  exact
                    Exists.intro m2.1
                      (And.intro hGm2
                        (And.intro m2.2
                          (Or.inl rfl)))

                next =>
                  cases
                      hilbert_XI12_generated_slice_parallel_native
                        (Geo := Geo)
                        m2.1 G hGm2 with
                  | intro sigma2 hSlice2 =>
                      cases hSlice2 with
                      | intro q2 hQ2 =>
                          have hJoinM2G :
                              HilbertJoin3D Geo
                                  (HilbertLineCarrier3D Geo m2.1)
                                  ({G} : Set Geo.Point) =
                                HilbertPlaneCarrier3D Geo sigma2 :=
                            hQ2.1

                          have hGq2 : H.OnLine G q2 :=
                            hQ2.2.1

                          have hParallelM2Q2 :
                              HilbertSpaceLinesParallel Geo m2.1 q2 :=
                            hQ2.2.2.1

                          have hJoinM2Q2 :
                              HilbertJoin3D Geo
                                  (HilbertLineCarrier3D Geo m2.1)
                                  (HilbertLineCarrier3D Geo q2) =
                                HilbertPlaneCarrier3D Geo sigma2 :=
                            hQ2.2.2.2

                          have hJoinRho2 :
                              HilbertJoin3D Geo
                                  (HilbertLineCarrier3D Geo m2.1)
                                  ({G} : Set Geo.Point) =
                                HilbertPlaneCarrier3D Geo rho :=
                            hilbertJoin3D_line_external_point_eq_planeCarrier
                              (Geo := Geo)
                              rho m2.1 G
                              m2.2 hGrho hGm2

                          cases hParallelM2Q2 with
                          | intro tau2 hTau2 =>
                              have hm2tau2 :
                                  HilbertLineInPlane Geo m2.1 tau2 :=
                                hTau2.1

                              have hq2tau2 :
                                  HilbertLineInPlane Geo q2 tau2 :=
                                hTau2.2.1

                              have hDisjointM2Q2 :
                                  HilbertLinesDisjoint Geo m2.1 q2 :=
                                hTau2.2.2

                              have hGtau2 : S.OnPlane G tau2 :=
                                hq2tau2 G hGq2

                              have hJoinTau2 :
                                  HilbertJoin3D Geo
                                      (HilbertLineCarrier3D Geo m2.1)
                                      ({G} : Set Geo.Point) =
                                    HilbertPlaneCarrier3D Geo tau2 :=
                                hilbertJoin3D_line_external_point_eq_planeCarrier
                                  (Geo := Geo)
                                  tau2 m2.1 G
                                  hm2tau2 hGtau2 hGm2

                              have hCarrierTau2Rho :
                                  HilbertPlaneCarrier3D Geo tau2 =
                                    HilbertPlaneCarrier3D Geo rho :=
                                hJoinTau2.symm.trans hJoinRho2

                              have hq2rho :
                                  HilbertLineInPlane Geo q2 rho := by
                                intro X hXq2
                                change HilbertPlaneCarrier3D Geo rho X
                                rw [<- hCarrierTau2Rho]
                                exact hq2tau2 X hXq2

                              have hParallelM2Q2' :
                                  HilbertSpaceLinesParallel Geo m2.1 q2 :=
                                Exists.intro tau2
                                  (And.intro hm2tau2
                                    (And.intro hq2tau2 hDisjointM2Q2))

                              exact
                                Exists.intro q2
                                  (And.intro hGq2
                                    (And.intro hq2rho
                                      (Or.inr
                                        (Exists.intro sigma2
                                          (And.intro hJoinM2G
                                            (And.intro
                                              hParallelM2Q2'
                                              hJoinM2Q2))))))

              cases hQ2Data with
              | intro q2 hQ2Data' =>
                  have hGq2 : H.OnLine G q2 :=
                    hQ2Data'.1

                  have hq2rho :
                      HilbertLineInPlane Geo q2 rho :=
                    hQ2Data'.2.1

                  have hQ2Structure :=
                    hQ2Data'.2.2

                  ----------------------------------------------------------------
                  -- Step 5. Transport the first parallel direction:
                  --
                  --     l1 || m1,   m1 || q1   ==>   l1 || q1.
                  --
                  -- If q1 = m1 this is immediate.
                  --
                  -- Otherwise:
                  --   * if l1,q1,m1 are not coplanar, use XI.9;
                  --   * if they are coplanar, any intersection P of l1 and q1
                  --     would give two distinct parallels through P to m1,
                  --     contradicting Group IV.
                  ----------------------------------------------------------------

                  have hParallelL1Q1 :
                      HilbertSpaceLinesParallel Geo l1.1 q1 := by

                    cases hQ1Structure with
                    | inl hQ1Eq =>
                        simpa [hQ1Eq] using hParallel1

                    | inr hQ1Generic =>
                        cases hQ1Generic with
                        | intro sigma1 hSigma1 =>
                            have hParallelM1Q1 :
                                HilbertSpaceLinesParallel Geo m1.1 q1 :=
                              hSigma1.2.1

                            have hParallelQ1M1 :
                                HilbertSpaceLinesParallel Geo q1 m1.1 := by
                              cases hParallelM1Q1 with
                              | intro tau hTau =>
                                  have hm1tau :
                                      HilbertLineInPlane Geo m1.1 tau :=
                                    hTau.1

                                  have hq1tau :
                                      HilbertLineInPlane Geo q1 tau :=
                                    hTau.2.1

                                  have hDisjointM1Q1 :
                                      HilbertLinesDisjoint Geo m1.1 q1 :=
                                    hTau.2.2

                                  have hDisjointQ1M1 :
                                      HilbertLinesDisjoint Geo q1 m1.1 := by
                                    intro hMeet
                                    cases hMeet with
                                    | intro X hX =>
                                        exact
                                          hDisjointM1Q1
                                            (Exists.intro X
                                              (And.intro hX.2 hX.1))

                                  exact
                                    Exists.intro tau
                                      (And.intro hq1tau
                                        (And.intro hm1tau hDisjointQ1M1))

                            have hl1q1 : Ne l1.1 q1 := by
                              intro hEq

                              have hBq1 : H.OnLine B.1 q1 := by
                                rw [<- hEq]
                                exact hBl1

                              exact
                                hBoffRho
                                  (hq1rho B.1 hBq1)

                            by_cases hCoplanar :
                                exists omega : S.Plane,
                                  HilbertLineInPlane Geo l1.1 omega /\
                                  HilbertLineInPlane Geo q1 omega /\
                                  HilbertLineInPlane Geo m1.1 omega

                            next =>
                              cases hCoplanar with
                              | intro omega hOmega =>
                                  have hl1omega :
                                      HilbertLineInPlane Geo l1.1 omega :=
                                    hOmega.1

                                  have hq1omega :
                                      HilbertLineInPlane Geo q1 omega :=
                                    hOmega.2.1

                                  have hm1omega :
                                      HilbertLineInPlane Geo m1.1 omega :=
                                    hOmega.2.2

                                  have hDisjointL1M1 :
                                      HilbertLinesDisjoint Geo l1.1 m1.1 := by
                                    cases hParallel1 with
                                    | intro tau hTau =>
                                        exact hTau.2.2

                                  have hDisjointQ1M1 :
                                      HilbertLinesDisjoint Geo q1 m1.1 := by
                                    cases hParallelQ1M1 with
                                    | intro tau hTau =>
                                        exact hTau.2.2

                                  have hDisjointL1Q1 :
                                      HilbertLinesDisjoint Geo l1.1 q1 := by
                                    intro hMeet

                                    cases hMeet with
                                    | intro P hP =>
                                        have hPl1 : H.OnLine P l1.1 :=
                                          hP.1

                                        have hPq1 : H.OnLine P q1 :=
                                          hP.2

                                        have hPomega : S.OnPlane P omega :=
                                          hl1omega P hPl1

                                        have hPm1 :
                                            Not (H.OnLine P m1.1) := by
                                          intro hPm1
                                          exact
                                            hDisjointL1M1
                                              (Exists.intro P
                                                (And.intro hPl1 hPm1))

                                        have hEq :
                                            l1.1 = q1 :=
                                          HilbertSpaceEuclidean.parallel_unique_in_plane
                                            (Geo := Geo)
                                            omega
                                            m1.1 hm1omega
                                            P hPomega hPm1
                                            l1.1 q1
                                            hl1omega hq1omega
                                            hPl1 hDisjointL1M1
                                            hPq1 hDisjointQ1M1

                                        exact hl1q1 hEq

                                  exact
                                    Exists.intro omega
                                      (And.intro hl1omega
                                        (And.intro hq1omega
                                          hDisjointL1Q1))

                            next =>
                              exact
                                euclid_proposition_11_9
                                  (Geo := Geo)
                                  l1.1 q1 m1.1
                                  hParallel1
                                  hParallelQ1M1
                                  hCoplanar

                  ----------------------------------------------------------------
                  -- Step 6. The same argument for the second direction.
                  ----------------------------------------------------------------

                  have hParallelL2Q2 :
                      HilbertSpaceLinesParallel Geo l2.1 q2 := by

                    cases hQ2Structure with
                    | inl hQ2Eq =>
                        simpa [hQ2Eq] using hParallel2

                    | inr hQ2Generic =>
                        cases hQ2Generic with
                        | intro sigma2 hSigma2 =>
                            have hParallelM2Q2 :
                                HilbertSpaceLinesParallel Geo m2.1 q2 :=
                              hSigma2.2.1

                            have hParallelQ2M2 :
                                HilbertSpaceLinesParallel Geo q2 m2.1 := by
                              cases hParallelM2Q2 with
                              | intro tau hTau =>
                                  have hm2tau :
                                      HilbertLineInPlane Geo m2.1 tau :=
                                    hTau.1

                                  have hq2tau :
                                      HilbertLineInPlane Geo q2 tau :=
                                    hTau.2.1

                                  have hDisjointM2Q2 :
                                      HilbertLinesDisjoint Geo m2.1 q2 :=
                                    hTau.2.2

                                  have hDisjointQ2M2 :
                                      HilbertLinesDisjoint Geo q2 m2.1 := by
                                    intro hMeet
                                    cases hMeet with
                                    | intro X hX =>
                                        exact
                                          hDisjointM2Q2
                                            (Exists.intro X
                                              (And.intro hX.2 hX.1))

                                  exact
                                    Exists.intro tau
                                      (And.intro hq2tau
                                        (And.intro hm2tau hDisjointQ2M2))

                            have hl2q2 : Ne l2.1 q2 := by
                              intro hEq

                              have hBq2 : H.OnLine B.1 q2 := by
                                rw [<- hEq]
                                exact hBl2

                              exact
                                hBoffRho
                                  (hq2rho B.1 hBq2)

                            by_cases hCoplanar :
                                exists omega : S.Plane,
                                  HilbertLineInPlane Geo l2.1 omega /\
                                  HilbertLineInPlane Geo q2 omega /\
                                  HilbertLineInPlane Geo m2.1 omega

                            next =>
                              cases hCoplanar with
                              | intro omega hOmega =>
                                  have hl2omega :
                                      HilbertLineInPlane Geo l2.1 omega :=
                                    hOmega.1

                                  have hq2omega :
                                      HilbertLineInPlane Geo q2 omega :=
                                    hOmega.2.1

                                  have hm2omega :
                                      HilbertLineInPlane Geo m2.1 omega :=
                                    hOmega.2.2

                                  have hDisjointL2M2 :
                                      HilbertLinesDisjoint Geo l2.1 m2.1 := by
                                    cases hParallel2 with
                                    | intro tau hTau =>
                                        exact hTau.2.2

                                  have hDisjointQ2M2 :
                                      HilbertLinesDisjoint Geo q2 m2.1 := by
                                    cases hParallelQ2M2 with
                                    | intro tau hTau =>
                                        exact hTau.2.2

                                  have hDisjointL2Q2 :
                                      HilbertLinesDisjoint Geo l2.1 q2 := by
                                    intro hMeet

                                    cases hMeet with
                                    | intro P hP =>
                                        have hPl2 : H.OnLine P l2.1 :=
                                          hP.1

                                        have hPq2 : H.OnLine P q2 :=
                                          hP.2

                                        have hPomega : S.OnPlane P omega :=
                                          hl2omega P hPl2

                                        have hPm2 :
                                            Not (H.OnLine P m2.1) := by
                                          intro hPm2
                                          exact
                                            hDisjointL2M2
                                              (Exists.intro P
                                                (And.intro hPl2 hPm2))

                                        have hEq :
                                            l2.1 = q2 :=
                                          HilbertSpaceEuclidean.parallel_unique_in_plane
                                            (Geo := Geo)
                                            omega
                                            m2.1 hm2omega
                                            P hPomega hPm2
                                            l2.1 q2
                                            hl2omega hq2omega
                                            hPl2 hDisjointL2M2
                                            hPq2 hDisjointQ2M2

                                        exact hl2q2 hEq

                                  exact
                                    Exists.intro omega
                                      (And.intro hl2omega
                                        (And.intro hq2omega
                                          hDisjointL2Q2))

                            next =>
                              exact
                                euclid_proposition_11_9
                                  (Geo := Geo)
                                  l2.1 q2 m2.1
                                  hParallel2
                                  hParallelQ2M2
                                  hCoplanar

                  ----------------------------------------------------------------
                  -- Step 7. Metric transport across one parallel pair.
                  --
                  -- This block stays local to XI.15.
                  --
                  -- q lies in rho through G and n is perpendicular to rho,
                  -- so n is perpendicular to q at G. Since l || q, the
                  -- common carrier plane of l,q also contains the transversal
                  -- n through the two distinct feet G and B0.
                  --
                  -- Inside that plane erect p through B0 perpendicular to n.
                  -- Neutral I.27 makes p disjoint from q; Group IV then gives
                  -- p = l. Thus n is perpendicular to l at B0.
                  ----------------------------------------------------------------

                  have hTransportAcrossParallel :
                      forall
                        (l q : Geo.Line)
                        (B0 : Geo.Point),
                        HilbertSpaceLinesParallel Geo l q ->
                        H.OnLine B0 l ->
                        H.OnLine B0 n ->
                        H.OnLine G q ->
                        HilbertLineInPlane Geo q rho ->
                        HilbertLinesPerpendicularAt Geo n l B0 := by

                    intro l q B0 hParallelLQ hB0l hB0n hGq hqrho0

                    have hGn : H.OnLine G n :=
                      hNormalInc.1

                    have hPerpNQ :
                        HilbertLinesPerpendicularAt Geo n q G :=
                      HilbertLinePerpendicularPlaneAt.perpendicular_to_line
                        (Geo := Geo)
                        hNormalRho
                        hqrho0
                        hGq

                    have hPerpQn :
                        HilbertLinesPerpendicularAt Geo q n G :=
                      hilbertLinesPerpendicularAt_symm_wyler
                        (Geo := Geo)
                        n q G
                        hPerpNQ

                    have hGB0 : Ne G B0 := by
                      intro hEq
                      subst B0

                      cases hParallelLQ with
                      | intro sigma hSigma =>
                          have hDisjointLQ :
                              HilbertLinesDisjoint Geo l q :=
                            hSigma.2.2

                          exact
                            hDisjointLQ
                              (Exists.intro G
                                (And.intro hB0l hGq))

                    cases hParallelLQ with
                    | intro sigma hSigma =>
                        have hlsigma :
                            HilbertLineInPlane Geo l sigma :=
                          hSigma.1

                        have hqsigma :
                            HilbertLineInPlane Geo q sigma :=
                          hSigma.2.1

                        have hDisjointLQ :
                            HilbertLinesDisjoint Geo l q :=
                          hSigma.2.2

                        have hB0sigma : S.OnPlane B0 sigma :=
                          hlsigma B0 hB0l

                        have hGsigma : S.OnPlane G sigma :=
                          hqsigma G hGq

                        have hnsigma :
                            HilbertLineInPlane Geo n sigma :=
                          HilbertSpaceIncidence.line_in_plane
                            (Geo := Geo)
                            G B0 hGB0
                            n hGn hB0n
                            sigma hGsigma hB0sigma

                        let Gp : PlanePoint Geo sigma :=
                          { val := G, property := hGsigma }

                        let Bp : PlanePoint Geo sigma :=
                          { val := B0, property := hB0sigma }

                        let np : PlaneLine Geo sigma :=
                          { val := n, property := hnsigma }

                        have hGBp : Ne Gp Bp := by
                          intro hEq
                          apply hGB0
                          exact congrArg Subtype.val hEq

                        have hGnp :
                            PlaneOnLine Geo Gp np :=
                          hGn

                        have hBnp :
                            PlaneOnLine Geo Bp np :=
                          hB0n

                        cases
                            HilbertOrder.between_extension
                              (Geo := PlaneGeo Geo sigma)
                              Gp Bp hGBp with
                        | intro Xp hGBX =>
                            cases
                                hilbert_right_angle_exists_nondegenerate
                                  (PlaneGeo Geo sigma)
                                  Gp Bp Xp hGBX with
                            | intro Yp hY =>
                                have hNonGBY :=
                                  hY.1

                                have hRightGBY :=
                                  hY.2

                                have hBYp : Ne Bp Yp := by
                                  intro hEq
                                  subst Yp
                                  apply hNonGBY
                                  exact
                                    Exists.intro np
                                      (And.intro hGnp
                                        (And.intro hBnp hBnp))

                                cases
                                    HilbertPlaneIncidence.line_through
                                      (Geo := PlaneGeo Geo sigma)
                                      Bp Yp hBYp with
                                | intro pp hP =>
                                    have hBpp :=
                                      hP.1

                                    have hYpp :=
                                      hP.2

                                    have hPerpNpPp :
                                        HilbertLinesPerpendicularAt
                                          (PlaneGeo Geo sigma)
                                          np pp Bp := by
                                      refine And.intro hBnp ?_
                                      refine And.intro hBpp ?_
                                      refine Exists.intro Gp ?_
                                      refine Exists.intro Yp ?_
                                      refine And.intro hGBp ?_
                                      refine And.intro hBYp.symm ?_
                                      refine And.intro hGnp ?_
                                      refine And.intro hYpp ?_
                                      refine And.intro hNonGBY ?_
                                      exact hRightGBY

                                    have hPerpAmbientNP :
                                        HilbertLinesPerpendicularAt
                                          Geo n pp.1 B0 :=
                                      (planeGeo_linesPerpendicularAt_iff_ambient
                                        (Geo := Geo)
                                        sigma np pp Bp).mp
                                        hPerpNpPp

                                    have hPerpPn :
                                        HilbertLinesPerpendicularAt
                                          Geo pp.1 n B0 :=
                                      hilbertLinesPerpendicularAt_symm_wyler
                                        (Geo := Geo)
                                        n pp.1 B0
                                        hPerpAmbientNP

                                    have hDisjointQP :
                                        HilbertLinesDisjoint Geo q pp.1 :=
                                      hilbert_XI8_coplanar_perpendiculars_to_same_line_disjoint_wyler
                                        (Geo := Geo)
                                        sigma
                                        q pp.1 n
                                        G B0
                                        hGB0
                                        hqsigma
                                        pp.2
                                        hnsigma
                                        hPerpQn
                                        hPerpPn

                                    have hDisjointPQ :
                                        HilbertLinesDisjoint Geo pp.1 q := by
                                      intro hMeet
                                      cases hMeet with
                                      | intro P hPMeet =>
                                          exact
                                            hDisjointQP
                                              (Exists.intro P
                                                (And.intro
                                                  hPMeet.2
                                                  hPMeet.1))

                                    have hB0q :
                                        Not (H.OnLine B0 q) := by
                                      intro hB0q
                                      exact
                                        hDisjointLQ
                                          (Exists.intro B0
                                            (And.intro hB0l hB0q))

                                    have hlp : l = pp.1 :=
                                      HilbertSpaceEuclidean.parallel_unique_in_plane
                                        (Geo := Geo)
                                        sigma
                                        q hqsigma
                                        B0 hB0sigma hB0q
                                        l pp.1
                                        hlsigma pp.2
                                        hB0l hDisjointLQ
                                        hBpp hDisjointPQ

                                    have hPerpLn :
                                        HilbertLinesPerpendicularAt
                                          Geo l n B0 := by
                                      rw [hlp]
                                      exact hPerpPn

                                    exact
                                      hilbertLinesPerpendicularAt_symm_wyler
                                        (Geo := Geo)
                                        l n B0
                                        hPerpLn

                  ----------------------------------------------------------------
                  -- Step 8. Apply the local transport twice.
                  ----------------------------------------------------------------

                  have hPerpNL1 :
                      HilbertLinesPerpendicularAt
                        Geo n l1.1 B.1 :=
                    hTransportAcrossParallel
                      l1.1 q1 B.1
                      hParallelL1Q1
                      hBl1
                      hBn
                      hGq1
                      hq1rho

                  have hPerpNL2 :
                      HilbertLinesPerpendicularAt
                        Geo n l2.1 B.1 :=
                    hTransportAcrossParallel
                      l2.1 q2 B.1
                      hParallelL2Q2
                      hBl2
                      hBn
                      hGq2
                      hq2rho

                  ----------------------------------------------------------------
                  -- Step 9. XI.4: the two perpendicular directions l1,l2
                  -- generate the normality of n to the whole plane pi.
                  ----------------------------------------------------------------

                  have hNormalPi :
                      HilbertLinePerpendicularPlaneAt
                        Geo n pi B.1 :=
                    euclid_proposition_11_4
                      (Geo := Geo)
                      pi
                      l1 l2
                      n
                      B
                      hl12
                      hPerpNL1
                      hPerpNL2

                  ----------------------------------------------------------------
                  -- Step 10. XI.14: the same line n is perpendicular to
                  -- both distinct planes pi and rho.
                  ----------------------------------------------------------------

                  exact
                    euclid_proposition_11_14
                      (Geo := Geo)
                      pi rho
                      n
                      B.1 G
                      hPlanesNe
                      hNormalPi
                      hNormalRho


end Geometry
